- src/components/organisms/NavigatorPane/components/ResourcesSection.tsx
This PR...
- hides sections that are empty
-
> feat: hide empty sections

- .husky/commit-msg
- commitlint.config.js
- package-lock.json
- package.json
To allow developers to add proper commit messages.
This commit messages will be gathered for preparing CHANGELOG file.
This PR...
-
-
> feat: Add commitlint

- src/components/molecules/NavigatorRowLabel/NavigatorRowLabel.tsx
- src/components/molecules/ScrollIntoView/ScrollIntoView.tsx
- src/components/organisms/NavigatorPane/NavigatorPane.tsx
- src/components/organisms/NavigatorPane/components/ResourcesSection.tsx
This PR...
- refactored how the expanded sections update when the selectedResource changes
-
> expand sections on scroll to selected resources

- README.md
> add note for unsigned binaries

- README.md
This PR improves README formatting
-
-
> chore: README formatting

- .github/workflows/monokle-build-mac.yml
- .github/workflows/monokle-build-windows.yml
> chore: update-workflow-tag-strategy

- src/kindhandlers/ClusterRole.handler.ts
- src/kindhandlers/ClusterRoleBinding.handler.ts
- src/kindhandlers/ConfigMap.handler.ts
- src/kindhandlers/CronJob.handler.ts
- src/kindhandlers/CustomResourceDefinition.handler.ts
- src/kindhandlers/DaemonSet.handler.ts
- src/kindhandlers/Deployment.handler.ts
- src/kindhandlers/Endpoint.handler.ts
- src/kindhandlers/Ingress.handler.ts
- src/kindhandlers/Job.handler.ts
- src/kindhandlers/NetworkPolicy.handler.ts
- src/kindhandlers/PersistentVolume.handler.ts
- src/kindhandlers/PersistentVolumeClaim.handler.ts
- src/kindhandlers/Pod.handler.ts
- src/kindhandlers/ReplicaSet.handler.ts
- src/kindhandlers/ReplicationController.handler.ts
- src/kindhandlers/Role.handler.ts
- src/kindhandlers/RoleBinding.handler.ts
- src/kindhandlers/Secret.handler.ts
- src/kindhandlers/Service.handler.ts
- src/kindhandlers/ServiceAccount.handler.ts
- src/kindhandlers/StatefulSet.handler.ts
- src/redux/initialState.ts
This PR...
-
- default value of apiVersionMatcher in all kindhandlers
> fix: default apiVersionMatcher in all kindhandlers

- src/components/molecules/Monaco/Monaco.tsx
This PR...
-
- source editor selection jumping to top every change
> fix: source editor selection jump

- package-lock.json
> chore: add package-lock from windows npm install

- src/components/molecules/FormEditor/FormEditor.tsx
- src/components/molecules/Monaco/Monaco.tsx
- src/components/molecules/Monaco/editorConstants.ts
- src/kindhandlers/Deployment.handler.ts
- src/kindhandlers/Service.handler.ts
- src/kindhandlers/index.ts
- src/models/k8sresource.ts
- src/redux/reducers/main.ts
- src/redux/services/fileEntry.ts
- src/redux/services/resource.ts
- src/redux/services/resourceRefs.ts
- src/redux/thunks/setRootFolder.ts
- src/redux/thunks/utils.ts
This PR...
- automatically update resource/file when the source code or FormEditor data has changed
- only reprocess resources that were affected by changes and their dependent resources
-
> Improve resource reprocessing and save mechanics

- electron/main.ts
- package-lock.json
- package.json
- public/Splashscreen.html
This PR...
- shows a splashscreen before the main browser window is loaded
-
> feat: show splashscreen before main window loads

- src/components/organisms/FileTreePane/FileTreePane.tsx
This PR...
*
* Updating the resource count of a file when changing it.
> fix: Fix resource count update on file change

- resources/cli/index.js
- src/App.tsx
- src/components/molecules/GraphView/GraphView.tsx
- src/components/molecules/GraphView/Sidebar.tsx
- src/components/molecules/LogViewer/LogViewer.tsx
- src/components/molecules/Monaco/Monaco.tsx
- src/components/molecules/NavigatorHelmRow/NavigatorHelmRow.tsx
- src/components/molecules/NavigatorRowLabel/NavigatorRowLabel.tsx
- src/components/organisms/ClustersPane/ClustersPane.tsx
- src/components/organisms/DiffModal/DiffModal.tsx
- src/components/organisms/FileTreePane/FileTreePane.tsx
- src/components/organisms/MessageBox/MessageBox.tsx
- src/components/organisms/NavigatorPane/NavigatorPane.tsx
- src/components/organisms/NavigatorPane/components/ResourcesSection.tsx
- src/components/organisms/PageHeader/PageHeader.tsx
This PR...
- resolve lint warnings
-
> chore: resolve lint warnings

- docs/architecture.md
- resources/schemas/k8sschemas.json
- src/kindhandlers/CronJob.handler.ts
- src/kindhandlers/CustomResourceDefinition.handler.ts
- src/kindhandlers/Endpoint.handler.ts
- src/kindhandlers/Ingress.handler.ts
- src/kindhandlers/Job.handler.ts
- src/redux/services/schema.ts
This PR...
- updates to the latest k8s resource schemas
- adds additional guards on schema extraction
-
> feat: updated to latest 1.22.1 k8s schemas

- electron/main.ts
- src/components/molecules/NavigatorHelmRow/NavigatorHelmRow.tsx
- src/components/organisms/FileTreePane/FileTreePane.tsx
- src/components/organisms/SettingsDrawer/SettingsDrawer.tsx
- src/constants/tooltips.ts
- src/models/appconfig.ts
- src/redux/initialState.ts
- src/redux/reducers/appConfig.ts
- src/redux/thunks/setRootFolder.ts
- src/utils/electronStore.ts
This PR...
- adds an "Auto load last recent folder on startup" option to the settings - and does just that
-
> feat: load last folder on startup

- src/components/organisms/ActionsPane/ActionsPane.tsx
- src/redux/services/applyHelmChartWithConfirm.tsx
- src/redux/services/fileEntry.ts
- src/redux/thunks/applyHelmChart.ts
> feat: added support for installing helm charts with Apply

- src/redux/thunks/applyFile.ts
- src/redux/thunks/applyHelmChart.ts
- src/redux/thunks/applyResource.ts
> fix: fixed reset of isApplyingResource on error

- src/kindhandlers/index.ts
This PR...
-
- the list of dependent resource kinds not being created correctly before reprocessing
> fix: get dependent resource kinds

- src/components/molecules/NavigatorRowLabel/ActionsMenu.tsx
- src/components/molecules/NavigatorRowLabel/NavigatorRowLabel.tsx
- src/kindhandlers/ClusterRole.handler.ts
- src/kindhandlers/ClusterRoleBinding.handler.ts
- src/kindhandlers/ConfigMap.handler.ts
- src/kindhandlers/CronJob.handler.ts
- src/kindhandlers/CustomResourceDefinition.handler.ts
- src/kindhandlers/DaemonSet.handler.ts
- src/kindhandlers/Deployment.handler.ts
- src/kindhandlers/Endpoints.handler.ts
- src/kindhandlers/Ingress.handler.ts
- src/kindhandlers/Job.handler.ts
- src/kindhandlers/NetworkPolicy.handler.ts
- src/kindhandlers/PersistentVolume.handler.ts
- src/kindhandlers/PersistentVolumeClaim.handler.ts
- src/kindhandlers/Pod.handler.ts
- src/kindhandlers/ReplicaSet.handler.ts
- src/kindhandlers/ReplicationController.handler.ts
- src/kindhandlers/Role.handler.ts
- src/kindhandlers/RoleBinding.handler.ts
- src/kindhandlers/Secret.handler.ts
- src/kindhandlers/Service.handler.ts
- src/kindhandlers/ServiceAccount.handler.ts
- src/kindhandlers/StatefulSet.handler.ts
- src/models/resourcekindhandler.ts
- src/redux/reducers/main.ts
- src/redux/services/fileEntry.ts
- src/redux/services/resource.ts
This PR...
- add logic to delete a resource from a file or from the cluster
- show ActionsMenu on hover over resources in navigator pane
- show delete resource action with confirm modal
-
> Delete resource from file/cluster

- docs/index.md
> added linebreak for formatting

- README.md
- docs/index.md
- mkdocs.yml
> switched places of features and getting-started

- package-lock.json
- package.json
> fix: update electron to latest 13.X version

- README.md
> Fixed snyk badge and added link to Discord Server

- src/components/atoms/SplitView/SplitView.tsx
- src/redux/initialState.ts
- src/utils/electronStore.ts
This PR...
-
- Resize problems on refresh screen
- Open main screen, resize panes and refresh the screen
-
> fix: Resizing issue on refresh

- src/kindhandlers/Namespace.handler.ts
- src/kindhandlers/index.ts
This PR...
- new kind handler to support Namespace objects
-
-
-
> feat: kind handler to support Namespace objects

- src/components/organisms/PaneManager/PaneManager.tsx
This PR...
- different icons when folder is open/closed
-
-
-
> feat: different icons when folder is open or not

- src/models/k8sresource.ts
- src/redux/services/manifest-utils.test.ts
- src/redux/services/resource.ts
- src/redux/services/resourceRefs.ts
This PR...
-
- missing ref links when the key path of multiple ref nodes was the same, probably happening only in arrays of objects
-
-
> fix: missing ref links

- src/kindhandlers/common/outgoingRefMappers.ts
> improved secretRef parsing to detect more refs..

- src/feature-flags.json
> chore: disable plugin manager

- src/components/molecules/ResourceRefsIconPopover/RefLink.tsx
- src/components/molecules/ResourceRefsIconPopover/RefsPopoverContent.tsx
- src/redux/services/resource.ts
This PR...
- makes refs popover content scrollable
- shows line:column next to refs
- removing duplicate refs
-
> resource refs improvements

- package.json
- src/components/molecules/Monaco/Monaco.tsx
- src/components/molecules/Monaco/useCodeIntel.ts
- src/redux/services/selection.ts
This PR...
-
- links not highlighted on first resource view
- cannot access 'isHighlighted' of undefined error
-
-
> fix: links not highlighted on first resource view & cannot access isHighlighted of undefined

- .gitignore
- electron/env..example.ts
- electron/main.ts
- env.example.ts
- src/utils/files.ts
This PR...
- Place env.ts file into electron folder.
- Module not found error.
- Run or build application
-
> fix: Place env.ts file into electron folder

- src/components/organisms/FileTreePane/FileTreePane.tsx
- src/redux/reducers/main.ts
- src/redux/services/fileEntry.ts
This PR...
-
- new files not showing in file explorer
-
-
> fix: new files not showing in file explorer

- src/components/organisms/NavigatorPane/NavSectionRenderer/NavSectionItem/NavSectionItem.tsx
- src/components/organisms/NavigatorPane/NavSectionRenderer/NavSectionRenderer.tsx
- src/components/organisms/NavigatorPane/NavSectionRenderer/styled.tsx
This PR...
- add missing deps to hooks
- change color of expand button if section is collapsed and selected
- show the items length next to section names
-
-
-
> navigator small improvements

- electron/main.ts
- electron/menu.ts
- package-lock.json
- src/components/atoms/Drawer/Drawer.tsx
- src/components/organisms/PageHeader/PageHeader.tsx
- src/components/organisms/SettingsDrawer/SettingsDrawer.tsx
- src/components/organisms/UpdateModal/UpdateModal.tsx
This PR...
- Remove Monokle update logic from settings drawer
- Improve Monokle update logic on menu item
- Fix staying modals under of Settings drawer
-
-
> feat: Remove Monokle update from settings && improve on menu item

- src/redux/services/kustomize.ts
- src/redux/services/resource.ts
> fix: fixed creation of unsatisfied refs for missing patch files

- electron/main.ts
- electron/src/initKubeconfig.ts
- package-lock.json
- src/App.tsx
- src/redux/reducers/appConfig.ts
- src/utils/env.ts
This PR...
- move kubeconfig init logic to main
- kubeconfig not being initialized properly
-
-
> refactor: move kubeconfig init logic to main

- src/components/molecules/Monaco/Monaco.tsx
- src/components/organisms/FileTreePane/FileTreePane.tsx
- src/redux/reducers/main.ts
- src/redux/services/fileEntry.ts
- src/redux/services/resource.ts
- src/redux/thunks/saveUnsavedResource.ts
- src/redux/thunks/setRootFolder.ts
- src/utils/files.ts
This PR...
-
-  catch fs statSync errors
-
-
> fix: catch fs statSync errors

- electron/menu.ts
This PR...
- Add toggle dev tools option to the application menu
-
-
-
> feat: Add toggle dev tools option to the application menu

- package.json
- src/components/molecules/ResourceRefsIconPopover/RefLink.tsx
- src/components/molecules/ResourceRefsIconPopover/RefsPopoverContent.tsx
- src/components/molecules/ResourceRefsIconPopover/ResourceRefsIconPopover.tsx
- src/components/organisms/NavigatorPane/NavSectionRenderer/NavSectionItem/NavSectionItem.tsx
- src/components/organisms/NavigatorPane/NavSectionRenderer/NavSectionItem/useItemCustomization.ts
- src/models/navsection.ts
- src/navsections/K8sResourceNavSection/ResourceKindPrefix.tsx
- src/navsections/K8sResourceNavSection/ResourceKindSuffix.tsx
- src/navsections/KustomizationNavSection/KustomizationPrefix.tsx
- src/navsections/KustomizationNavSection/KustomizationSuffix.tsx
> upgrade monaco-yaml & hide links for disabled items & disable kustomization links in preview

- src/App.tsx
> fix: wrap missing deps listener in useEffect

- src/navsections/HelmChartNavSection/HelmChartQuickAction.tsx
- src/navsections/KustomizationNavSection/KustomizationQuickAction.tsx
- src/redux/services/preview.ts
- src/redux/thunks/previewCluster.ts
- src/redux/thunks/previewHelmValuesFile.ts
- src/redux/thunks/previewKustomization.ts
> fix: fixed calls to restartPreview for Helm and Kustomizations

- src/components/organisms/FileTreePane/FileTreePane.tsx
> fix: wrap 'executed-from' listener with useEffect

- package-lock.json
> fix: rebuild package-lock

- src/redux/reducers/appConfig.ts
This PR...
-
- Update modal show issue on boot up
-
-
> fix: Fix logic operator

- src/components/molecules/Monaco/Monaco.tsx
> fix: fixed read-only check

- package.json
This PR...
- changes the windows installer from oneclick to assisted, presenting installation options.
> feat: enhance windows installer with options

- src/components/organisms/NavigatorPane/NavSectionRenderer/useNavSection.ts
> fix: useNavSection react hooks deps

- src/components/organisms/NavigatorPane/NavSectionRenderer/NavSectionRenderer.tsx
- src/components/organisms/NavigatorPane/NavSectionRenderer/useNavSection.ts
- src/models/navsection.ts
- src/navsections/HelmChartNavSection/HelmChartNavSection.ts
- src/navsections/K8sResourceNavSection/ResourceKindNavSection.ts
- src/navsections/KustomizationNavSection/KustomizationNavSection.ts
> refactor: sort items in nav sections and allow helm charts with same name

- package-lock.json
- src/components/organisms/NavigatorPane/SectionRenderer/ItemRenderer/ItemRenderer.tsx
- src/components/organisms/NavigatorPane/WarningsAndErrorsDisplay.tsx
- src/models/navigator.ts
- src/redux/initialState.ts
- src/redux/reducers/navigator.ts
This PR...
- add popup for warning/errors at top of navigator pane
-
-
-
> feat: add popup to error/warning counters

- electron/commands.ts
- src/components/atoms/FileExplorer/FileExplorer.tsx
- src/hooks/useFileExplorer.tsx
- src/redux/services/fileEntry.ts
> fix: set default folder to current root when selecting files/folders

- electron/menu.ts
- src/components/organisms/NotificationsDrawer/NotificationsDrawer.tsx
- src/hooks/useCopyToClipboard.ts
- src/models/alert.ts
- Added a possibility to copy any text in the application.
- Added copy-to-clipboard functionality in notification.
- Changed the behavior when the user could not copy any text in the application because this feature was working only under specific conditions.
> feat: added a possibility to copy any text in the application

- src/components/molecules/IconWithPopover/IconWithPopover.tsx
- src/components/molecules/IconWithPopover/index.ts
- src/components/molecules/ResourceFilter/ResourceFilter.tsx
- src/components/organisms/NavigatorPane/NavigatorPane.styled.tsx
- src/components/organisms/NavigatorPane/NavigatorPane.tsx
- src/components/organisms/NavigatorPane/SectionRenderer/SectionHeader.tsx
- Displayed the number of filters applied.
- Refactored code a bit: type and interface declarations.
- Added new reusable component IconWithPopover.
- Fixed behavior when user could not reset all the filters.
> feat: displayed the number of filters applied

- src/components/organisms/NotificationsDrawer/NotificationsDrawer.tsx
This PR...
-
- Notification id issue
- Badge ref issue
-
-
> fix: notification key issue & badge ref issue

- package.json
- src/components/organisms/ActionsPane/ActionsPane.tsx
- src/redux/selectors.ts
- src/redux/services/applyResourceWithConfirm.tsx
- src/redux/services/resource.ts
- src/redux/services/resourceRefs.ts
- src/redux/services/schema.ts
- src/redux/services/selection.ts
- src/redux/thunks/applyResource.ts
- src/redux/thunks/diffResource.ts
This PR:
- shows correct notification if diff fails with an error
- disables diff for kustomization and kustomization patches
- updates electron to 15.3.1
> electron update, kustomize and diff fixes, import formatting

- src/components/molecules/ClusterDiff/ClusterDiff.tsx
- src/components/molecules/ResourceDiff/ResourceDiff.tsx
- src/components/molecules/ResourceDiff/index.ts
- src/components/molecules/index.ts
- src/components/organisms/ClusterDiffModal/ClusterDiffModal.tsx
- src/components/organisms/DiffModal/DiffModal.tsx
- src/components/organisms/FileTreePane/FileTreePane.tsx
- src/components/organisms/NavigatorPane/ClusterComparisonButton.tsx
- src/components/organisms/NavigatorPane/NavigatorPane.styled.tsx
- src/components/organisms/NavigatorPane/NavigatorPane.tsx
- src/constants/tooltips.ts
- src/models/appstate.ts
- src/navsections/ClusterDiffSectionBlueprint/ResourceMatchNameDisplay.tsx
- src/navsections/HelmChartSectionBlueprint/HelmChartSectionBlueprint.ts
- src/navsections/KustomizationSectionBlueprint/KustomizationSectionBlueprint.ts
- src/redux/reducers/main.ts
- src/redux/selectors.ts
- src/redux/services/applyResourceWithConfirm.tsx
- src/redux/services/clusterResource.ts
- src/redux/thunks/applyResource.ts
- src/redux/thunks/diffResource.ts
- src/redux/thunks/loadClusterDiff.ts
- src/styles/Colors.ts
This PR...
- open the resource diff inside the cluster comparison modal
- UI changes and improvements
-
-
-
> Cluster Comparison improvements

- src/redux/services/clusterResource.ts
> fix: fixed correct context usage in cluster comparison resource diff

- src/components/molecules/ResourceFilter/ResourceFilter.tsx
This PR...
- fixed behavior when resource filters were not showing the same value
> fix: fixed behavior when resource filters were not showing the same value

- src/constants/clusterResource.ts
- src/constants/tooltips.ts
- src/redux/thunks/diffResource.ts
> fix: added selfLink to ignored paths, improved error/tooltip messages

- electron/main.ts
- src/utils/index.ts
> fix: changed dependency-check to use execSync with node env

- src/components/organisms/ClustersPane/ClustersPane.tsx
- src/constants/tooltips.ts
> fix: improved wording/tooltip

- src/components/molecules/FilePatternList/FilePatternList.tsx
- src/components/organisms/SettingsDrawer/SettingsDrawer.tsx
- src/hooks/useOnClickOutside.ts
- src/utils/hooks.ts
This PR...
- fixed bug when the user couldn't blur from input in the Settings Drawer
> fix: fixed bug when the user couldn't blur from input in the Settings Drawer

- package-lock.json
- src/components/atoms/SplitView/SplitView.tsx
This PR...
- Left pane will not be closed by drag event
-
-
-
> feat: Disable left navigation closing behaviour

- src/components/organisms/NavigatorPane/ClusterCompareButton.tsx
- src/components/organisms/NavigatorPane/ClusterComparisonButton.tsx
- src/components/organisms/NavigatorPane/NavigatorPane.tsx
- src/redux/reducers/main.ts
- src/utils/hooks.ts
> fix: reset state after loading new folder + small fixes

- electron/main.ts
- electron/src/initKubeconfig.ts
- package-lock.json
- src/components/organisms/ClustersPane/ClustersPane.tsx
- src/components/organisms/PaneManager/PaneManager.tsx
- src/constants/tooltips.ts
- src/models/appconfig.ts
- src/models/appstate.ts
- src/models/uiCoach.ts
- src/redux/initialState.ts
- src/redux/main-store.ts
- src/redux/reducers/appConfig.ts
- src/redux/reducers/main.ts
- src/redux/reducers/uiCoach.ts
- src/redux/store.ts
- src/utils/electronStore.ts
This PR...
- WIP: displayed the Warning icon if the user did not specify the path to kubeconfig
> feat: displayed the Warning icon if the user did not specify the path to kubeconfig

- src/components/molecules/ResourceDiff/ResourceDiff.tsx
- src/navsections/ClusterDiffSectionBlueprint/ResourceMatchNameDisplay.tsx
> fix: disable replace while in preview mode

- README.md
- docs/getting-started.md
- mkdocs.yml
- package-lock.json
> docs: re-added the getting-started document and updated readme content

- src/navsections/ClusterDiffSectionBlueprint/ClusterDiffSectionNameDisplay.tsx
> refactor: show title tags in cluster compare

- README.md
- docs/index.md
> chore: add overview gif to readme and docs

- CHANGELOG.md
- package-lock.json
- package.json
This PR...
- Release new 1.3.1 version
-
-
-
> chore(release): 1.3.1

- src/components/molecules/ResourceDiff/ResourceDiff.tsx
- src/components/organisms/DiffModal/DiffModal.tsx
> fix: set diff editors as read only

- src/redux/services/validation.ts
I suggest we get this in until we implement fix #668
> fix: intermediate fix that ignores lastProbeTime/creationTimestamp validation errors

- src/components/atoms/Dots/Dots.tsx
- src/components/atoms/Dots/index.ts
- src/components/molecules/ContextMenu/ContextMenu.tsx
- src/components/molecules/ContextMenu/index.ts
- src/components/molecules/SectionRenderer/ItemRenderer/styled.tsx
- src/components/organisms/FileTreePane/FileTreePane.tsx
- added open in finder/explorer button in File Explorer
> feat: added open in finder/explorer button in File Explorer

- src/components/atoms/index.ts
- src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenu.tsx
> refactor: use Dots component for resource row context menu

- src/components/molecules/Monaco/Monaco.tsx
- src/components/molecules/SectionRenderer/SectionHeader.tsx
- src/components/molecules/SectionRenderer/styled.tsx
- src/components/organisms/ActionsPane/ActionsPane.tsx
- src/navsections/K8sResourceSectionBlueprint/ResourceKindNameDisplay.tsx
> Fix Monaco errors and some styles

- electron/main.ts
- src/components/organisms/ClustersPane/ClustersPane.tsx
- src/components/organisms/PageHeader/PageHeader.tsx
> fix: improved wording in page header and window title

- src/components/organisms/ActionsPane/ActionsPane.tsx
- src/redux/thunks/applyFile.ts
- src/redux/thunks/applyResource.ts
- src/redux/thunks/applyYaml.ts
> fix: extracted apply to shared method and fixed context dependency

- src/redux/services/resource.ts
> fix: fixed recalculation of kustomization resources on change

- src/components/molecules/SectionRenderer/SectionHeader.tsx
- src/components/molecules/SectionRenderer/styled.tsx
> fix: section items length color when section is selected and collapsed

- src/components/organisms/PageHeader/PageHeader.tsx
> chore: change notifications icon

- src/components/molecules/PreviewDropdown/PreviewDropdown.tsx
- src/components/molecules/PreviewDropdown/index.ts
- src/components/molecules/index.ts
- src/components/organisms/ClusterDiffModal/ClusterDiffModal.tsx
- src/models/appstate.ts
- src/navsections/ClusterDiffSectionBlueprint/ClusterDiffSectionBlueprint.ts
- src/navsections/ClusterDiffSectionBlueprint/ClusterDiffSectionNameDisplay.tsx
- src/redux/reducers/main.ts
> feat: preview dropdown in cluster compare

- src/components/molecules/SectionRenderer/SectionRenderer.tsx
> fix: missing prop

- .github/workflows/monokle-sign-notarize-publish-linux.yml
- .github/workflows/monokle-sign-notarize-publish.yml
- electron/auto-update/index.ts
- electron/commands.ts
- electron/main.ts
- package-lock.json
This PR...
- workflows to handle built and release for updates
- listen only latest-version tag for new updates
-
-
-
> Auto updater release workflow

- src/components/molecules/Monaco/Monaco.tsx
- src/redux/services/fileEntry.ts
> fix: minor glitches

- src/components/organisms/ClusterDiffModal/ClusterDiffModal.tsx
- src/models/appstate.ts
- src/navsections/ClusterDiffSectionBlueprint/ClusterDiffSectionBlueprint.ts
- src/navsections/ClusterDiffSectionBlueprint/ClusterDiffSectionNameDisplay.tsx
- src/navsections/ClusterDiffSectionBlueprint/ResourceMatchNameDisplay.tsx
- src/redux/initialState.ts
- src/redux/reducers/main.ts
- src/redux/services/applySelectedMatchesWithConfirm.tsx
- src/redux/services/resource.ts
- src/redux/thunks/applySelectedResourceMatches.ts
- src/utils/resources.ts
This PR...
- logic to apply multiple resources
- added checkboxes to select resource matches in the cluster compare
- added button to deploy selected local resources
-
-
-
> feat: cluster compare multiselect deploy

- src/redux/reducers/main.ts
> Fix handling of discarded resourceId when exiting preview

- package.json
- src/components/molecules/PreviewDropdown/PreviewDropdown.tsx
- src/index.css
> Preview dropdown improvements

- src/components/molecules/Monaco/Monaco.tsx
- src/components/molecules/Monaco/useDebouncedCodeSave.ts
- src/components/organisms/FileTreePane/FileTreePane.tsx
- src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenu.tsx
- src/redux/reducers/main.ts
> fix: editing values files, helm preview selection, disabled selecting excluded files

- src/redux/services/resource.ts
> fix: check if file exists before deletion

- CHANGELOG.md
- package-lock.json
- package.json
This PR...
- 1.3.2 release
-
-
-
> chore(release): 1.3.2

- electron/menu.ts
- src/App.tsx
- src/components/molecules/FilePatternList/FilePatternList.tsx
- src/components/organisms/FileTreePane/FileTreePane.tsx
- src/components/organisms/RenameEntityModal/RenameEntityModal.tsx
- src/components/organisms/RenameEntityModal/index.ts
- src/components/organisms/SettingsDrawer/SettingsDrawer.tsx
- src/components/organisms/index.ts
- src/constants/tooltips.ts
- src/models/appconfig.ts
- src/models/ui.ts
- src/redux/initialState.ts
- src/redux/reducers/appConfig.ts
- src/redux/reducers/ui.ts
- src/utils/files.ts
This PR...
- added Rename file or folder functionality to File Explorer
- added Select All hotkey (ctrl+a or cmd+a)
> feat: added Rename button to File Explorer

- electron/commands.ts
- src/utils/index.ts
> fix: make sure kustomize/helm commands use environment path

- src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenu.tsx
- src/redux/reducers/main.ts
> fix resource selection when removing a resouce

- src/components/molecules/Monaco/Monaco.tsx
- src/redux/reducers/ui.ts
- fixed path to path library
- fixed monaco editor scroll
> fix: fixed path to path library, fixed monaco editor scroll

- src/components/organisms/PageHeader/PageHeader.tsx
- src/components/organisms/PageHeader/tooltips.ts
- added tooltips to all icons in the right top corner
> feat: added tooltips to all icons in the right top corner

- src/components/molecules/Monaco/Monaco.tsx
> refactor: improve useEffect in Monaco

- .husky/pre-commit
- .husky/pre-push
- package-lock.json
- package.json
This PR...
- pre-commit: run prettier on staged files 
- pre-push: run eslint on all src files (this was on pre-commit before)
-
-
-
> refactor: pre-commit to pre-push

- electron/main.ts
- src/utils/index.ts
> fix: hide dependency warning if the user can run kubectl kustomize

- src/components/molecules/SectionRenderer/ItemRenderer/ItemRenderer.tsx
- src/components/organisms/NavigatorPane/WarningsAndErrorsDisplay.tsx
- src/models/navigator.ts
- src/redux/initialState.ts
- src/redux/reducers/navigator.ts
> fix: errors & warnings navigation

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 1.3.3

- package.json
please give this a try before approving!
This PR...
-
-
-
-
> update electron to 16.0.1

- src/components/organisms/ActionsPane/ActionsPane.tsx
- src/kindhandlers/ClusterRole.handler.ts
- src/kindhandlers/ConfigMap.handler.ts
- src/kindhandlers/Namespace.handler.ts
- src/kindhandlers/Secret.handler.ts
- src/models/resourcekindhandler.ts
- src/utils/shell.ts
- added the External Link to Documentation button to the Editor
- ![image](https://user-images.githubusercontent.com/25991946/143261062-872aa8dd-9292-4c7e-9942-b21db7217e5b.png)
> feat: added the External Link to Documentation button to the Editor

- src/components/organisms/ActionsPane/ActionsPane.styled.tsx
- src/components/organisms/ActionsPane/ActionsPane.tsx
- src/components/organisms/ActionsPane/tooltips.ts
- src/kindhandlers/ClusterRoleBinding.handler.ts
- src/kindhandlers/CronJob.handler.ts
- src/kindhandlers/CustomResourceDefinition.handler.ts
- src/kindhandlers/DaemonSet.handler.ts
- src/kindhandlers/Deployment.handler.ts
- src/kindhandlers/Endpoints.handler.ts
- src/kindhandlers/Ingress.handler.ts
- src/kindhandlers/Job.handler.ts
- src/kindhandlers/NetworkPolicy.handler.ts
- src/kindhandlers/PersistentVolume.handler.ts
- src/kindhandlers/PersistentVolumeClaim.handler.ts
- src/kindhandlers/Pod.handler.ts
- src/kindhandlers/ReplicaSet.handler.ts
- src/kindhandlers/ReplicationController.handler.ts
- src/kindhandlers/Role.handler.ts
- src/kindhandlers/RoleBinding.handler.ts
- src/kindhandlers/Service.handler.ts
- src/kindhandlers/ServiceAccount.handler.ts
- src/kindhandlers/StatefulSet.handler.ts
- src/kindhandlers/VolumeAttachment.handler.ts
- added links to documentation
> feat: added links to documentation

- src/navsections/HelmChartSectionBlueprint/HelmChartSectionBlueprint.ts
- src/navsections/KustomizationSectionBlueprint/KustomizationSectionBlueprint.ts
> fix: helm & kustomize empty displays

- src/components/organisms/PaneManager/PaneManager.tsx
- src/models/ui.ts
- src/redux/reducers/ui.ts
> fix: left menu selection on setRootFolder

- src/components/molecules/Monaco/Monaco.tsx
- src/components/molecules/Monaco/codeIntel.ts
- src/components/molecules/Monaco/editorHelpers.ts
- src/components/molecules/Monaco/useCodeIntel.ts
- src/components/organisms/NewResourceWizard/NewResourceWizard.tsx
- src/models/ui.ts
- src/redux/services/fileEntry.ts
> fix: added hover command to create new resource for unsatisfied refs

- package-lock.json
- resources/form-schemas/deployment-schema.json
- resources/form-schemas/deployment-ui-schema.json
- resources/form-schemas/secret-schema.json
- resources/form-schemas/secret-ui-schema.json
- src/components/molecules/FormEditor/FormEditor.tsx
- src/components/molecules/FormEditor/FormWidgets/SecretKindSelection.tsx
- src/components/molecules/FormEditor/FormWidgets/index.ts
- src/components/organisms/ActionsPane/ActionsPane.tsx
- src/kindhandlers/common/formLoader.ts
This PR...
- Allow selecting Deployment environment values from Secret kind resource
- Allow selecting docker hub credentials from Secret kind resource
- Redesign Secret and Deployment kind resources from schema
-
-
> feat: select from Secret kind resource

- electron/commands.ts
- src/utils/index.ts
> fix: hide shell windows

- package.json
> fix: updated to electron 16.0.2

- src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
- src/constants/hotkeys.ts
- added hotkeys to navigate between panes
> feat: added hotkeys to navigate between panes

- package-lock.json
- src/components/atoms/Icon/Icon.tsx
- src/components/organisms/PageHeader/PageHeader.tsx
- src/components/organisms/PaneManager/MenuIcon.tsx
- src/components/organisms/PaneManager/PaneManager.tsx
- src/components/organisms/SettingsDrawer/SettingsDrawer.tsx
- src/index.css
- src/models/ui.ts
- src/redux/initialState.ts
- src/redux/reducers/ui.ts
- src/utils/electronStore.ts
This PR...
- Add cluster status to header
-
-
-
> feat: add cluster context status to header

- src/components/organisms/ActionsPane/ActionsPane.styled.tsx
- src/components/organisms/ActionsPane/ActionsPane.tsx
- improved documentation button
> fix: improved documentation button

- src/components/organisms/ClusterDiffModal/ClusterDiffModal.tsx
- src/redux/reducers/main.ts
- src/redux/services/replaceSelectedMatchesWithConfirm.tsx
- src/redux/thunks/replaceSelectedResourceMatches.ts
> feat: cluster diff replace selected resources

- src/components/molecules/Monaco/codeIntel.ts
- src/redux/services/manifest-utils.test.ts
- src/redux/services/manifest-utils.ts
> fix: fixed removal of empty maps/sequences when merging yaml files

- src/navsections/UnknownResourceSectionBlueprint/UnknownResourceSectionBlueprint.ts
> fix: unknown resources section filtering + icons

- src/redux/services/resource.ts
temporary fix until we implement #823 
-
-
-
-
> fix: fixed reprocessing of patch-resources

- src/components/organisms/NewResourceWizard/NewResourceWizard.tsx
- fixed behavior when the user could add a new namespace to the list of namespaces
> fix: fixed behavior when the user could add a new namespace to the list of namespaces

- src/components/organisms/ClustersPane/ClustersPane.tsx
This PR...
-
- Cluster pane height
-
-
> fix: set clusterpane height to inherit

- src/components/atoms/KeyValueInput/KeyValueInput.tsx
> fix: resource filter crashing

- src/components/organisms/ActionsPane/ActionsPane.tsx
This PR...
- disabled the diff button for cluster resources because we will have to refactor `performResourceDiff` to make the diff work properly
-
-
-
> fix: disable diff button for cluster resources

- src/components/organisms/ActionsPane/ActionsPane.tsx
- fixed behavior when NavTab had ellipsis under conditions
> fix: fixed behavior when NavTab had ellipsis under conditions

- electron/main.ts
- electron/pluginService.ts
- src/components/organisms/PaneManager/PaneManager.tsx
- src/components/organisms/PluginManagerPane/PluginInformation.tsx
- src/components/organisms/PluginManagerPane/PluginInstallModal.tsx
- src/components/organisms/PluginManagerPane/PluginManagerPane.tsx
- src/components/organisms/TemplatesPane/TemplatesPane.tsx
- src/components/organisms/TemplatesPane/index.ts
- src/components/organisms/index.ts
- src/constants/tooltips.ts
- src/feature-flags.json
- src/models/plugin.ts
- src/models/ui.ts
- src/redux/reducers/main.ts
This PR...
- simplified logic for downloading plugins from a github repo
- added logic for parsing/loading existing plugins on startup
-
-
-
> feat: initial logic for plugins downloading and parsing

- src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
- src/constants/hotkeys.ts
This PR...
-
- removes Cluster Pane hotkey
-
-
> fix: remove cluster pane hotkey

- src/components/molecules/Monaco/codeIntel.ts
- src/components/molecules/Monaco/editorHelpers.ts
- src/components/molecules/Monaco/symbolProcessing.ts
> feat: added hover for decoded secret values

- src/components/organisms/FileTreePane/FileTreePane.tsx
- src/components/organisms/NewResourceWizard/NewResourceWizard.styled.tsx
- src/components/organisms/NewResourceWizard/NewResourceWizard.tsx
- src/components/organisms/PageHeader/PageHeader.tsx
- src/models/ui.ts
This PR...
- adds option to save new resource to existing file
- Change style of load/reload action button
-
-
> feat: add new resources to existing file

- src/components/molecules/SectionRenderer/SectionHeader.tsx
- src/components/molecules/SectionRenderer/SectionRenderer.tsx
- src/components/molecules/SectionRenderer/styled.tsx
- src/components/molecules/SectionRenderer/useSectionCustomization.ts
- src/models/navigator.ts
- src/navsections/K8sResourceSectionBlueprint/ResourceKindSectionBlueprint.ts
- src/navsections/K8sResourceSectionBlueprint/ResourceKindSectionNameSuffix.tsx
- src/navsections/K8sResourceSectionBlueprint/ResourceKindSectionSuffix.tsx
- src/navsections/sectionBlueprintMiddleware.ts
> feat: quick create resource from resource section

- src/components/molecules/ScrollIntoView/ScrollIntoView.tsx
- src/components/molecules/SectionRenderer/ItemRenderer/ItemRenderer.tsx
- src/components/molecules/SectionRenderer/ItemRenderer/styled.tsx
- src/models/appstate.ts
- src/models/navigator.ts
- src/navsections/K8sResourceSectionBlueprint/ResourceKindSectionBlueprint.ts
- src/navsections/sectionBlueprintMiddleware.ts
- src/redux/initialState.ts
- src/redux/reducers/main.ts
This PR...
- added `isCheckable` and `isChecked` handlers to the item builder
- added `isCheckVisibleOnHover` to item customization
- rendered checkbox in `ItemRenderer` based on the values above
-
-
-
> feat: logic for handling & rendering section items checkboxes

- src/components/molecules/ResourceDiff/ResourceDiff.tsx
- src/components/molecules/SectionRenderer/ItemRenderer/ItemRenderer.tsx
- src/components/molecules/SectionRenderer/ItemRenderer/styled.tsx
- src/components/organisms/ClusterDiffModal/ClusterDiffModal.tsx
- src/components/organisms/DiffModal/DiffModal.tsx
- src/navsections/ClusterDiffSectionBlueprint/ClusterDiffSectionNameDisplay.tsx
- src/navsections/ClusterDiffSectionBlueprint/ResourceMatchNameDisplay.tsx
- Resizable Cluster Compare Modal
- Resizable Resource Diff Modal
> feat: Cluster Compare modal resizable

- src/components/atoms/PaneContainer/PaneContainer.tsx
- src/components/molecules/ClusterDiff/ClusterDiff.styled.tsx
- src/components/molecules/ClusterDiff/ClusterDiff.tsx
- src/components/molecules/FormEditor/FormEditor.tsx
- src/components/molecules/ResourceRefsIconPopover/RefsPopoverContent.tsx
- src/components/organisms/FileTreePane/FileTreePane.tsx
- src/components/organisms/HelmPane/styled.tsx
- src/components/organisms/KustomizePane/styled.tsx
- src/components/organisms/NavigatorPane/NavigatorPane.styled.tsx
- src/components/organisms/NavigatorPane/NavigatorPane.tsx
- src/components/organisms/NavigatorPane/WarningsAndErrorsDisplay.tsx
- src/styles/Colors.ts
- src/utils/scrollbar.ts
- Adds styling to the scrollbar
> feat: Styled scrollbar

- src/kindhandlers/ClusterRoleBinding.handler.ts
- src/kindhandlers/Endpoints.handler.ts
- src/kindhandlers/Ingress.handler.ts
- src/kindhandlers/PersistentVolume.handler.ts
- src/kindhandlers/PersistentVolumeClaim.handler.ts
- src/kindhandlers/RoleBinding.handler.ts
- src/kindhandlers/Secret.handler.ts
- src/kindhandlers/Service.handler.ts
- src/kindhandlers/ServiceAccount.handler.ts
- src/kindhandlers/VolumeAttachment.handler.ts
- src/kindhandlers/common/outgoingRefMappers.ts
- src/models/k8sresource.ts
- src/models/resourcekindhandler.ts
- src/redux/reducers/main.ts
- src/redux/services/fileEntry.ts
- src/redux/services/resource.ts
- src/redux/services/resourceRefs.ts
improved parsing and ref-processing performance substantially - for around 1000 resources time went from 1200 ms to 20ms
> ref parsing/processing performance

- src/components/organisms/FileTreePane/FileTreePane.tsx
- src/models/fileentry.ts
- src/redux/services/fileEntry.ts
- Different styling for excluded and unsupported files
> refactor: Styling for excluded/unsupported files

- src/components/molecules/FormEditor/FormEditor.tsx
- src/components/organisms/ActionsPane/ActionsPane.tsx
- src/kindhandlers/ClusterRole.handler.ts
- src/kindhandlers/ClusterRoleBinding.handler.ts
- src/kindhandlers/ConfigMap.handler.ts
- src/kindhandlers/CronJob.handler.ts
- src/kindhandlers/CustomResourceDefinition.handler.ts
- src/kindhandlers/DaemonSet.handler.ts
- src/kindhandlers/Deployment.handler.ts
- src/kindhandlers/Endpoints.handler.ts
- src/kindhandlers/Ingress.handler.ts
- src/kindhandlers/Job.handler.ts
- src/kindhandlers/Namespace.handler.ts
- src/kindhandlers/NetworkPolicy.handler.ts
- src/kindhandlers/PersistentVolume.handler.ts
- src/kindhandlers/PersistentVolumeClaim.handler.ts
- src/kindhandlers/Pod.handler.ts
- src/kindhandlers/ReplicaSet.handler.ts
- src/kindhandlers/ReplicationController.handler.ts
- src/kindhandlers/Role.handler.ts
- src/kindhandlers/RoleBinding.handler.ts
- src/kindhandlers/Secret.handler.ts
- src/kindhandlers/Service.handler.ts
- src/kindhandlers/ServiceAccount.handler.ts
- src/kindhandlers/StatefulSet.handler.ts
- src/kindhandlers/VolumeAttachment.handler.ts
- src/kindhandlers/common/customObjectKindHandler.ts
- src/kindhandlers/index.ts
- src/models/resourcekindhandler.ts
- src/redux/thunks/previewCluster.ts
and improved loading o…f custom resources from cluster
This PR...
-
-
-
-
> feat: enabled form editor for custom resources

- src/components/organisms/FileTreePane/FileTreePane.tsx
- src/redux/services/fileEntry.ts
- src/redux/services/helm.ts
> feat: added preview menu item to kustomization and helm-vaues files 

- src/components/organisms/NewResourceWizard/NewResourceWizard.tsx
- src/kindhandlers/index.ts
- src/redux/services/schema.ts
This PR also fixes the New Resource dialog to contain all resource kinds
-
-
-
-
> fix: loading of editor schemas for bundled CRDs

- src/redux/reducers/ui.ts
> fix: removed old reducer actions

- README.md
- docs/index.md
> docs: added latest blogpost to index.md

- docs/overview.md
Added a missing period.
This PR...
-
-
-
-
> update overview.md with period

- src/components/molecules/Monaco/Monaco.tsx
- src/redux/reducers/main.ts
- src/redux/services/kustomize.ts
> fix: possibility to update kustomization and patch file during preview

- src/components/molecules/FormEditor/FormEditor.tsx
- src/components/organisms/ActionsPane/ActionsPane.tsx
- src/components/organisms/NavigatorPane/NavigatorPane.tsx
> fix: editor pane overflow

- package-lock.json
- src/navsections/KustomizePatchSectionBlueprint/KustomizePatchSectionBlueprint.ts
This PR...
Disable patch resources for Cluster Mode
-
- Just run preview in cluster mode
> feat: Disable patch resources in cluster mode

- src/components/molecules/SectionRenderer/SectionHeader.tsx
- src/components/molecules/SectionRenderer/SectionRenderer.tsx
- src/components/molecules/SectionRenderer/styled.tsx
This PR...
Added ellipsis to section headers
#958 
Make the window really small
> Fix element wrapping section headers

- .github/workflows/monokle-build-nightly.yml
- .github/workflows/monokle-sign-notarize-publish-linux.yml
- .github/workflows/monokle-sign-notarize-publish.yml
> fix: added USE_HARD_LINKS: false to electron builder actions

- package.json
This PR...
attempts to fix pipeline errors
> fix: set electron-builder version to 22.11.7

- src/components/organisms/ActionsPane/ActionsPane.tsx
- adjust distances in action pane
- fix: #989 
- Open a custom resource and reduce the width of the screen
- https://user-images.githubusercontent.com/5509112/149790029-272d9341-9727-4cfe-967f-ee2ee68eca63.mov
> fix: see more documentation flicker

- electron/commands.ts
- electron/main.ts
- package.json
- src/components/organisms/SettingsDrawer/SettingsDrawer.tsx
- src/constants/tooltips.ts
- src/models/appconfig.ts
- src/redux/initialState.ts
- src/redux/reducers/appConfig.ts
- src/redux/reducers/ui.ts
- src/redux/thunks/previewKustomization.ts
This PR also removes the persistence of some uiState properties which didn't make sense to me :) 
-
-
-
> feat: added setting for enabling Helm with Kustomize

- electron/utils.ts
This PR...
- message typo
-
-
-
> fix: message typo

- electron/templateService.ts
- src/components/organisms/TemplateModal/TemplateModal.tsx
- src/models/template.ts
- src/redux/services/manifest-utils.ts
- src/redux/services/previewReferencedHelmChart.ts
- src/redux/services/templates.ts
This PR...
- adds support for vanilla templates
-
- Install the https://github.com/devcatalin/monokle-test-plugin which now contains a vanilla template as well
-
> feat: support for vanilla templates

- src/components/organisms/RecentProjectsPane/RecentProjectsPane.tsx
This PR...
- adds styling to the scrollbar from Recent Projects pane
-
-
-
> fix: recent projects scrollbar style

- src/components/organisms/PluginManagerPane/PluginManagerPane.styled.tsx
- src/components/organisms/PluginManagerPane/PluginManagerPane.tsx
- src/components/organisms/TemplateManagerPane/TemplateManagerPane.styled.tsx
- src/components/organisms/TemplateManagerPane/TemplateManagerPane.tsx
This PR adds search bar for templates and plugins panes.
> feat: search bar for templates and plugins

- src/components/organisms/TemplateModal/TemplateModal.tsx
- src/redux/services/templates.ts
> fix template loading state on error and improve message

- package.json
- resources/form-schemas/networkpolicy-schema.json
- resources/form-schemas/networkpolicy-ui-schema.json
- src/scripts/generate-schema.ts
- src/scripts/index.ts
- NetworkPolicy form schema and a script to generate form schemas for other resources
- NetworkPolicy form schema
- Open a network policy file and in the editor you should see a tab where you can edit network policy items in a form
- https://user-images.githubusercontent.com/5509112/150130162-5543f723-1d4e-4236-b895-dd08073f3dfe.mov
> network policy form editor & script for other resources

- src/components/organisms/TemplateModal/TemplateModal.tsx
> fix: remove intro page from formData array

- src/redux/services/templates.ts
> fix: propagation of namespace in generated manifests

- src/components/organisms/TemplateManagerPane/TemplateManagerPane.styled.tsx
> fix: have auto rows with max content for templates

- src/redux/services/projectConfig.ts
- src/redux/thunks/loadKubeConfig.ts
> chore: add error logging

- src/components/organisms/MessageBox/MessageBox.tsx
- src/components/organisms/NotificationsDrawer/NotificationsDrawer.tsx
- src/components/organisms/PageHeader/PageHeader.tsx
- src/redux/reducers/main.ts
This PR...
- added badge with unseen notifications count
- set error alerts to disappear after 2 seconds
-
-
> feat: unseen notifications badge

- src/components/molecules/QuickActionPreview/styled.tsx
- src/components/molecules/SectionRenderer/SectionHeader.tsx
- src/components/molecules/SectionRenderer/styled.tsx
> fix section header padding and quick preview padding

- src/components/organisms/PageHeader/ClusterSelection.styled.tsx
- src/components/organisms/PageHeader/ClusterSelection.tsx
- src/components/organisms/PageHeader/PageHeader.tsx
- src/components/organisms/PageHeader/ProjectSelection.styled.tsx
- src/components/organisms/PageHeader/ProjectSelection.tsx
- src/components/organisms/PageHeader/Styled.tsx
- Grey 7 for `No cluster configured` text
- Remove hide action
- Create separate styled files for styled components
> refactor: cluster selector

- src/components/organisms/PageHeader/PageHeader.tsx
> fix: correct import typo

- src/components/organisms/TemplateManagerPane/TemplateInformation.tsx
- src/components/organisms/TemplateManagerPane/TemplateManagerPane.tsx
> fix: disabled templates in preview mode

- src/components/organisms/TemplateManagerPane/TemplateInformation.styled.tsx
- src/components/organisms/TemplateManagerPane/TemplateInformation.tsx
- src/components/organisms/TemplateManagerPane/TemplateManagerPane.styled.tsx
> refactor: improve TemplateInformation UI

- electron/templateService.ts
- src/components/organisms/TemplateModal/TemplateModal.tsx
- src/models/template.ts
> refactor: make template repository optional

- src/components/organisms/PaneManager/PaneManager.tsx
- src/components/organisms/TemplateManagerPane/TemplateManagerPane.styled.tsx
- src/components/organisms/TemplateManagerPane/TemplateManagerPane.tsx
> chore: add padding to skeletons

- src/components/molecules/TemplateFormRenderer/TemplateFormRenderer.tsx
- src/components/organisms/TemplateModal/TemplateModal.tsx
- src/components/organisms/TemplateModal/styled.tsx
This PR...
- moved template title to the modal title
- changed style of form title/description
- console error
-
> Template Modal improvements

- src/components/organisms/SettingsDrawer/Settings.tsx
- src/components/organisms/SettingsDrawer/SettingsDrawer.tsx
- src/redux/reducers/appConfig.ts
This PR...
- Add ability to change project name
-
-
-
> feat: add ability to change project name

- src/navsections/K8sResourceSectionBlueprint/ResourceKindSectionNameSuffix.tsx
> fix: section quick create button color

- src/components/organisms/PaneManager/PaneManager.tsx
This PR...
- the blue dot/badge should be hidden after we click on the kustomization / helm charts icons
- it should appear again when changing the folder, if there are any kustomizations or helm charts in that folder
-
-
-
> fix: hide left menu icons badges after pane opens

- src/components/organisms/SettingsDrawer/Settings.tsx
This PR...
-
- Handles form value correctly on project change  
-
-
> chore: set correct value change on project change

- src/components/organisms/PaneManager/PaneManager.tsx
- src/constants/tooltips.ts
> refactor: improve left menu icons tooltips

- src/components/organisms/PageHeader/ClusterSelection.styled.tsx
- src/components/organisms/PageHeader/ClusterSelection.tsx
- src/components/organisms/PageHeader/ProjectSelection.styled.tsx
- src/components/organisms/PageHeader/ProjectSelection.tsx
- Adds ellipsis when the cluster context name is too long
> fix: ellipsis for cluster context name

- src/components/atoms/MonoPaneTitle/MonoPaneTitle.tsx
- src/components/organisms/NavigatorPane/NavigatorPane.styled.tsx
- src/components/organisms/NavigatorPane/NavigatorPane.tsx
- src/components/organisms/NavigatorPane/WarningAndErrorsDisplay.styled.tsx
- src/components/organisms/NavigatorPane/WarningsAndErrorsDisplay.tsx
- Change resource kind styling
- Add resource namespace ( if exists )
- New sorting of the resources
> refactor: warnings/errors redesign

- src/redux/services/schema.ts
> fix: fixed retreival of schemas for dynamically loaded kindhandlers

- src/components/molecules/ResourceRefsIconPopover/RefLink.styled.tsx
- src/components/molecules/ResourceRefsIconPopover/RefLink.tsx
- Styling for refs popover links
> refactor: new styling for refs popover links

- docs/overview.md
- src/constants/hotkeys.ts
- Add CTRL/CMD P hotkey for quick search
- Update toggle settings hotkey to CTRL/CMD , (Comma)
- Use the hotkeys from above
> refactor: change settings/quick search hotkeys

- src/components/organisms/FileTreePane/FileTreePane.tsx
- src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenu.tsx
> fix: remove gap between context menu icon and dropdown

- src/components/organisms/PaneManager/MenuButton.tsx
- Add different color for toolbar buttons when hovering
> fix: different color on hover for toolbar buttons

- src/components/molecules/Monaco/codeIntel.ts
- src/redux/services/resourceRefs.ts
> feat: added support for marking incoming name refs in editor

- src/redux/services/resource.ts
> fix: ensure namespace is parsed correctly when reparsing

- src/components/organisms/PaneManager/PaneManager.tsx
- src/redux/reducers/appConfig.ts
This PR...
-
- Active project delete issue
-
-
> fix: deleting active project issue

- src/components/organisms/ActionsPane/ActionsPane.tsx
> fix: update kustomization check for Metadata Form editor

- src/utils/resources.ts
> fix: check pod template labels when filtering on label

- docs/plugins.md
- docs/templates.md
- mkdocs.yml
> docs: first draft for templates/plugins docs

- src/components/organisms/ActionsPane/ActionsPane.tsx
> fix: disable deploy/diff for unknown resources

- src/components/molecules/SectionRenderer/SectionHeader.tsx
> fix: remove expand/collapse icons, move suffix to the right

- src/components/organisms/SettingsDrawer/SettingsDrawer.tsx
- src/components/organisms/SettingsDrawer/Styles.tsx
This PR...
-
- Scrollbar style for settings pane
-
-
> fix: add scrollbar style to settings pane

- src/components/organisms/PageHeader/HelpMenu.tsx
- src/components/organisms/PageHeader/PageHeader.tsx
- src/components/organisms/PageHeader/styled.tsx
This PR...
- centered the icons vertically
- increased space between them by 4 px
- increased font size by 2 px
-
-
> fix: center icons in top right corner

- src/components/molecules/SaveResourcesToFileFolderModal/SaveResourcesToFileFolderModal.tsx
- src/components/organisms/NewResourceWizard/NewResourceWizard.tsx
> fix: filter unsupported or excluded file names from append to file

- .github/workflows/monokle-publish-updater.yml
- .github/workflows/monokle-publish.yml
This PR...
-
- Fixes release pipeline
-
-
> fix: pipeline for release

- src/components/molecules/SaveResourcesToFileFolderModal/SaveResourcesToFileFolderModal.tsx
This PR...
- save project files
- fix: #1188 
- save a file
- https://user-images.githubusercontent.com/5509112/151299033-5f5b91fc-75e3-41b6-a602-0165ca432112.mov
> fix: save project file

- src/components/molecules/Monaco/Monaco.tsx
- src/components/molecules/ResourceDiff/ResourceDiff.tsx
- src/hooks/useResourceYamlSchema.ts
This PR...
- fixes code intel and schema for selected files that contain only one resource
-
-
> fix: code editor intelligence for selected path

- src/components/organisms/PaneManager/PaneManager.tsx
- src/components/organisms/PaneManager/Styled.tsx
- src/components/organisms/RecentProjectsPane/RecentProjectsPane.tsx
- src/components/organisms/RecentProjectsPane/Styled.tsx
This PR...
-
- Recent project; instead of clicking title, click on the whole item
-
-
> fix: style Recent Project improvements & clicn on whole item

- electron/src/initKubeconfig.ts
This PR...
- removes unused function
-
-
-
> chore: remove unused function

- docs/templates.md
> docs: added some more links and a subsection for our custom widgets

- src/App.tsx
This PR...
- resolve relative path before search for the project 
- cmd: `monokle .` open current path project in monokle 
-
-
> fix: resolve relative path

- package.json
> feat: updated to electron 16.0.8

- src/components/molecules/FormEditor/FormEditor.tsx
- src/components/organisms/ActionsPane/ActionsPane.tsx
This PR...
- added an `isActive` flag to the FormEditor to only update active forms 
- form editor modifies resources without it been opened #1218 
-
-
> fix: update active forms

- src/components/organisms/LazyDrawer/LazyDrawer.tsx
- src/components/organisms/LazyDrawer/styled.tsx
- Add styling for the drawers scrollbar
> fix: drawer vertical scrollbar styling

- src/components/organisms/TemplateModal/TemplateModal.tsx
This PR...
-
- indexing off by one for helm chart templates
-
-
> fix: helm chart templates form data

- src/kindhandlers/ClusterRoleBinding.handler.ts
- src/kindhandlers/RoleBinding.handler.ts
> fix: correct namespace validation for rolebinding subject refs

- src/components/molecules/CheckedResourcesActionsMenu/CheckedResourcesActionsMenu.tsx
- src/components/molecules/ModalConfirmWithNamespaceSelect/ModalConfirmWithNamespaceSelect.tsx
- src/components/molecules/ResourceDiff/ResourceDiff.tsx
- src/components/organisms/ActionsPane/ActionsPane.tsx
- src/components/organisms/ClusterDiffModal/ClusterDiffModal.tsx
- src/components/organisms/ClusterResourceDiffModal/ClusterResourceDiffModal.tsx
- src/components/organisms/CreateProjectModal/CreateProjectModal.tsx
- src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
- src/components/organisms/LocalResourceDiffModal/LocalResourceDiffModal.tsx
- src/navsections/ClusterDiffSectionBlueprint/ResourceMatchNameDisplay.tsx
- src/redux/services/applyMultipleResources.ts
- src/redux/thunks/applyCheckedResources.ts
- src/redux/thunks/applyResource.ts
- src/redux/thunks/applySelectedResourceMatches.ts
- src/redux/thunks/applyYaml.ts
- src/redux/thunks/utils.ts
- Delete the newly created namespace if the deploy fails
> fix: create namespace only if deploy is successful

- mkdocs.yml
> add testing.md to mk docs

- src/components/molecules/SectionRenderer/styled.tsx
- src/constants/constants.ts
- src/redux/services/fileEntry.test.ts
- src/redux/services/fileEntry.ts
- src/redux/services/helm.ts
This PR...
-
- https://github.com/kubeshop/monokle/issues/1329
-
-
> fix: adding/removing Chart.yaml and values files

- src/redux/services/fileEntry.ts
- src/redux/services/resource.ts
> fix: reprocess kustomizations on addPath

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 1.5.1

- electron/commands.ts
seems to be needed after latest node update
-
-
-
-
> fix: added missing error any type

- package.json
> fix: updated to electron 17.0.1

- src/redux/reducers/main.ts
- src/redux/services/fileEntry.ts
- src/redux/services/fileMonitor.ts
- src/redux/services/helm.ts
- src/redux/thunks/setRootFolder.ts
and processing updated files
This PR...
-
- #1361 
-
-
> fix: use projectConfig instead of appConfig when parsing folder 

- src/components/organisms/ActionsPane/ActionsPane.tsx
This PR...
-
- #1363 #1362 
-
-
> fix: enabled form editors for selected file and deploy for kustomizations

- src/components/molecules/FormEditor/FormWidgets/NamespaceSelection.tsx
- src/redux/services/resource.ts
> fix: added namespaces from currently selected cluster to list of selectable namespaces

- src/components/molecules/SectionRenderer/SectionHeader.tsx
- src/components/molecules/SectionRenderer/styled.tsx
- src/components/molecules/SectionRenderer/useSectionCustomization.ts
- src/models/navigator.ts
- src/navsections/HelmChartSectionBlueprint/CollapseSectionPrefix.tsx
- src/navsections/HelmChartSectionBlueprint/FileItemPrefix.tsx
- src/navsections/HelmChartSectionBlueprint/HelmChartSectionBlueprint.ts
- src/navsections/HelmChartSectionBlueprint/RootHelmChartsSectionBlueprint.ts
> refactor: helm charts sections styling

- docs/overview.md
- docs/testing.md
- mkdocs.yml
Fix mkdocs.yml error and 2 broken links
This PR...
-
-
-
-
> Fix mkdocs.yml error

- src/components/molecules/TemplateFormRenderer/TemplateFormRenderer.tsx
> fix: template schema parsing error feedback

- electron/main.ts
This PR...
#1265 
- Project name appears after "Monokle" and before file path.
-
-
-
> project name added to window title

- electron/main.ts
- src/App.tsx
- src/redux/reducers/appConfig.ts
- src/utils/global-electron-store.ts
This PR...
- 
- #1159
- follow steps from #1159
- https://user-images.githubusercontent.com/5509112/156415218-a4eed653-14ab-4dff-9d42-d62b41b22f66.mov
> propagate project name changes across windows

- electron/main.ts
- electron/utils.ts
- src/components/organisms/CreateProjectModal/CreateProjectModal.tsx
- src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
- src/components/organisms/TemplateModal/TemplateModal.tsx
- src/redux/thunks/previewCluster.ts
- src/redux/thunks/previewHelmValuesFile.ts
- src/redux/thunks/previewKustomization.ts
- src/redux/thunks/saveUnsavedResources.ts
- src/redux/thunks/setRootFolder.ts
- src/utils/shell.ts
- src/utils/telemetry.ts
This PR...
- add event names into constant
-
-
-
> chore: Telemetry reviews fixes

- src/components/molecules/ModalConfirmWithNamespaceSelect/ModalConfirmWithNamespaceSelect.tsx
- src/kindhandlers/ClusterRole.handler.ts
- src/kindhandlers/ClusterRoleBinding.handler.ts
- src/kindhandlers/ConfigMap.handler.ts
- src/kindhandlers/CronJob.handler.ts
- src/kindhandlers/CustomResourceDefinition.handler.ts
- src/kindhandlers/DaemonSet.handler.ts
- src/kindhandlers/Deployment.handler.ts
- src/kindhandlers/Endpoints.handler.ts
- src/kindhandlers/Ingress.handler.ts
- src/kindhandlers/Job.handler.ts
- src/kindhandlers/Namespace.handler.ts
- src/kindhandlers/NetworkPolicy.handler.ts
- src/kindhandlers/PersistentVolume.handler.ts
- src/kindhandlers/PersistentVolumeClaim.handler.ts
- src/kindhandlers/Pod.handler.ts
- src/kindhandlers/ReplicaSet.handler.ts
- src/kindhandlers/ReplicationController.handler.ts
- src/kindhandlers/Role.handler.ts
- src/kindhandlers/RoleBinding.handler.ts
- src/kindhandlers/Secret.handler.ts
- src/kindhandlers/Service.handler.ts
- src/kindhandlers/ServiceAccount.handler.ts
- src/kindhandlers/StatefulSet.handler.ts
- src/kindhandlers/VolumeAttachment.handler.ts
- src/kindhandlers/common/customObjectKindHandler.ts
- src/models/resourcekindhandler.ts
and adapted Deploy modal accordingly
This PR...
-
-
-
-
> fix: added isNamespaced to ResourceKindHandler 

- src/utils/global-electron-store.ts
> fix: edge case when new project is created

- package-lock.json
- package.json
This PR...
- updates electron-unhandled version to latest
-
-
-
> chore: update electron-unhandled version

- src/components/molecules/FilePatternList/FilePatternList.tsx
- src/components/organisms/FileTreePane/FileTreePane.tsx
- src/components/organisms/SettingsManager/Settings.tsx
- src/components/organisms/SettingsManager/SettingsManager.tsx
- src/models/appconfig.ts
- src/redux/initialState.ts
- src/redux/reducers/appConfig.ts
- src/redux/reducers/main.ts
- src/redux/thunks/setRootFolder.ts
-
- #1287
- Go to project settings
- add/edit/delete an option to include/ignore files
- after each change the apply changes should be visible
- https://user-images.githubusercontent.com/5509112/156014901-b5f56c87-4d62-41f6-be11-a458d9ae75d1.mov
-
> #1287 Apply Changes not shown

- src/components/organisms/ActionsPane/ActionsPane.tsx
- src/redux/thunks/applyMultipleResources.ts
- src/redux/thunks/previewHelmValuesFile.ts
> fix: fixed compilation error and lint warnings

- docs/telemetry.md
> Privacy policy link

- src/components/organisms/PageHeader/ClusterSelectionTable.tsx
- src/index.css
- src/redux/thunks/loadKubeConfig.ts
- src/utils/kubeclient.ts
> fix: display error when cluster access cannot be checked

- electron/utils.ts
- on some macs not all paths are set correctly when running monokle as an application
-
-
-
> Fix bin $PATH not set correctly

- src/components/organisms/PageHeader/ClusterSelectionTable.tsx
- src/redux/reducers/appConfig.ts
- src/redux/thunks/loadKubeConfig.ts
- src/utils/electronStore.ts
- src/utils/kubeclient.ts
> fix: remove namespaces and don't add them back automatically

- electron/utils.ts
> fix: checking missing dependencies

- README.md
> Update link to new release blog post

- src/components/organisms/LocalResourceDiffModal/LocalResourceDiffModal.tsx
- src/redux/services/getClusterObjects.ts
- src/redux/thunks/applyFile.ts
- src/redux/thunks/applyMultipleResources.ts
- src/redux/thunks/applyResource.ts
- src/redux/thunks/applyYaml.ts
- src/redux/thunks/loadClusterDiff.ts
> fix: cluster compare and resource diff when no namespaces is selected

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 1.6.1

- src/redux/reducers/main.ts
> fix: thunks that were mutating state directly

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 1.6.2

- .github/CODEOWNERS
- package-lock.json
> chore: update codeowners

- craco.config.js
> fix: provide output path on craco

- electron/commands.ts
- electron/main.ts
- package-lock.json
- package.json
This PR...
-
- fix PATH env variable
-
-
> fix: PATH env variable

- package-lock.json
- package.json
> fix: downgrade antd version

- electron/app/createWindow.ts
> fix: electron reload path

- electron/app/createWindow.ts
> fix: relative paths in createWindow

- resources/kindhandlers/handlers/bitnami.com/SealedSecret.json
> fix: removed enum for secret type

- src/components/molecules/ModalConfirm/ModalConfirm.tsx
- src/components/molecules/ModalConfirm/index.ts
- src/components/molecules/ModalConfirm/styled.ts
- src/components/molecules/index.ts
- src/components/organisms/AboutModal/AboutModal.tsx
- src/components/organisms/LocalResourceDiffModal/LocalResourceDiffModal.tsx
- src/constants/makeApplyText.ts
- src/utils/getDependencyVersion.ts
> feat: confirm cluster local modal

- src/redux/reducers/main.ts
This PR...
-
- https://github.com/kubeshop/monokle/issues/1546
-
-
> fix: remove existing charts on project switch

- src/redux/services/schema.ts
This PR...
-
- https://github.com/kubeshop/monokle/issues/1541
-
-
> fix: values file schema remove defaults

- src/App.tsx
- src/components/organisms/SettingsManager/SettingsManager.tsx
- src/components/organisms/SettingsManager/styled.tsx
- src/constants/tooltips.ts
> refactor: telemetry info & links

- src/components/molecules/FormEditor/FormWidgets/SecretKindResourceForm.tsx
This PR...
-
- Form editor
-
-
> fix: set initial load parameter to disable resource update on first load

- src/App.tsx
> fix: telemetry notification showing only once

- package-lock.json
- package.json
- src/utils/telemetry.ts
> fix track events on main process and update Electron to 17.4.0

- src/redux/initialState.ts
> fix: initial state of ui pane configuration

- src/components/organisms/PaneManager/PaneManagerSplitView.styled.tsx
> chore: add min width to split pane

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 1.6.3

- .github/workflows/monokle-publish-downloads.yml
> chore: windows publish name

- .github/workflows/monokle-ui-tests.yml
- src/components/organisms/ActionsPane/ActionsPane.tsx
- tests/base.test.ts
- tests/git.test.ts
- tests/models/navigatorPane.ts
- tests/project.test.ts
> fixing tests

- src/components/molecules/PreviewConfigurationDetails/PreviewConfigurationDetails.tsx
- src/redux/thunks/runPreviewConfiguration.ts
This PR...
-
- https://github.com/kubeshop/monokle/issues/1603
-
-
> fix: building the helm command for preview configs

- src/redux/reducers/main.ts
- src/redux/thunks/previewConfiguration.ts
This PR...
-
- Closes https://github.com/kubeshop/monokle/issues/1607
-
-
> fix: selection after deleting preview config

- src/redux/reducers/main.ts
This PR...
-
- Closes https://github.com/kubeshop/monokle/issues/1609
-
-
> fix: ignore unsatisfied refs setting

- resources/kindhandlers/crds/bitnami/sealed-secret.yaml
- resources/kindhandlers/handlers/bitnami.com/SealedSecret.json
> fix: added status to SealedSecret validation schema

- src/components/organisms/PageHeader/ProjectSelection.tsx
This PR...
-
project selection dropdown
-
-
-
> fix: project selection dropdown opening

- src/components/molecules/WalkThrough/WalkThrough.tsx
- src/components/organisms/StartProjectPane/RecentProjectsPage.tsx
- src/components/organisms/StartProjectPane/StartProjectPage.tsx
- tests/models/mainWindow.ts
- tests/models/projectsDropdown.ts
> ui-tests: create project from welcome screen; from project dropdown

- src/components/organisms/RenameResourceModal/RenameResourceModal.tsx
> fix: Error handling when renaming resource

- resources/schemas/1.23.3.json
- src/components/organisms/NewResourceWizard/NewResourceWizard.tsx
This PR...
-
- fix: #1594 
-
-
> fix: add regex for resource names in file

- src/components/organisms/FileTreePane/TreeItem.tsx
> fix: fix delete resource

- src/constants/helmOptions.ts
> feat: add namespace helm option in preview config

- src/redux/reducers/appConfig.ts
> fix: handle deleteion of .monokle file

- src/components/organisms/PageHeader/ClusterSelectionTable.tsx
- src/redux/reducers/appConfig.ts
This PR...
-
- fix: #1618 
-
-
> fix: don't duplicate clusters when stopping minikube

- src/components/molecules/TitleBar/TitleBar.tsx
This PR...
- Fix editor buttons Layout issue
Previews:
Now:
> fix: Fix Editor buttons layout buttons

- package-lock.json
- package.json
> chore: update electron

- src/components/molecules/TitleBar/TitleBar.tsx
- src/components/organisms/FileTreePane/FileTreePane.tsx
- src/components/organisms/TemplateManagerPane/TemplateManagerPane.tsx
This PR...
Fix File Explorer & Template buttons layout issue
> fix: Navigator & Templates title buttons issue

- src/components/organisms/PageHeader/HelpMenu.tsx
> feat: add replay guide functionality

- package-lock.json
- src/components/molecules/NotificationMarkdown/TelemetryButtons.tsx
- src/redux/reducers/appConfig.ts
> feat: disable telemetry on telemetry notification

- src/components/organisms/CreateProjectModal/CreateProjectModal.tsx
This PR...
Fixed Console error - opening New project modal
> fix: console error when opening New Project from template modal

- src/components/organisms/KustomizePane/KustomizePane.tsx
- src/components/organisms/KustomizePane/styled.tsx
This PR amends a small mistake when no Kustomizations are found.
-
-
-
-
> fix: amend fix left menu layout height

- .github/workflows/monokle-build-nightly.yml
- .github/workflows/monokle-publish-downloads.yml
- .github/workflows/monokle-publish.yml
> chore: add MONOKLE_INSTALLS_URL env to workflow

- src/components/molecules/Monaco/codeIntel.ts
> fix: go directly to values file if there is just one link

- electron/app/utils.ts
> fix: deviceId value for telemetry

- src/components/organisms/StartProjectPane/Guide.tsx
> chore: add help links

- src/components/organisms/StartProjectPane/Guide.styled.tsx
- src/components/organisms/StartProjectPane/Guide.tsx
- Remove cursor pointer for Exclamation Icon on the Getting Started page **Guide**
> refactor: guide styling

- README.md
> chore: direct download links in readme + small updates

- .github/workflows/monokle-build-nightly.yml
- .github/workflows/monokle-publish-downloads.yml
- .github/workflows/monokle-publish.yml
- electron/app/amplitude.ts
- electron/app/createWindow.ts
- electron/app/index.ts
- electron/app/ipc/ipcListeners.ts
- electron/app/utils.ts
- package-lock.json
- package.json
> telemetry: setup Amplitude

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 1.7.1

- src/redux/services/validation.ts
and resources referred to by kustomizations - #1735 
This PR...
-
-
-
-
> fix: enabled OPA validation for preview resources 

- src/components/organisms/StartProjectPane/RecentProjectsPage.tsx
> fix: text typo

- src/components/organisms/StartProjectPane/RecentProjectsPage.styled.tsx
- src/components/organisms/StartProjectPane/StartProjectPage.styled.tsx
> fix: recent projects overflow

- electron/app/index.ts
- electron/app/utils.ts
> fix: nucleus telemetry

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 1.7.2

- src/components/organisms/FileTreePane/FileTreePane.tsx
- src/components/organisms/SettingsManager/Settings.tsx
- src/models/appconfig.ts
- src/redux/initialState.ts
- src/redux/services/projectConfig.ts
- src/utils/electronStore.ts
- Add the `Hide Unsupported files` settings
> feat: add hide unsupported files setting

- package-lock.json
- src/components/organisms/UpdateNotice/styled.tsx
- Add z-index to `UpdateNoticeContainer` so the slider border is not shown over it
> fix: add update notice container z-index

- src/utils/defineHotkey.ts
> fix: fix shortcuts for windows

- CHANGELOG.md
- package-lock.json
- package.json
This PR releases the next version of Monokle.
> chore(release): 1.7.3

- docs/hotkeys.md
- electron/app/openApplication.ts
- src/App.tsx
- src/components/molecules/Monaco/useEditorKeybindings.ts
- src/components/organisms/PageHeader/ClusterSelection.tsx
- src/constants/hotkeys.ts
- src/navsections/HelmChartSectionBlueprint/HelmChartQuickAction.tsx
- src/navsections/KustomizationSectionBlueprint/KustomizationQuickAction.tsx
- src/utils/restartEditorPreview.ts
> feat: restart preview shortcut for Monaco editor

- package-lock.json
- src/components/molecules/Monaco/CodeIntel/k8sResource.ts
> fix: add applyErrorIntel back

- src/components/molecules/ChangeFiltersConfirmModal/ChangeFiltersConfirmModal.tsx
- src/components/molecules/Monaco/symbolProcessing.ts
- src/components/molecules/ResourceFilter/ResourceFilter.tsx
- src/components/organisms/QuickSearchActions/QuickSearchActions.tsx
- src/models/appstate.ts
- src/redux/reducers/main.ts
- src/utils/resources.ts
- search by multiple resource ids
- fix: #1768 
-
- <img width="451" alt="Screenshot 2022-05-17 at 13 40 11" src="https://user-images.githubusercontent.com/5509112/168793258-12804819-e23d-4928-8a20-5a2eec6cefbd.png">
> feat: search by multiple resource kinds

- src/components/molecules/Monaco/useEditorKeybindings.ts
> fix: enable resource search when focus in editor

- src/components/organisms/PaneManager/MenuButton/MenuButton.tsx
> fix: highlight file explorer for helm value file

- src/components/organisms/PageHeader/ClusterSelectionTable.tsx
- src/redux/reducers/main.ts
- src/redux/services/helm.ts
- src/redux/services/preview.ts
> fix: display same selected resource when reloading cluster

- src/components/organisms/ActionsPane/ActionsPane.styled.tsx
- src/components/organisms/ActionsPane/ActionsPane.tsx
- src/components/organisms/ActionsPane/ActionsPaneHeader.styled.tsx
- src/components/organisms/ActionsPane/ActionsPaneHeader.tsx
- Add actions pane header component
> refactor: actions pane header

- package.json
Updated the Subject name with the Certificate's Subject
This PR...
-
-
-
-
> Updated Subject's Name with the Certificate Actual Subject

- src/components/molecules/Monaco/Monaco.tsx
- src/components/molecules/Monaco/useCodeIntel.ts
- src/models/appstate.ts
- src/navsections/DockerImagesSectionBlueprint/DockerImagesSectionBlueprint.ts
- src/redux/reducers/main.ts
- src/redux/thunks/selectionHistory.ts
- Add `ImagesMapType`
- Selecting an image from Monaco editor after replacing tag
> fix: monaco editor select image

- src/components/molecules/Monaco/CodeIntel/k8sResource/applyErrorIntel.ts
- src/components/molecules/Monaco/CodeIntel/k8sResource/applyPolicyIntel.ts
- src/components/molecules/Monaco/CodeIntel/k8sResource/applyRefIntel.ts
- src/components/molecules/Monaco/CodeIntel/k8sResource/index.ts
- Separate Monaco editor resource code intel
> refactor: separate resource code intel

- src/components/molecules/FilterPopover/FilterPopover.stories.tsx
- src/components/molecules/WalkThrough/WalkThrough.tsx
- src/components/organisms/KeyboardShortcuts/KeyboardShortcuts.tsx
- src/kindhandlers/common/customMatchers.ts
- src/navsections/KustomizationSectionBlueprint/KustomizationContextMenuWrapper.tsx
- src/redux/services/fileEntry.test.ts
> fix: fix warnings

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 1.7.4

- src/components/organisms/CompareModal/CompareActionBar.tsx
- src/components/organisms/CompareModal/CompareModal.tsx
- src/components/organisms/CompareModal/CompareModalComparing.tsx
- src/components/organisms/CompareModal/ComparisonInspection.tsx
- src/components/organisms/CompareModal/ComparisonList.styled.tsx
- src/components/organisms/CompareModal/ComparisonList.tsx
- src/components/organisms/CompareModal/DiffActionBar.tsx
- src/redux/reducers/compare.ts
- src/redux/services/compare/compareResources.ts
- src/redux/services/compare/transferResource.ts
- src/redux/thunks/utils.ts
This PR adds default namespace override and improved inspection.
> Compare everything: namespace override and improved inspection

- src/components/molecules/FilePatternList/FilePatternList.tsx
- src/components/molecules/NotificationMarkdown/NotificationModalTitle.tsx
- src/components/organisms/CompareModal/ResourceSetSelector/ResourceSetSelector.tsx
- src/components/organisms/FileTreePane/FileTreePane.tsx
- src/components/organisms/NavigatorPane/NavigatorPane.tsx
- src/components/organisms/NotificationsManager/Notification.tsx
- src/components/organisms/PluginManager/PluginManager.tsx
- src/components/organisms/SettingsManager/Settings.tsx
- src/components/organisms/SettingsManager/SettingsManager.tsx
- src/components/organisms/StartProjectPane/RecentProject.tsx
- src/components/organisms/TemplateManagerPane/TemplateManagerPane.tsx
- src/components/organisms/ValidationDrawer/OpenPolicyAgent/useOpenPolicyAgentTable.tsx
- src/navsections/HelmChartSectionBlueprint/PreviewConfigurationNameSuffix.tsx
- src/navsections/K8sResourceSectionBlueprint/ResourceKindSectionNameSuffix.tsx
- Add delay for all the tooltips
> fix: add tooltips delay

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 1.7.5

- src/components/organisms/PageHeader/ClusterSelection.styled.tsx
- src/components/organisms/PageHeader/ClusterSelection.tsx
- src/styles/Colors.ts
> feat: add different color themes for different preview modes

- .github/workflows/monokle-publish-updater.yml
> chore: remove workflow condition in favor of website re-runs

- src/components/organisms/PageHeader/ClusterSelection.styled.tsx
- src/components/organisms/PageHeader/ClusterSelection.tsx
> fix: preview loading button shrinking

- package-lock.json
- src/components/organisms/PageHeader/ClusterSelectionTable.tsx
- src/index.css
This PR...
https://github.com/kubeshop/monokle/issues/1880
> fix: hover on row - edit btn

- src/components/molecules/ResourceFilter/ResourceFilter.styled.tsx
- src/components/molecules/ResourceFilter/ResourceFilter.tsx
This PR...
https://github.com/kubeshop/monokle/issues/1872
1 - open resource filter
> fix: fix resource filter margin

- src/components/organisms/NavigatorPane/NavigatorPane.tsx
> fix: tooltip behaviour for disabled button

- src/components/organisms/PageHeader/ProjectSelection.tsx
> fix: enable switch projects while in Cluster or Preview mode

- package.json
> fix: update to electron 18.3.1

- src/redux/services/manifest-utils.test.ts
- src/redux/services/manifest-utils.ts
> fix: do not remove empty objects

- src/components/molecules/ImageDetails/ImageDetails.styled.tsx
- src/components/molecules/ImageDetails/ImageDetails.tsx
- Show not found text when the data could not be retrieved from docker hub
> feat: show not found message

- src/components/molecules/SaveResourcesToFileFolderModal/SaveResourcesToFileFolderModal.tsx
- src/redux/reducers/main.ts
> fix: newly created resource selected and highlighted

- package.json
> chore: add "dev" shorthand for "electron:dev"

- src/components/molecules/ImageDetails/ImageTags.tsx
- Add delay for image tag tooltip
> feat: image tag tooltip delay

- package-lock.json
- src/redux/thunks/loadKubeConfig.ts
> fix: stop access loading

- package.json
> chore: add publisherNames

- src/components/organisms/PageHeader/ClusterSelection.tsx
> chore: change cluster selection placement

- src/redux/services/helm.ts
> fix: loading helm chart folder

- src/components/organisms/PageHeader/ClusterSelection.tsx
> chore: top panel resize

- .github/workflows/monokle-build-nightly.yml
- .github/workflows/monokle-publish-downloads.yml
- .github/workflows/monokle-publish-updater.yml
- .github/workflows/monokle-publish.yml
- .github/workflows/monokle-ui-tests.yml
> chore: specify a version for AzureSignTool

- src/components/organisms/TemplateManagerPane/TemplateManagerPane.tsx
- Filter templates by author name
> feat: filter templates also by author name

- package-lock.json
- src/components/organisms/MessageBox/MessageBox.tsx
> chore: revert notification duration

- package-lock.json
- package.json
> feat: upgrade electron version to 19.0.4

- src/components/molecules/Monaco/CodeIntel/helmChartFile.ts
- Stringified Helm value preview
> fix: stringify helm value

- src/components/organisms/FileTreePane/FileTreePane.tsx
- src/components/organisms/FileTreePane/TreeItem.tsx
- src/components/organisms/FileTreePane/types.tsx
- src/utils/files.ts
- Adds possibility to duplicate file from File Explorer
Before duplication:
After duplication:
> feat: duplicate file

- src/components/molecules/FormEditor/FormEditor.styled.tsx
- src/components/molecules/FormEditor/FormEditor.tsx
- src/components/molecules/Monaco/Monaco.tsx
- src/components/molecules/Monaco/useDebouncedCodeSave.ts
- src/components/organisms/PageHeader/PageHeader.styled.tsx
- src/components/organisms/PageHeader/PageHeader.tsx
- src/models/appstate.ts
- src/redux/initialState.ts
- src/redux/reducers/main.ts
- src/redux/thunks/updateFileEntry.ts
- src/redux/thunks/updateResource.ts
- src/styles/Colors.ts
- Autosaving indicator for when editing a resource/file
- Autosaving indicator for the form editor
- Autosaving error with github report
- Edit a resource/file using Monaco Editor or Form Editor
> feat: autosave indicator

- electron/tsconfig.json
- package-lock.json
> chore: fix type issu for tar dependency

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 1.8.1

- resources/releaseNotes/1.8/1.8.json
- src/components/organisms/AboutModal/AboutModal.tsx
> feat: get about info from json file

- src/App.tsx
- src/components/organisms/MessageBox/MessageBox.tsx
- src/models/alert.ts
- Notify users if a middle release was installed
> feat: middle/patch release notification

- package-lock.json
- resources/schemas/1.24.2.json
- src/constants/constants.ts
- src/redux/services/validation.test.ts
> feat: add latest k8s versions

- package-lock.json
- package.json
- src/components/organisms/FileTreePane/FileTreePane.tsx
- src/components/organisms/FileTreePane/TreeItem.tsx
- src/components/organisms/FileTreePane/types.tsx
> fix: fix FileTree type issue

- src/components/molecules/Monaco/CodeIntel/helmChartFile.ts
- src/components/molecules/Monaco/CodeIntel/helmValues.ts
- src/components/molecules/Monaco/editorHelpers.ts
- Mention the path of the found file only once
> fix: mentioned the file path only once

- src/components/molecules/Monaco/CodeIntel/helmChartFile.ts
- Show only the message, without the possibility to link click
> fix: hover disposable instead of link

- src/components/molecules/Monaco/CodeIntel/helmChartFile.ts
- src/components/molecules/Monaco/CodeIntel/helmValues.ts
- src/components/molecules/Monaco/CodeIntel/types.ts
- src/components/molecules/Monaco/Monaco.tsx
- src/components/molecules/Monaco/useCodeIntel.ts
- src/components/molecules/Monaco/useDebouncedCodeSave.ts
- src/models/appstate.ts
- src/models/helm.ts
- src/navsections/HelmChartSectionBlueprint/HelmChartSectionBlueprint.ts
- src/redux/initialState.ts
- src/redux/reducers/main.ts
- src/redux/services/fileEntry.test.ts
- src/redux/services/fileEntry.ts
- src/redux/services/helm.ts
- src/redux/thunks/setRootFolder.ts
- src/redux/thunks/updateFileEntry.ts
-  Create Helm Templates map
- Reprocess helm template/value file after updating file entry
Before modifying the file:
After modifying the file:
> fix: reprocess helm value file/template

- electron/app/initKubeconfig.ts
- src/redux/services/kubeConfigMonitor.ts
- src/redux/services/projectConfig.ts
> chore: listen project kubeconfig path

- package-lock.json
- tests/git.test.ts
> chore: fix test type error + update package-lock

- src/redux/reducers/appConfig.ts
- src/redux/services/projectConfig.ts
> fix: do not flat arrays & compare arrays

- src/components/organisms/StartProjectPane/StartProjectPage.tsx
> fix: fix test errors

- src/components/organisms/FileTreePane/FileTreePane.tsx
- src/components/organisms/FileTreePane/TreeItem.tsx
- src/components/organisms/SearchPane/SearchPane.tsx
- src/hooks/fileTreeHooks/index.ts
- src/hooks/fileTreeHooks/useDelete.tsx
- src/hooks/fileTreeHooks/useDuplicate.tsx
- src/hooks/fileTreeHooks/useFileSelect.tsx
- src/hooks/fileTreeHooks/useFilterByFileOrFolder.tsx
- src/hooks/fileTreeHooks/usePreview.tsx
- src/hooks/fileTreeHooks/useRename.tsx
- src/kindhandlers/StorageClass.handler.ts
- src/navsections/HelmChartSectionBlueprint/HelmChartContextMenu.tsx
- src/navsections/HelmChartSectionBlueprint/HelmChartContextMenuWrapper.tsx
- src/navsections/HelmChartSectionBlueprint/HelmChartSectionBlueprint.ts
- src/navsections/KustomizationSectionBlueprint/KustomizationContextMenu.tsx
- src/redux/services/kustomize.ts
- src/utils/files.ts
- Add Context Menu and Wrapper for Kustomizations
- Add Context Menu and Wrapper for Helm Charts/Templates/Values files
- Disable unnecessary actions for Kustomization/Helm Chart context menu
- Deleting helm chart would break application
> feat: kustomize/helm context menu

- package-lock.json
- src/redux/services/fileEntry.ts
- src/redux/services/kustomize.ts
- src/redux/services/resource.ts
- Reprocess kustomization after duplicate
- Duplicate kustomization file and then check kustomize pane
> fix: reprocess kustomizations on duplicate

- src/components/molecules/Monaco/Monaco.tsx
- src/components/molecules/Monaco/useDebouncedCodeSave.ts
- src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenu.tsx
- src/redux/reducers/main.ts
This PR...
-
update file content for Monaco editor when deleting its resource
-
-
-
> fix: update file content for Monaco editor when deleting its resource

- README.md
> chore: remove old blog post from README

- docs/templates.md
- resources/form-schemas/deployment-ui-schema.json
- src/components/molecules/FormEditor/FormEditor.tsx
- src/components/molecules/FormEditor/FormWidgets/ImageSelection.tsx
- src/components/molecules/FormEditor/FormWidgets/NamespaceSelection.tsx
- src/components/molecules/FormEditor/FormWidgets/index.ts
- src/scripts/generate-schema.ts
- Image selection widget for templates and form editor
> feat: image selection ui widget

- src/components/organisms/PageHeader/HelpMenu.styled.tsx
- src/components/organisms/PageHeader/HelpMenu.tsx
- src/constants/tooltips.tsx
- Add feedback option to help menu
> feat: add feedback option to help menu

- src/navsections/ImagesSectionBlueprint/ImagesSectionNameSuffix.tsx
> refactor: resources links icon color for selected

- src/components/organisms/StartProjectPane/StartProjectPage.styled.tsx
- src/components/organisms/StartProjectPane/StartProjectPage.tsx
- src/styles/Device.ts
This PR...
added const styles for device media queries and fixed styling in StartProjectPage
-
-
-
> fix: added media queries and fixed styling in StartProjectPage

- resources/releaseNotes/1.9/1.9.json
- resources/releaseNotes/1.9/1.9.md
> chore: change Search to Find in release notes

- src/components/organisms/StartProjectPane/StartProjectPage.styled.tsx
- src/styles/Device.ts
This PR...
fixed styling by adding new media query stop to handle FirstPageSection
-
-
> fix: added new media query stop to fix Entry screen

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 1.9.0

- package-lock.json
- src/redux/services/kustomize.ts
> fix: add null checker for isKustomizationFile function

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 1.9.1

- src/redux/reducers/appConfig.ts
> feat: add/delete namespace from cluster selection

- package-lock.json
> feat: update package-lock

- docs/compare-sync.md
> fix: spacing in compare-sync.md

- src/constants/tooltips.tsx
- Change feedback link tooltip text
> feat: new feedback tooltip text

- src/components/molecules/FormEditor/FormWidgets/ImageSelection.tsx
> feat: add image selection placeholder

- src/navsections/K8sResourceSectionBlueprint/ResourceKindInformation.styled.tsx
- src/navsections/K8sResourceSectionBlueprint/ResourceKindInformation.tsx
> fix: warning

- src/components/molecules/ModalConfirmWithNamespaceSelect/ModalConfirmWithNamespaceSelect.tsx
- src/redux/reducers/main.ts
- Deploy Cluster Scoped resources
- Set alert notification error
> fix: deploy cluster scoped resource

- package-lock.json
- src/components/organisms/BottomPaneManager/BottomPaneManager.styled.tsx
- src/components/organisms/BottomPaneManager/BottomPaneManager.tsx
- src/components/organisms/TerminalPane/TerminalPane.styled.tsx
- src/components/organisms/TerminalPane/TerminalPane.tsx
- Redesign terminal 
https://www.figma.com/file/RnF7sRStr0DXJNMaVzlkwd/Monokle-Terminal-UI-(updated)?node-id=0%3A1
> refactor: terminal redesign

- src/components/organisms/BottomPaneManager/BottomPaneManager.styled.tsx
- src/components/organisms/BottomPaneManager/BottomPaneManager.tsx
- src/components/organisms/TerminalPane/TerminalOptions.styled.tsx
- src/components/organisms/TerminalPane/TerminalOptions.tsx
- src/components/organisms/TerminalPane/TerminalPane.tsx
- src/models/terminal.ts
- src/redux/initialState.ts
- src/redux/reducers/terminal.ts
- src/utils/electronStore.ts
- Add possibility to change terminal font size
> feat: terminal font size

- src/index.css
This PR...
- #2012 
- Check the draggable between the pane
> build: splitter style enhancement done as requested

- src/components/organisms/BottomPaneManager/BottomPaneManager.tsx
- src/components/organisms/TerminalPane/TerminalPane.tsx
- Confirmation modal for killing terminal
> feat: confirmation modal for killing terminal

- src/redux/reducers/appConfig.ts
> chore: fix kubeconfig monitor dispatch

- electron/app/ipc/ipcListeners.ts
- src/components/organisms/BottomPaneManager/BottomPaneManager.tsx
- src/components/organisms/TerminalPane/TerminalPane.tsx
- Kill terminal on `exit` command
> feat: terminal exit command

- electron/app/ipc/ipcListeners.ts
- package-lock.json
- package.json
- src/components/organisms/BottomPaneManager/BottomPaneManager.styled.tsx
- src/components/organisms/BottomPaneManager/BottomPaneManager.tsx
- src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
- src/components/organisms/TerminalPane/NewTerminalOptions.styled.tsx
- src/components/organisms/TerminalPane/NewTerminalOptions.tsx
- src/components/organisms/TerminalPane/TerminalOptions.styled.tsx
- src/components/organisms/TerminalPane/TerminalOptions.tsx
- src/components/organisms/TerminalPane/TerminalPane.tsx
- src/constants/terminal.ts
- src/models/terminal.ts
- src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenu.tsx
- src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenuWrapper.tsx
- src/redux/initialState.ts
- src/redux/reducers/terminal.ts
- src/redux/services/terminalShells.ts
- src/redux/store.ts
- src/utils/electronStore.ts
- Get list of possible shells for each OS ( `powershell.exe` and `cmd.exe` for Windows, `bash` and `zsh` for MacOS and `bash` for Linux - for now... )
- Set default shell ( that your OS is using - if we support it )
- Possibility to change default shell ( screenshot 1 )
- Possibility to create a different shell ( screenshot 2 )
1. ![image](https://user-images.githubusercontent.com/47887589/183395683-0db2c221-e75f-49e2-9f48-93d8c9a4a261.png)
2. ![image](https://user-images.githubusercontent.com/47887589/183395771-71944c3d-d5a6-4d8e-bc28-b2070f4d439d.png)
> feat: terminal multiple shells

- package-lock.json
- src/navsections/HelmChartSectionBlueprint/HelmChartSectionBlueprint.ts
> fix: select helm template

- package-lock.json
- package.json
- Update electron to newer version
> chore: update electron version

- src/components/organisms/PageHeader/CreateProject.styled.tsx
- src/components/organisms/PageHeader/CreateProject.tsx
- Close the new project popup when selection one of the options
> fix: close new project popup on option click

- src/redux/reducers/main.ts
- src/redux/services/unsavedResource.ts
- When create resources with the templates, select and highlight the first one
> fix: select and highlight first created resource from templates

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 1.10.0

- src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
- Terminal Icon `isSelected` prop
> refactor: terminal icon isSelected

- src/components/molecules/InputTags/InputTags.tsx
- Remove name filter tags on backspace
- Add tag onBlur and on pressing comma key
> feat: remove tag in name filter using backspace

- src/components/organisms/NavigatorPane/CompareButton.tsx
- src/components/organisms/NavigatorPane/NavigatorPane.tsx
- Compare & Sync button text when there is enough space
> refactor: compare & sync button text

- electron/app/createWindow.ts
- src/redux/reducers/ui.ts
- src/utils/electronStore.ts
- Save zoom factor in electron store
> fix: save zoom factor in electron store

- src/components/organisms/SearchPane/SearchPane.tsx
fix: remove highlights for matched chars/patterns when panel is closed or not active
This PR...
-
-
-
-
> fix: remove highlights for matched chars/patterns

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 1.10.1

- src/components/molecules/PreviewConfigurationDetails/PreviewConfigurationDetails.tsx
> fix: preview configuration details crashing

- src/components/organisms/SearchPane/CreateFilteredNode.tsx
- src/hooks/fileTreeHooks/useFileSelect.tsx
> fix: select file on match line click

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 1.10.2

- docs/cluster-integration.md
- docs/working-with-multiple-resources.md
- mkdocs.yml
Move Working with Multiple Resources to its own page and under the Working with Resources navigation section.
This PR...
-
-
-
-
> docs: Create Working with Multiple Resources Doc

- package-lock.json
- package.json
> fix: downgrade electron version

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 1.10.3

- electron/app/createWindow.ts
- electron/app/git/git.ts
- electron/app/git/ipc.ts
- src/components/atoms/CopyButton/CopyButton.tsx
- src/components/atoms/CopyButton/index.ts
- src/components/atoms/TableSelect/TableSelect.tsx
- src/components/atoms/TableSelect/index.ts
- src/components/atoms/index.ts
- src/components/molecules/BranchSelect/BranchCell.tsx
- src/components/molecules/BranchSelect/BranchSelect.tsx
- src/components/molecules/BranchSelect/BranchTable.styled.tsx
- src/components/molecules/BranchSelect/BranchTable.tsx
- src/components/molecules/BranchSelect/index.ts
- src/components/molecules/BranchSelect/useBranchTable.tsx
- src/components/organisms/PageHeader/PageHeader.tsx
- src/models/git.ts
- src/models/rootstate.ts
- src/redux/git/git.initialState.ts
- src/redux/git/git.slice.ts
- src/redux/git/index.ts
- src/redux/reducers/main.ts
- src/redux/store.ts
- src/redux/thunks/setRootFolder.ts
- src/styles/Colors.ts
> feat: branch selector + logic for branch checkout

- docs/index.md
> docs: Add v10 Blog Post

- package.json
This PR updates electron
-
-
-
-
> fix: updated to latest 19.x electron release

- src/kindhandlers/Secret.handler.ts
- src/kindhandlers/common/outgoingRefMappers.ts
- src/redux/services/resourceRefs.ts
> fix: allow "default" serviceAccountName references

- src/components/molecules/FormEditor/FormEditor.tsx
- src/components/molecules/Monaco/CodeIntel/k8sResource/applyLineDecorationIntel.ts
- src/components/molecules/Monaco/CodeIntel/k8sResource/index.ts
- src/components/molecules/Monaco/CodeIntel/types.ts
- src/components/molecules/Monaco/Monaco.tsx
- src/components/molecules/Monaco/editorConstants.ts
- src/components/molecules/Monaco/useCodeIntel.ts
- src/components/organisms/SearchPane/CreateFilteredNode.tsx
- src/components/organisms/SearchPane/styled.tsx
- src/index.css
- src/models/appstate.ts
- src/redux/initialState.ts
- src/redux/reducers/main.ts
- src/redux/services/manifest-utils.ts
- src/redux/thunks/updateResource.ts
This PR...
-
-
1) select resource
2) go to form tab
3) make changes to some properties
4) go to code editor tab
expected result:
you should see the last modified prop highlighted in code editor.
Highlight disappears once a resource's code is modified or another resource is selected 
-
> feat: highlight last changed line

- src/components/organisms/TerminalPane/TerminalOptions.tsx
- Change label for setting default shell
> feat: change default shell option label

- src/redux/services/schema.ts
This PR attempts to provide a safeguard for #2309 
-
-
-
-
> fix: added try/catch for all schema parsing

- src/components/molecules/Monaco/Monaco.tsx
This PR enables syntax-highlighting for any file/language supported by Monaco 
-
-
-
-
> fix: use Monaco logic to set syntax-highlighting for non-yaml files

- src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenu.tsx
- src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenuWrapper.tsx
> fix: getting resource content spec container name for opening terminal into pod

- src/components/organisms/FileTreePane/TreeItem.tsx
- src/navsections/KustomizationSectionBlueprint/KustomizationContextMenu.tsx
- src/navsections/KustomizationSectionBlueprint/KustomizationContextMenuWrapper.tsx
- Update menu items for Kustomization context menu wrapper
- Disable add resource action for kustomization files
$$ Screenshots
> fix: disable add resource action for kustomization files

- src/redux/reducers/main.ts
- Update images list when resource filter is changing
> fix: update images list when chaning resource filter

- electron/app/git/git.ts
- electron/app/git/ipc.ts
- src/components/molecules/BranchSelect/BranchCell.styled.tsx
- src/components/molecules/BranchSelect/BranchCell.tsx
- src/components/molecules/BranchSelect/BranchTable.styled.tsx
- src/components/molecules/BranchSelect/BranchTable.tsx
- src/components/molecules/BranchSelect/useBranchTable.tsx
- Possibility to delete a local branch that is not checked out
> feat: delete local branch

- electron/app/git/git.ts
- src/components/organisms/GitPane/GitPane.styled.tsx
- src/components/organisms/GitPane/GitPane.tsx
- src/redux/services/fileEntry.ts
- src/utils/git.ts
- Show added/removed files
- Do now populate fileMap `text` property for excluded files when they change
> feat: git show added/removed files

- package-lock.json
- src/components/organisms/ActionsPane/Scale/Scale.tsx
- src/components/organisms/GitPane/GitPane.tsx
- src/components/organisms/SettingsManager/Settings.tsx
- Show current branch name on commit button label
- ANTD related errors
> refactor: commit button label + fix antd

- src/redux/reducers/main.ts
- src/redux/services/gitFolderMonitor.ts
- src/redux/thunks/multiplePathsAdded.ts
- src/redux/thunks/multiplePathsChanged.ts
- Monitor files that are being added/removed if the project is a git repo
> feat: monitor added/removed files

- electron/app/git/git.ts
- electron/app/git/ipc.ts
- src/components/molecules/BranchSelect/BranchTable.styled.tsx
- src/components/molecules/BranchSelect/BranchTable.tsx
- src/components/molecules/BranchSelect/CreateBranchInput.styled.tsx
- src/components/molecules/BranchSelect/CreateBranchInput.tsx
- Possibility to create a new local branch ( after create it will be automatically checked out )
After clicking on the CTA:
> feat: create branch functionality + design

- src/redux/services/schema.ts
> fix: schema definitions crash

- src/navsections/KustomizationSectionBlueprint/KustomizationContextMenuWrapper.tsx
> fix: add sanity checks in KustomizationContextMenu

- src/components/molecules/BranchSelect/BranchCell.tsx
- src/components/organisms/GitOpsView/GitView.styled.tsx
- src/components/organisms/GitOpsView/GitView.tsx
- src/components/organisms/GitPane/BottomActions.styled.tsx
- src/components/organisms/GitPane/BottomActions.tsx
- src/components/organisms/GitPane/CommitModal.tsx
- src/components/organisms/GitPane/FileList.styled.tsx
- src/components/organisms/GitPane/FileList.tsx
- src/components/organisms/GitPane/GitPane.styled.tsx
- src/components/organisms/GitPane/GitPane.tsx
- src/components/organisms/PaneManager/PaneManagerLeftMenu.styled.tsx
- src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
- src/components/organisms/PaneManager/PaneManagerSplitView.tsx
- Commit button first
- Bigger action buttons bar
- Show badge with number of changed files in the left menu
- Auto-focus input in commit modal
- Show unstaged label when there are only staged files
- Popconfirm for deleting local branch
- Black background for diff editor 
- Highlight selected changed file + select file in file explorer ( if exists )
- Show action buttons at anytime
> feat: git improvements + fixes

- src/components/molecules/FormEditor/FormEditor.tsx
This PR...
-
update form ui view on changes
-
-
-
> fix: update form on data change
