src/App.tsx
src/AppContext.ts
src/components/molecules/NavigatorRowLabel/NavigatorRowLabel.tsx
src/components/molecules/ScrollIntoView/ScrollIntoView.tsx
src/components/organisms/FileTreePane/FileTreePane.tsx
src/components/organisms/NavigatorPane/NavigatorPane.tsx
src/constants/constants.ts

introduced AppContext to avoid prop drilling of the windowSize
This PR...
- scrolls selected resource into view if it's not visible, which allows us to click links in the navigator/editor and the newly selected resource will be scrolled into view
-

feat: scroll selected resource into view if not visible

---

src/App.tsx
src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
src/components/organisms/PaneManager/PaneManager.tsx
src/components/organisms/PaneManager/index.js
src/components/organisms/index.ts
src/models/ui.ts
src/redux/initialState.ts
src/redux/reducers/ui.ts

This PR...
- moved leftMenu and rightManu state to ui store
- simplified App.tsx by moving panes logic to new PaneManager component
-

refactor: app structure improvements

---

electron/main.ts
package-lock.json
package.json

This PR...
Will add `electron-logger` library to project. So in release mode, we will be able to see log messages of the application or We will be able to request log messages from end-users.
- Added related library to the project
- Assigned log functions to console functions. So developers can continue to use log functions as it is.
-

feat: Add electronlogger to the project

---

docs/overview.md
src/components/molecules/GraphView/GraphView.tsx
src/components/molecules/Monaco/Monaco.tsx
src/components/molecules/NavigatorHelmRow/NavigatorHelmRow.tsx
src/components/molecules/NavigatorRowLabel/NavigatorRowLabel.tsx
src/components/organisms/ActionsPane/ActionsPane.tsx
src/components/organisms/FileTreePane/FileTreePane.tsx
src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
src/components/organisms/NavigatorPane/components/KustomizationsSection.tsx
src/components/organisms/NavigatorPane/components/ResourcesSection.tsx
src/constants/hotkeys.ts
src/models/appstate.ts
src/redux/initialState.ts
src/redux/reducers/main.ts
src/redux/services/selectionHistory.ts
src/redux/thunks/selectionHistory.ts

This PR...
- implemented logic to allow user to navigate through the history of selections
- added left and right arrows to the Editor's title bar
- added both global and monaco hotkeys for navigation (ALT+ArrowLeft and ALT+ArrowRight)
-

Navigate through selection history

---

src/components/molecules/NavigatorRowLabel/NavigatorRowLabel.tsx
src/models/k8sresource.ts
src/redux/services/resource.ts
src/redux/services/resourceRefs.ts

This PR...
- saves target resource kind on ResourceRef
- displays the target resource kind on NavigatorRowLabel
-

feat: save and display target resource kind for unsatisfied refs

---

src/components/molecules/ValidationErrorsModal/ValidationErrorsModal.tsx
src/kindhandlers/ClusterRole.handler.ts
src/kindhandlers/ClusterRoleBinding.handler.ts
src/kindhandlers/ConfigMap.handler.ts
src/kindhandlers/CronJob.handler.ts
src/kindhandlers/CustomResourceDefinition.handler.ts
src/kindhandlers/DaemonSet.handler.ts
src/kindhandlers/Deployment.handler.ts
src/kindhandlers/Endpoint.handler.ts
src/kindhandlers/Ingress.handler.ts
src/kindhandlers/Job.handler.ts
src/kindhandlers/NetworkPolicy.handler.ts
src/kindhandlers/PersistentVolume.handler.ts
src/kindhandlers/PersistentVolumeClaim.handler.ts
src/kindhandlers/Pod.handler.ts
src/kindhandlers/ReplicaSet.handler.ts
src/kindhandlers/ReplicationController.handler.ts
src/kindhandlers/Role.handler.ts
src/kindhandlers/RoleBinding.handler.ts
src/kindhandlers/Secret.handler.ts
src/kindhandlers/Service.handler.ts
src/kindhandlers/ServiceAccount.handler.ts
src/kindhandlers/StatefulSet.handler.ts
src/models/resourcekindhandler.ts
src/redux/services/schema.ts
src/redux/services/unsavedResource.ts

This PR...
- add validationSchemaPrefix to all kind handlers
- use validationSchemaPrefix in getResourceSchema
- multiple errors where validation schemas couldn't be found for some resource kinds

feat: add validationSchemaPrefix to all kind handlers

---

src/constants/constants.ts
src/redux/services/resource.ts
src/redux/thunks/previewCluster.ts
src/redux/thunks/saveUnsavedResource.ts
src/redux/thunks/utils.ts

This PR...
-
- saving multi-document files on Windows was adding unnecessary yaml document delimiters, which caused the parsed content to be null

fix: yaml document delimiter line endings

---

src/components/molecules/Monaco/Monaco.tsx
src/components/organisms/FileTreePane/FileTreePane.tsx

This PR...
*
* Set and keep selection on file explorer
* Prevent selection flashing on first resource select on source editor

fix: Selection flashing on both source editor and file explorer

---

src/kindhandlers/Endpoints.handler.ts
src/kindhandlers/index.ts

This PR fixes Endpoints ResourceKindHandler to use correct name and prefix
-
-

fix: fixed Endpoints ResourceKindHandler to use correct name and prefix

---

src/components/molecules/NavigatorRowLabel/ActionsMenu.tsx
src/components/molecules/NavigatorRowLabel/NavigatorRowLabel.tsx
src/models/appstate.ts
src/redux/reducers/main.ts
src/redux/services/resource.ts
src/redux/thunks/saveUnsavedResource.ts

This PR...
- show ActionsMenu on all resources and disable Delete action instead
- save resource range for the unsaved resource and for existing one if needed
- delete file only if it has a single resource

Fix saving an unsaved resource and refactor resource delete

---

src/components/molecules/NavigatorRowLabel/NavigatorRowLabel.tsx
src/components/organisms/NewResourceWizard/NewResourceWizard.tsx

This PR...
- show only resources which have the selected kind in the NewResourceWizard for template selection and reset if kind changes
- hide actions menu for Kustomizations
-
-

show only resources which have the selected kind in the NewResourceWizard for templates

---

src/components/organisms/RenameResourceModal/RenameResourceModal.tsx
src/redux/reducers/main.ts
src/redux/services/renameResource.ts

This PR...
- option to prevent updating selection and highlights after a resource is updated
- get and set the default resource name when renaming
- resource selection after renaming a resource
-
-

rename resource improvements

---

electron/main.ts
src/components/atoms/FileExplorer/FileExplorer.tsx
src/hooks/useFileExplorer.tsx
src/utils/files.ts

This PR replaces the usage of the input file/folder dialogs for selecting folders/files with the electron-provided os file dialogs 
-
-
-
-

feat: use os file dialogs for selecting folders and files

---

package.json

This PR...
- Removed ignored path on package.json `@babel`
- Module not found error on application bootup
- Install and run the built application
-

fix: Include @babel path on production

---

src/components/molecules/Monaco/Monaco.tsx
src/components/molecules/Monaco/useMonacoUiState.ts
src/components/molecules/ResourceRefsIconPopover/RefsPopoverContent.tsx
src/components/molecules/ResourceRefsIconPopover/ResourceRefsIconPopover.tsx
src/models/ui.ts
src/redux/reducers/ui.ts

This PR...
- clicking on a link in the resource refs popover will now select the resource that contains the ref then scroll to and select the ref in the editor
-
-
-

feat: resource ref selection in Monaco editor

---

src/components/organisms/NavigatorPane/NavSectionRenderer/NavSectionItem/NavSectionItem.tsx
src/components/organisms/NavigatorPane/NavSectionRenderer/NavSectionItem/styled.tsx
src/components/organisms/NavigatorPane/NavSectionRenderer/NavSectionRenderer.tsx
src/components/organisms/NavigatorPane/NavSectionRenderer/styled.tsx
src/components/organisms/NavigatorPane/NavSectionRenderer/useNavSection.ts
src/models/navsection.ts
src/navsections/K8sResourceNavSection/K8sResourceNavSection.ts
src/navsections/K8sResourceNavSection/ResourceKindNavSection.ts

This PR...
- add logic to support showing all sections/subsections as empty before a folder is loaded (via new isInitialized handler)
- improve performance by avoiding entire re-renders of the section components
- spacing between section by properly finding the last visible section
-
-

refactor: navigator pane improvements

---

.gitignore
electron/main.ts
env.example.ts
package-lock.json
package.json

This PR...
- The way of handling environment variables
- NODE_ENV undefined issue
- Copy env.example.ts file as env.ts and set env as production and get the build.
-

fix: Add env.ts to handle environment variables

---

src/redux/reducers/appConfig.ts

This PR...
-
- Inherits initial new version check and prevents to modal show up at every boot up
-
-

fix: Prevent update not found meesage to appear on every boot up

---

electron/main.ts

This PR...
-
- Sets initial value on version check.
-
-

fix: Set initial value on new version check

---

electron/commands.ts
src/redux/thunks/previewHelmValuesFile.ts

This PR...
- instead of attempting to run kustomize/helm in the root folder of a helm chart or kustomization it will run commands in the default folder and pass the path to those folders as arguments. 
- #521 - run commands for files on network shares on Windows
- load manifests from a windows share and attempt to preview contained kustomizations or helm charts
-

fix: changed helm/kustomize commands to run in default folder

---

electron/menu.ts
src/components/molecules/Monaco/Monaco.tsx

This PR...
- Editor instance creation logic
- After selecting resource one after and doing undo replaces the content with the previous resource content
- Copy and paste entire resource content to other file, resource selection changes
-
-

fix: doing undo replaces the content

---

src/components/atoms/Icon/Icon.tsx
src/components/molecules/FilePatternList/FilePatternList.tsx
src/components/molecules/FilePatternList/FilePatternListItem.tsx
src/components/organisms/ClusterDiffModal/ClusterDiffModal.tsx
src/components/organisms/ClustersPane/ClustersPane.tsx
src/components/organisms/FileTreePane/FileTreePane.tsx
src/components/organisms/SettingsDrawer/SettingsDrawer.tsx

This PR...
- Disabled editing of kubeconfig and/or current context if the user is in cluster mode.
- Fixed bug when the user could input some text in the File Pattern input in the Settings Drawer if he opened the Settings Drawer, pressed on the Add File Pattern button, and closed the Settings Drawer.
- Fixed styling of Clusters Pane.

feat: disabled editing of kubeconfig and/or current context if the user is in cluster mode

---

src/components/molecules/SectionRenderer/SectionRenderer.tsx
src/components/molecules/SectionRenderer/styled.tsx
src/components/molecules/SectionRenderer/useSectionCustomization.ts
src/components/organisms/ClusterDiffModal/ClusterDiffModal.tsx
src/components/organisms/NavigatorPane/ClusterComparisonButton.tsx
src/constants/tooltips.ts
src/models/navigator.ts
src/navsections/K8sResourceSectionBlueprint/K8sResourceSectionBlueprint.ts
src/navsections/K8sResourceSectionBlueprint/K8sResourceSectionEmptyDisplay.tsx
src/navsections/sectionBlueprintMiddleware.ts
src/redux/thunks/loadClusterDiff.ts

This PR...
- add isEmpty method to the section builder
- allow sections to provide a React component to render when a section is empty
-
-

feat: logic to customize empty sections in navigator

---

src/components/molecules/Monaco/Monaco.tsx
src/components/molecules/Monaco/useMonacoUiState.ts

This PR...
- reset editor's undo history by creating a new TextModel when selected resource is changed
- remove the update of focused state because it causes re-renders and the editor behaves weirdly, we should find a better solution for that
-
-
-

fix: monaco undo history by resetting the modal + remove focused state

---

src/components/atoms/MonoPaneTitle/MonoPaneTitle.tsx
src/components/organisms/NavigatorPane/WarningsAndErrorsDisplay.tsx

This PR...
- Add white-space: nowrap for preventing next line issue on warn icons
-
-
-

fix: prevent going next line on narrow widths

---

src/components/molecules/FormEditor/FormEditor.tsx
src/components/molecules/Monaco/Monaco.tsx
src/redux/services/fileMonitor.ts

This PR...
- Listen to resource changes in Manoco editor
- Don't set orgFormData to undefined whenever selectedResource changes
- Change fileMonitor interval to 1 second
-
-
-

fix: Reflect changes made in Form editor

---

src/components/molecules/ClusterDiff/ClusterDiff.tsx
src/components/molecules/ResourceFilter/ResourceFilter.tsx
src/models/navigator.ts
src/navsections/ClusterDiffSectionBlueprint/ClusterDiffSectionBlueprint.ts
src/navsections/ClusterDiffSectionBlueprint/ClusterDiffSectionEmptyDisplay.tsx
src/navsections/K8sResourceSectionBlueprint/K8sResourceSectionBlueprint.ts
src/navsections/K8sResourceSectionBlueprint/K8sResourceSectionEmptyDisplay.tsx
src/navsections/K8sResourceSectionBlueprint/K8sResourceSectionNameSuffix.tsx
src/navsections/sectionBlueprintMiddleware.ts
src/redux/services/resource.ts
src/utils/resources.ts

This PR...
- changed preview output tag color in cluster preview
- logic to show empty sections that have an emptyDisplay set
- added "No resources match filters" message for both the K8s Section in Navigator and the Cluster Compare
- fixed ResourceFilter component state issues
- fixed resource filtering logic
- added back Resource Filter to the Cluster Compare
-
-
-

Navigator improvements, fixed resource filters

---

src/components/organisms/ActionsPane/ActionsPane.styled.tsx

- fixed behavior when the context-sensitive pop-up was cropped

fix: fixed behavior when context-sensitive pop-up was cropped

---

src/redux/reducers/main.ts
src/redux/services/resourceRefs.ts

fix: reprocess all resources for file updates

---

src/redux/thunks/previewCluster.ts
src/redux/thunks/utils.ts

This PR implements #641 
- retrieve resources from a cluster containing custom resources - they should show up at the bottom of the navigator under an "Unknown" section

fix: added retrieval of custom resource objects from cluster

---

src/components/molecules/ClusterDiff/ClusterDiff.tsx
src/components/organisms/ClusterDiffModal/ClusterDiffModal.tsx
src/navsections/ClusterDiffSectionBlueprint/ClusterDiffSectionNameDisplay.tsx

This PR...
- change header color while comparing a preview
- moved reload button next to cluster resources tag
-
-

Improved Cluster Compare UX

---

src/navsections/sectionBlueprintMiddleware.ts
src/redux/store.ts

This PR...
- collapse all redux-logger logs by default if they don't have any errors
- disable redux-logger in production
-
-
-

refactor: redux-logger configuration

---

src/components/molecules/SectionRenderer/ItemRenderer/ItemRenderer.tsx
src/components/molecules/SectionRenderer/ItemRenderer/styled.tsx

This PR...
- this increases the space that can be clicked to trigger the onClick event on an item in navigator sections
- before this, we could select resources only by clicking their text, now we can click on the blank space in the row as well
-
-
-

Increase items' onClick area in navigator

---

src/components/organisms/NewResourceWizard/NewResourceWizard.tsx
src/utils/shell.ts

- applied validation to the New Resource Wizard's name field
- ![image](https://user-images.githubusercontent.com/25991946/143192334-0653f1e6-7746-43ab-8d97-888f3a3325f3.png)
- ![image](https://user-images.githubusercontent.com/25991946/143192372-5c220459-f90e-4fd1-a092-e6f7c7fea2a4.png)

fix: applied validation to the New Resource Wizard's name field

---

src/redux/services/kustomize.ts

fix: create unsatisifed refs for invalid kustomization resources ref

---

electron/commands.ts
electron/main.ts
src/components/atoms/FileExplorer/FileExplorer.tsx
src/components/organisms/ActionsPane/ActionsPane.tsx
src/constants/tooltips.ts
src/hooks/useFileExplorer.tsx
src/redux/thunks/saveUnsavedResource.ts

This PR replaces the current open-dialogs when saving a resource with save dialogs instead...
-
- #780 
-
-

fix: updated resource save actions to use save dialog

---

src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenu.tsx

- fixed wrong styling of context menu in k8s resources tab
If we provide the overlay menu as another component e.g. ResourceActionsMenu, Ant Design does not recognize this component as a Menu and does not provide any Menu styles to it.

fix: fixed wrong styling of context menu in k8s resources tab

---

electron/commands.ts
src/components/molecules/Monaco/Monaco.tsx
src/components/molecules/Monaco/codeIntel.ts
src/components/molecules/Monaco/editorHelpers.ts
src/components/molecules/Monaco/useCodeIntel.ts
src/redux/reducers/main.ts

This PR adds hover actions to editor for extending the current resource filter - see #444 
-
-
-
-

fix: added hover links to add filters in source editor

---

src/components/molecules/Monaco/Monaco.tsx
src/models/appstate.ts
src/redux/initialState.ts
src/redux/reducers/main.ts
src/redux/services/fileEntry.ts

This PR...
-
- fix file selection and reload file content in editor when the selected file is changed outside of Monokle
- remove resource selection if the file containing it is a multi-document file and it was changed externally
-
-

fix: selections & editor content on file changes

---

src/components/atoms/KeyValueInput/KeyValueInput.tsx
src/components/molecules/ResourceFilter/ResourceFilter.tsx
src/components/organisms/NavigatorPane/NavigatorPane.tsx
src/models/ui.ts
src/redux/initialState.ts
src/redux/reducers/ui.ts

- Show resource filters as a panel instead of a popup

refactor: show resource filters as a panel

---

src/models/k8sresource.ts
src/redux/reducers/main.ts
src/redux/services/fileEntry.ts
src/redux/services/resource.ts
src/redux/services/resourceRefs.ts

A side-benefit of this is that we now have an isOptional flag on refs - which we could use in the ref popups (and anywhere else) to indicate that a ref is optional (goes for both satisfied and unsatisfied refs)
-
- #852 
-
-

fix: removed all referring refs when deleting a resource

---

src/components/organisms/SettingsDrawer/SettingsDrawer.tsx
src/navsections/K8sResourceSectionBlueprint/K8sResourceSectionEmptyDisplay.tsx

This PR adds a "Reset filters" link to the "No resources match the active filters" message (cause I'm lazy and don't want to have to open the filters panel to reset..)
-
-
-
-

feat: added action to reset filters when no resources match

---

src/components/molecules/ResourceRefsIconPopover/RefLink.tsx
src/components/molecules/SectionRenderer/SectionHeader.tsx
src/components/organisms/ActionsPane/ActionsPane.tsx
src/components/organisms/DiffModal/DiffModal.tsx
src/components/organisms/FileTreePane/FileTreePane.tsx
src/components/organisms/PageHeader/PageHeader.tsx
src/navsections/K8sResourceSectionBlueprint/ResourceKindSectionNameSuffix.tsx

- Disable create resource button on preview mode
- Show corresponding color for icon
- Hide checkboxes before the sections are initialized
- Fix console warnings

fix: Disable create resource button on preview mode + small fixes

---

src/components/molecules/CheckedResourcesActionsMenu/CheckedResourcesActionsMenu.tsx
src/components/molecules/ClusterDiff/ClusterDiff.tsx
src/components/molecules/SectionRenderer/SectionRenderer.tsx
src/components/organisms/HelmPane/HelmPane.tsx
src/components/organisms/KustomizePane/KustomizePane.tsx
src/components/organisms/NavigatorPane/NavigatorPane.tsx
src/redux/reducers/main.ts
src/redux/services/applyCheckedResourcesWithConfirm.tsx
src/redux/services/applyMultipleResources.ts
src/redux/thunks/applyCheckedResources.ts
src/redux/thunks/applySelectedResourceMatches.ts

- Show actions menu instead of the title bar ( with warnings, buttons etc. )
- Show the number of selected resources
- Deploy resources functionality with modal confirmation
- Delete modal confirmation (without logic to delete the resources)
- Minor styling updates
- Do not show `Delete` when in preview mode
- Do not show `Deploy` when in cluster mode

feat: Actions menu for checkable resources

---

src/components/molecules/ClusterDiff/ClusterDiff.tsx
src/components/organisms/HelmPane/HelmPane.tsx
src/components/organisms/KustomizePane/KustomizePane.tsx
src/components/organisms/NavigatorPane/NavigatorPane.tsx
src/models/navigator.ts
src/navsections/ClusterDiffSectionBlueprint/ClusterDiffSectionBlueprint.ts
src/navsections/HelmChartSectionBlueprint/HelmChartSectionBlueprint.ts
src/navsections/K8sResourceSectionBlueprint/K8sResourceSectionBlueprint.ts
src/navsections/K8sResourceSectionBlueprint/ResourceKindSectionBlueprint.ts
src/navsections/KustomizationSectionBlueprint/KustomizationSectionBlueprint.ts
src/navsections/KustomizePatchSectionBlueprint/KustomizePatchSectionBlueprint.ts
src/navsections/UnknownResourceSectionBlueprint/UnknownResourceSectionBlueprint.ts
src/navsections/sectionBlueprintMiddleware.ts

This PR...
- added `containerElementId` to all section blueprints in order to "observe" the height changes of those elements using ResizeObserver
- wrong compute of sectionInstanceRoots
-
-

fix: scroll into view logic of section blueprints

---

src/components/organisms/FileTreePane/FileTreePane.tsx

- Show the default folder icon for entities that are folders

refactor: Different icon for folders in file explorer

---

src/components/organisms/NewResourceWizard/NewResourceWizard.tsx
src/utils/hooks.ts

- Preselect namespace when adding a new resource from the resource filter namespace ( if it exists )
- Show `Add to File` path prefilled only for `File Explorer` -> `Add Resource`

feat: Preselect namespace when adding a new resource

---

src/components/molecules/ResourceRefsIconPopover/ResourceRefsIconPopover.tsx
src/components/molecules/SectionRenderer/ItemRenderer/styled.tsx
src/components/molecules/SectionRenderer/SectionHeader.tsx
src/components/molecules/SectionRenderer/styled.tsx
src/index.css
src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenu.tsx
src/navsections/K8sResourceSectionBlueprint/ResourceKindPrefix.tsx
src/navsections/K8sResourceSectionBlueprint/ResourceKindSectionBlueprint.ts

This PR...
- added namespace tag next to resources with Popover to apply filter to that namespace
- namespace tag is hidden if there is a filter on the namespace
- aligned sections and items (removed the indentation based on nesting levels)
-
-

feat: show namespace tag next to resources in navigator + styling changes

---

src/navsections/KustomizePatchSectionBlueprint/KustomizePatchSectionBlueprint.ts

This PR...
- let patches be enabled in preview mode
- don't apply resource filters to patches
- remove patches loading state while preview loads
-
-
-

fix: remove unnecessary logic from patch resources

---

src/components/organisms/ActionsPane/ActionsPane.tsx
src/components/organisms/FileTreePane/FileTreePane.tsx
src/components/organisms/NavigatorPane/NavigatorPane.tsx
src/components/organisms/PaneManager/PaneManager.tsx

This PR...
- this is a temporary fix for calculating the heights of panes while in preview mode
- we should refactor the PaneManager implementation so we can get the values dinamically
- either the footer or part of the header were hidden during preview mode
-
-

fix: height offset of panes in preview mode

---

docs/overview.md
src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
src/constants/hotkeys.ts

- Added `Ctrl/Cmd ALT R` hotkey for resetting the resource filters

feat: hotkey for resetting resource filters

---

src/components/molecules/ResourceFilter/ResourceFilter.tsx
src/components/organisms/FileTreePane/FileTreePane.tsx
src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
src/components/organisms/NewResourceWizard/NewResourceWizard.tsx
src/models/appstate.ts
src/redux/reducers/main.ts
src/utils/resources.ts

This PR implements the functionality to filter resources by file/folder.
- Add new filter `Contained in` in resource filters which filters resources by file/folder
- Add option to apply filtering on file/folder in `FileTreePane ContextMenu`

feat : filter resource by file/folder

---

src/components/organisms/FileTreePane/FileTreePane.tsx

- Disabled `Add resource` for **Excluded** and **Unsupported** files
- Disabled `Filter on this file/folder` for **Excluded** and **Unsupported** files
- Disabled `Remove from/Add to Files: Exclude` for **Unsupported** files
##

fix: disable actions for excluded/unsupported files

---

electron/menu.ts

This PR removes the `Zoom` action for non-macOS systems.

refactor: remove zoom action for non macos systems

---

src/components/organisms/ActionsPane/ActionsPane.tsx

This PR...
- Added a guard check if there is no kube context before open the DiffModal and show an alert 
- Crashing if there is no configured cluster 
- remove the kube config from ~/.kube/config or shutdown the cluster 
- open a project folder
- select a resource 
- diff against the cluster 
- should show cluster is not configured error popup message

fix: guard against no cluster configured

---

src/components/molecules/FormEditor/FormWidgets/SecretKindResourceForm.tsx

This PR...
- Prevent to convert `null` value to Base64
- Set Base64 Input value to null when it is toggled to `decode` state

fix: prevent to convert null value to Base64

---

src/components/molecules/SectionRenderer/ItemRenderer/ItemRenderer.tsx

- Checking/Unchecking a resource should not scroll to the selected resource.
##

fix: checking/unchecking resource should not scroll

---

src/components/molecules/SectionRenderer/SectionHeader.tsx
src/components/molecules/SectionRenderer/useSectionCustomization.ts
src/models/navigator.ts
src/navsections/K8sResourceSectionBlueprint/K8sResourceSectionBlueprint.ts

This PR...
Add a new option to section header for displaying context bellow
-
Connect to a kubernetes cluster

feat: add name context to section header

---

src/components/organisms/TemplateManagerPane/TemplateInformation.styled.tsx
src/components/organisms/TemplateManagerPane/TemplateInformation.tsx

This PR styling Template information item
- styled the template information item
- delete icon overflows the text 
-
-

fix: delete icon overflow text template information

---

src/components/organisms/TemplateManagerPane/TemplateInformation.styled.tsx
src/components/organisms/TemplateManagerPane/TemplateInformation.tsx

- Open button with fix width
- Truncate title if it's too long

fix: truncate title + fix width open button

---

src/components/molecules/TemplateFormRenderer/TemplateFormErrorBoundary.tsx
src/components/molecules/TemplateFormRenderer/TemplateFormRenderer.tsx

This PR...
- added Error Boundary component to catch errors thrown by `rjsf` , which happened when either the form or form ui schemas were invalid and the app would crash
-
-
-

feat: error boundary for template form renderer

---

src/components/organisms/TemplateModal/TemplateModal.tsx
src/components/organisms/TemplateModal/styled.tsx

- Max height for the template modal with scrollbar
- Truncate step name if too long

fix: truncate step name + max height for modal content

---

src/components/organisms/PaneManager/MenuButton.tsx
src/components/organisms/PaneManager/PaneManager.tsx
src/components/organisms/StartProjectPane/StartProjectPane.tsx

This PR...
- disable tool buttons on Get Start screen
- add disabled prop to the menu button
- open Get Start screen
- show disabled `File Explorer - kustomize - helm` buttons
-

fix: disable tool menu when no active project

---

src/components/organisms/PaneManager/PaneManager.tsx

This PR Show existence of Kustomizations/Helm Charts on toolbar buttons
- Added a badge for helm/kustomize tool icons if there are exists resources 
-
- open a project with kustomize/ helm resources 
- show the badge on the tool icon
-

fix: add badge to tool icons

---

src/components/organisms/TemplateModal/TemplateModal.tsx
src/components/organisms/TemplateModal/styled.tsx

- Have separate overflows for steps and forms on the modal ( if you scroll the form, steps will remain in place and vice-versa).

feat: separate scrollbar for steps and form on modal

---

src/components/molecules/SaveResourcesToFileFolderModal/SaveResourcesToFileFolderModal.tsx

- Show the files that will be replaced when selecting `<root>` folder

fix: show files to be replaced for <root>

---

src/components/atoms/SplitView/SplitView.tsx

This PR reopening closed left panel should remember last size
- removed setLeftWidth to zero
-
- resize left pane
- close left pane (try it )
- close the app and reopen (try it)
- 
https://user-images.githubusercontent.com/20525304/150517459-25c624ad-6b31-46e4-9f59-957f3f87ceca.mp4

fix: persist left pane last size

---

src/components/organisms/PageHeader/ClusterSelection.tsx
src/redux/thunks/loadKubeConfig.ts

This PR changes the cluster selector to show the context name instead of context cluster - because multiple contexts can use the same cluster but will have different names
-
-
-
-

fix: use context name instead of cluster in UI

---

src/components/organisms/PageHeader/ProjectSelection.tsx
src/components/organisms/PageHeader/Styled.tsx
src/components/organisms/RecentProjectsPane/RecentProjectsPane.tsx
src/components/organisms/RecentProjectsPane/Styled.tsx

This PR...
- 
- Make project name ellipsis if overflow on recent projects and project selection
-

fix: small UI style bugs

---

src/redux/reducers/appConfig.ts

This PR...
- added default value for `project,lastOpened` in the new created project   
-
-
-

fix: set default value for undefined lastOpen date

---

src/components/organisms/PluginManagerPane/PluginInformation.styled.tsx
src/components/organisms/PluginManagerPane/PluginInformation.tsx
src/components/organisms/PluginManagerPane/PluginManagerPane.tsx
src/components/organisms/TemplateManagerPane/TemplateInformation.styled.tsx
src/components/organisms/TemplateManagerPane/TemplateInformation.tsx
src/components/organisms/TemplateManagerPane/TemplateManagerPane.tsx

This PR...
- removed search bar
- improved styling to match the design from templates manager
- improved popconfirm message to list all templates that will be removed
- sorted templates and plugins in their panes
-
-

plugin manager pane styling improvements

---

electron/main.ts
src/constants/constants.ts

This PR...
- loads default plugins
- fix: #1049 
- Start monokle with and without plugins and the https://github.com/kubeshop/monokle-default-templates-plugin will be loaded
-

feat: load default plugins

---

src/components/organisms/PluginManagerPane/PluginInformation.styled.tsx

- No overlap for the delete icon in `Plugin Pane`

fix: plugin pane delete icon overlap

---

src/components/organisms/PageHeader/ProjectSelection.styled.tsx
src/components/organisms/PageHeader/ProjectSelection.tsx
src/index.css

This PR...
- added table padding
- removed empty `thead` cell  border
-
-
-

fix: table padding

---

src/components/organisms/PaneManager/PaneManager.tsx

This PR...
- Hide panel of recent projects if there is no projects
- open monokle? remove all recent projects, panel should be hidden after delete of last recent project

feat: If there is no recent projects - hide panel

---

src/components/organisms/NavigatorPane/NavigatorPane.styled.tsx
src/components/organisms/NavigatorPane/NavigatorPane.tsx

- Disabled color for Add New Resource button when in preview mode

fix: add new resource button disabled color when in preview mode

---

src/components/organisms/PageHeader/ProjectSelection.styled.tsx
src/components/organisms/PageHeader/ProjectSelection.tsx

This PR...
- added escape keyboard fn to Project management selection
- dismiss project management selection by press escape 
-
- 
https://user-images.githubusercontent.com/20525304/151131405-f470bd23-ee42-4de3-8685-61f1615af5dc.mp4

fix: dismiss project management selection by press escape 

---

src/components/molecules/Monaco/symbolProcessing.ts

fix: remove highlighting of matchLabels in a selector

---

src/components/organisms/PageHeader/ClusterSelection.tsx

This PR...
-
- cluster load/reload tooltip dissapearing
- keep the cursor on the load/reload button for one second and click it
- https://user-images.githubusercontent.com/5509112/151125037-3c73bac7-e4e2-4236-b1cf-9ce758894f9c.mov

fix: hover cluster load

---

src/components/organisms/RecentProjectsPane/RecentProjectsPane.tsx
src/components/organisms/RecentProjectsPane/Styled.tsx

This PR...
- add styles to the active project item in the recent projects list 
- mark active project in recent projects pane
-
-

fix: mark active project in recent projects pane

---

src/components/organisms/NavigatorPane/NavigatorPane.tsx
src/components/organisms/PageHeader/HelpMenu.tsx
src/components/organisms/PageHeader/styled.tsx
src/constants/tooltips.ts

This PR...
- added a tooltip for quick search 
- set setting icons size 18px
-
-
-

fix: quick search tooltip & resize settings icons

---

src/components/organisms/PageHeader/ClusterSelection.tsx

This PR...
- added a hotkey to cluster selection dropdown
-  dismiss cluster dropdown when press escape
-
- 
https://user-images.githubusercontent.com/20525304/151163500-6377a4a5-dea4-4908-97dd-d6f8e30bfa67.mp4

fix: dismiss cluster dropdown when press escape

---

src/components/organisms/PageHeader/ProjectSelection.tsx

This PR...
- add a flag to prevent change dropdown visible state while clicking on the modal 
- keep dropdown open when deleting project
-
-
https://user-images.githubusercontent.com/20525304/151176133-709ac260-e200-490d-9817-3b7f97d1b7a0.mp4

fix: keep dropdown open when deleting project

---

src/components/organisms/RecentProjectsPane/RecentProjectsPane.tsx
src/components/organisms/RecentProjectsPane/Styled.tsx

This PR...
- added max-width to the recent folder project path
- add hover to the recent project list item
-
-
- 
https://user-images.githubusercontent.com/20525304/151191070-9af6da2b-313d-4cb0-aba2-821e72d211a8.mp4

fix: recent project folder path max width

---

src/redux/services/validation.ts

This PR fixes the validator cache to use the correct schema for validation - see screenshot - no more errors!
-
-
-

fix: validator-cache now uses resource kind+apiVersion for key

---

src/components/molecules/SaveResourcesToFileFolderModal/SaveResourcesToFileFolderModal.tsx
src/components/organisms/NewResourceWizard/NewResourceWizard.tsx

- Filter only files by `IsSupported` and `isExcluded` for the dropdown options from `Save to folder` and `Append to file`

fix: filter only files by isSupported and isExcluded

---

src/components/organisms/QuickSearchActions/QuickSearchActions.tsx

- Close quick search modal if you select the resource that is already selected in the navigator

fix: close modal if selecting from dropdown the same selected resource

---

src/components/organisms/PageHeader/ClusterSelection.tsx

- Closes the dropdown when a cluster is selected
- Handle cluster change only if the selected value is different than the current context

fix: close dropdown on cluster select

---

src/components/organisms/PageHeader/ClusterSelection.tsx

- Enable cluster selector when in preview mode

fix: enable cluster selector when in preview mode

---

src/components/organisms/LocalResourceDiffModal/LocalResourceDiffModal.tsx

- Open the local resource diff modal when "diffing" resources from preview mode

fix: open local diff modal for resources from preview mode

---

electron/src/initKubeconfig.ts
src/components/organisms/SettingsDrawer/Settings.tsx

This PR...
- removes hasUserPerformedClickOnClusterIcon
-  kubeconfig error is visible on a clean install
-
-

fix: remove hasUserPerformedClickOnClusterIcon

---

src/components/organisms/ClusterResourceDiffModal/ClusterResourceDiffModal.tsx
src/components/organisms/LocalResourceDiffModal/LocalResourceDiffModal.tsx

- Sometimes, diffing a cluster resource was leading to an error, fixed it by not executing logic inside the component if the modal is not visible

fix: diffing cluster resource would lead to error

---

src/components/organisms/PageHeader/ProjectSelection.tsx

- Close project selection when deleting the active project and opening a new one
- Don't dispatch open project action when selecting from project selection dropdown the currently active project
- Delete active project and select a recent project or open a new one
- Select the active project from the project selection dropdown

fix: project selection small improvements

---

src/components/organisms/NavigatorPane/WarningAndErrorsDisplay.styled.tsx
src/components/organisms/NavigatorPane/WarningsAndErrorsDisplay.tsx

- Add icon for the count of warnings/errors

refactor: show icon for count of warnings/errors

---

src/navsections/K8sResourceSectionBlueprint/ResourceKindPrefix.tsx
src/redux/services/applyMultipleResources.ts
src/redux/thunks/applyResource.ts

- Delete the local resource namespace ( if exists ) when deploying to the cluster so you can deploy it to other namespaces different than the one from metadata
- Add navigator resource namespace tag vertical margin

fix: deploy resource to other namespace

---

electron/commands.ts
src/redux/services/previewReferencedHelmChart.ts
src/redux/thunks/applyResource.ts
src/redux/thunks/previewHelmValuesFile.ts

- Wrap folder name in quotes when running kustomize

fix: wrap folder name with quotes

---

src/hooks/useResourceYamlSchema.ts
src/redux/services/helm.ts

This PR...
- disables yaml validation for all files that do not contain k8s resources
- disable yaml validation for resources that contain go templates
-
-
-

fix: disable validation for go templates

---

src/components/atoms/SplitView/SplitView.tsx
src/components/organisms/ActionsPane/ActionsPane.styled.tsx
src/components/organisms/ActionsPane/ActionsPane.tsx
src/components/organisms/ActionsPane/ActionsPaneFooter.styled.tsx
src/components/organisms/ActionsPane/ActionsPaneFooter.tsx
src/constants/constants.ts
src/models/ui.ts
src/redux/reducers/ui.ts
src/styles/Colors.ts

- Redesign of the actions pane footer
- Make actions pane footer resizable

refactor: actions pane footer

---

src/components/molecules/SectionRenderer/SectionRenderer.tsx
src/components/molecules/SectionRenderer/styled.tsx
src/models/navigator.ts
src/navsections/HelmChartSectionBlueprint/HelmChartSectionBlueprint.ts
src/navsections/sectionBlueprintMiddleware.ts
src/redux/services/helm.ts

This PR...
- added option to show empty section groups if there's an `emptyGroupText` property set
- correctly show charts for which we did not find any values files
- isHelmChartFolder to only check for `Chart.yaml` file
-

fix Helm chart folder recognition

---

src/redux/services/fileEntry.ts
src/redux/services/helm.ts

This PR...
-
- removes helm charts and helm values files from helmChartMap and helmValuesMap when their corresponding files are deleted
-
-

fix: helm charts/values removal

---

electron/main.ts
package.json
src/App.tsx
src/components/molecules/ModalConfirmWithNamespaceSelect/ModalConfirmWithNamespaceSelect.tsx
src/components/organisms/LocalResourceDiffModal/LocalResourceDiffModal.tsx
src/redux/reducers/main.ts
src/redux/services/getClusterObjects.ts
src/redux/services/resource.ts
src/redux/thunks/loadClusterDiff.ts
src/redux/thunks/previewCluster.ts
src/redux/thunks/utils.ts
src/utils/env.ts
src/utils/kubeclient.ts

This PR ensures that all kubeclient instances are created consistently - and ensures that kubeconfig users with exec authentication use the main process env for exec call
-
#1285 
- create a context in kubeconfig that has a user that uses exec authentication (aws) - and attempt to preview this context in Monokle
-

fix: ensured passing of main process env to kubeclient exec authenticator

---

src/components/organisms/CreateProjectModal/CreateProjectModal.tsx

- Use conditional rendering of the steps instead of using CSS `display: none` for hiding them
- Enable `Next: Select a Template` button after clicking on `Back` button on the second step
- Enter a project name
- Go to step 2
- Click on the back button

fix: enable select a template button on back

---

src/constants/clusterResource.ts
src/redux/services/__test__/manifests/invalid-deployment/invalid-deployment.yaml
src/redux/services/validation.ts

This PR adds the following properties to the list of ignored properties during validation:
- finishedAt
- createdAt
- startedAt
- x_kubernetes_preserve_unknown_fields
-
-
-
-

fix: added more properties to ignore during validation

---

src/components/molecules/SectionRenderer/SectionHeader.tsx
src/components/molecules/SectionRenderer/SectionRenderer.tsx
src/components/molecules/SectionRenderer/styled.tsx
src/components/organisms/HelmPane/HelmPane.tsx
src/constants/constants.ts
src/models/navigator.ts
src/navsections/HelmChartSectionBlueprint/HelmChartSectionBlueprint.ts
src/navsections/HelmChartSectionBlueprint/RootHelmChartsSectionBlueprint.ts
src/navsections/HelmChartSectionBlueprint/index.ts
src/navsections/sectionBlueprintMiddleware.ts
src/redux/services/fileEntry.ts
src/redux/services/helm.ts

In this PR I've created a "Values Files" subsection for each helm chart as a starting point for this issue - https://github.com/kubeshop/monokle/issues/586
-
-
-

refactor: create subsections for helm charts

---

src/components/molecules/SectionRenderer/ItemRenderer/ItemRenderer.tsx
src/components/molecules/SectionRenderer/ItemRenderer/styled.tsx
src/components/molecules/SectionRenderer/SectionHeader.tsx
src/components/molecules/SectionRenderer/SectionRenderer.tsx
src/components/molecules/SectionRenderer/styled.tsx
src/components/organisms/PaneManager/MenuButton.tsx
src/models/navigator.ts
src/navsections/HelmChartSectionBlueprint/HelmChartSectionBlueprint.ts

This PR...
- added Chart.yaml as an item directly under the helm chart
- slightly changed the color "Values Files" subsection
- added indentation to it's easier to see where each subsection is 
-
-

show Chart.yaml, improve helm pane styling and section blueprint functionality

---

src/navsections/HelmChartSectionBlueprint/HelmChartSectionBlueprint.ts
src/navsections/HelmChartSectionBlueprint/HelmChartSectionEmptyDisplay.tsx
src/navsections/HelmChartSectionBlueprint/RootHelmChartsSectionBlueprint.ts
src/navsections/HelmChartSectionBlueprint/RootHelmChartsSectionEmptyDisplay.tsx
src/navsections/KustomizationSectionBlueprint/KustomizationSectionBlueprint.ts
src/navsections/KustomizationSectionBlueprint/KustomizationSectionEmptyDisplay.tsx

This PR...
-
- kustomizations items count
- helm chart not visible when it's only one in a project
- empty displays for both kustomize/helm sections
-
-

Helm and Kustomize panes fixes

---

src/components/molecules/SectionRenderer/SectionRenderer.tsx
src/models/navigator.ts
src/navsections/HelmChartSectionBlueprint/HelmChartSectionBlueprint.ts
src/navsections/sectionBlueprintMiddleware.ts
src/redux/reducers/main.ts
src/redux/services/fileEntry.ts
src/redux/services/helm.ts

This PR...
- added new `transformName` method to the section blueprint builder
- reactivity of helm chart section name
- get helm chart name from the file
- update helm chart name when file is updated within Monokle or externally
-
-

fix: update helm chart name on file change

---

electron/main.ts
electron/utils.ts
src/components/organisms/PageHeader/ProjectSelection.tsx
src/redux/selectors.ts

This PR resolves #991
- It now shows a confirmation dialog when you close the window with unsaved files.
- none
- Create a new resource and be sure to use the default "Don't save".
- Close the window or quit the application.

feat: add confirm dialog on window close with unsaved files

---

docs/form-editor.md
src/components/organisms/ActionsPane/ActionsPane.tsx

This PR...
Updated to read Kubernetes resources instead of a dedicated ConfigMap's resource editor form.
-
-
-

Change "ConfigMap Properties Form" to generic "Kubernetes Resources Properties Form"

---

electron/extensions/downloadExtension.ts
src/components/organisms/PluginManager/PluginInstallModal.tsx

This PR...
-
- handle not showing the same error message for the continues attempts
-
-

fix: handle plugin import model error message cache problem

---

src/components/atoms/OrderedList/OrderedList.tsx
src/components/atoms/OrderedList/index.ts
src/components/molecules/PreviewConfigurationDetails/PreviewConfigurationDetails.tsx
src/components/organisms/PreviewConfigurationEditor/PreviewConfigurationEditor.tsx
src/models/appconfig.ts
src/redux/thunks/runPreviewConfiguration.ts

This PR...
- I might've complicated the `OrderedList` component by allowing to specify the property names of the items but I wanted it to be reusable and other solutions were throwing lots of typescript errors
- the order and the isChecked properties of values files from Preview Configurations were not being updated correctly, this PR fixes it 
-
-

fix: update values files in preview configurations

---

src/components/organisms/CreateProjectModal/CreateProjectModal.tsx
src/components/organisms/TemplateManagerPane/TemplateInformation.styled.tsx
src/components/organisms/TemplateManagerPane/TemplateInformation.tsx

This PR...
- removed the "Create Project" button from top right when creating a project from a template
- change the style of the Use Template button
-
-
-

refactor: improve create project from template

---

src/components/organisms/FileTreePane/FileTreePane.tsx

This PR...
-
- shows the root folder name instead of the `<root>` text as the root node in the File Tree
-
-

fix: root folder name in File Explorer

---

src/components/organisms/PreviewConfigurationEditor/PreviewConfigurationEditor.tsx
src/components/organisms/PreviewConfigurationEditor/styled.tsx

fix: add error message if preview configuration name is empty

---

src/redux/reducers/appConfig.ts

This PR...
-
- Remove unused execSync import
-
-

fix: remove unused execSync

---

src/redux/reducers/main.ts
src/redux/thunks/updateResource.ts

This PR...
- Splits updateResource thunk into reducer
- https://github.com/kubeshop/monokle/issues/1472
-
-

fix: split updateResource thunk into reducer

---

src/redux/reducers/main.ts
src/redux/thunks/multiplePathsAdded.ts
src/redux/thunks/multiplePathsChanged.ts
src/redux/thunks/removeResource.ts
src/redux/thunks/updateFileEntry.ts
src/redux/thunks/updateManyResources.ts
src/redux/thunks/updateResource.ts

This PR...
- used the `createNextState` method from redux toolkit which is a copy of the `produce` method from `immer` in order to be able to mutate the main state in thunks and then replace it via returning it in the `.fulfilled` action
-
-
-

fix: use immer in thunks to create next main state

---

src/components/organisms/FileTreePane/FileTreePane.tsx
src/components/organisms/FileTreePane/Styled.tsx
src/components/organisms/PaneManager/PaneMangerSplitView.tsx

- Panes having an overflow and moving infinitely to the right
- File explorer file path overflow ellipsis

fix: panes overflow ( moving towards right )

---

src/App.tsx
src/redux/initialState.ts
src/utils/global-electron-store.ts

This PR...
-
- making sure `paneConfiguration` has an intial state if `config.json` is deleted
- fix error from watching the electronStore onDidChange
-
-

fix: paneConfiguration initial state and electronStore.onDidChange listener

---

src/components/organisms/FileTreePane/Styled.tsx
src/components/organisms/FileTreePane/TreeItem.tsx

This PR...
Truncates file names in file explorer (UI affected)
-
-
- Open the Monokle and have a look on the File explorer files with long names or deep nesting.
- Hover over the filename.
-

feat: file explorer: trancate names and add path for files

---

electron/app/services/pluginService.ts
electron/app/services/templateService.ts

This PR...
- if the `icon` field on plugins or templates is not a URL, populate it with the full folder path
-
-
-

fix: absolute path for plugin/template icons

---

src/components/molecules/SectionRenderer/SectionHeader.tsx
src/components/molecules/SectionRenderer/SectionHeaderDefaultNameCounter.tsx
src/components/molecules/SectionRenderer/styled.tsx
src/components/molecules/SectionRenderer/useSectionCustomization.ts
src/components/organisms/NavigatorPane/WarningAndErrorsDisplay.styled.tsx
src/components/organisms/NavigatorPane/WarningsAndErrorsDisplay.tsx
src/models/navigator.ts
src/navsections/K8sResourceSectionBlueprint/ResourceKindSectionBlueprint.ts
src/navsections/K8sResourceSectionBlueprint/ResourceKindSectionNameCounter.styled.tsx
src/navsections/K8sResourceSectionBlueprint/ResourceKindSectionNameCounter.tsx
src/utils/resources.ts

This PR closes https://github.com/kubeshop/monokle/issues/1495
- Aggregates warnings on collapsing a navigation section.
- Open a project with warnings or errors
- Collapse a nav section with said warnings
- Validate that warnings are aggregated.
https://user-images.githubusercontent.com/7761005/161929246-c4be3314-8a17-4e89-945c-5daf87d1d961.mov
- [x ] tested locally

Aggregate warnings on collapse nav section

---

src/components/organisms/FileTreePane/FileTreePane.tsx

This PR fixes https://github.com/kubeshop/monokle/issues/1602
- Fix project switch
- Have two projects, one with excluded files.
- Swap between them
- Validate it no longer goes black

fix: fix switch project

---

src/hooks/useTargetClusterNamespaces.ts

fix: cluster namespaces list if no kubeConfig set

---

src/components/organisms/PageHeader/ClusterSelection.styled.tsx
src/components/organisms/PageHeader/ProjectSelection.styled.tsx
src/components/organisms/PaneManager/MenuButton/MenuButton.tsx
src/components/organisms/PaneManager/MenuButton/styled.ts
src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
src/components/organisms/PaneManager/PaneManagerSplitView.styled.tsx
src/components/organisms/PaneManager/PaneTooltip/PaneTooltip.tsx
src/components/organisms/PaneManager/PaneTooltip/index.ts
src/styles/Colors.ts

This PR...
Updated according to Julio Comments:
please change colors to:
- top: #101314
- left: #191F21
- the border colors of drop-downs in the top, which are gray-4, have them to gray-5
- the left tab, when highlighted, looks like it have a 2px radio. we need to take that out
- first time, when file explorer is open, the tab on the left does not appear highlighted. We need to highlight it so the tab look is there from scratch
-
-
-
-

fix: ui updates colors and borders

---

src/components/organisms/ActionsPane/ActionsPane.tsx
src/navsections/HelmChartSectionBlueprint/HelmChartSectionBlueprint.ts
src/navsections/HelmChartSectionBlueprint/RootHelmChartsSectionBlueprint.ts
src/redux/services/fileEntry.ts
src/redux/services/helm.ts
tests/git.test.ts

This PR...
- added "Templates" section for all helm charts in the Helm pane
- population of `templateFilePaths` property of helm charts
- closes #1647 
-

Helm Charts fixes and improvements

---

.github/workflows/monokle-build-nightly.yml
.github/workflows/monokle-publish-downloads.yml
.github/workflows/monokle-publish.yml
electron/app/index.ts
electron/app/utils.ts

This PR...
- to make sure the Nucleus installations and sessions are tracked correctly, we will also temporarily track them using our own endpoint
-
-
-

chore: temp alternative telemetry

---

src/App.tsx
src/components/molecules/SectionRenderer/SectionHeader.tsx
src/components/molecules/WalkThrough/WalkThrough.tsx
src/components/molecules/WalkThrough/newReleaseFeaturesContent.ts
src/components/molecules/WalkThrough/types.ts
src/components/molecules/WalkThrough/walkThroughNoviceContent.ts
src/components/organisms/ActionsPane/ActionsPane.tsx
src/components/organisms/NavigatorPane/ClusterCompareButton.tsx
src/components/organisms/PageHeader/HelpMenu.tsx
src/components/organisms/PageHeader/ProjectSelection.tsx
src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
src/models/ui.ts
src/redux/initialState.ts
src/redux/reducers/ui.ts

This PR...
Separates walkthrough logic for new users and new release features.
Currently, the new release feature contains only one step about the validation policy.
I removed the step about validation for a basic walkthrough guide, but maybe we want to join it all together?
Also, the replay functionality will replay only the basic guide.
-
-
-
-

feat: separate walkthrough for new users and release features

---

src/index.css

This PR adds missing scroll bar style to the resource filter on Windows.
https://user-images.githubusercontent.com/7761005/166421561-be497c69-e456-4fb5-8f78-454938a07181.mov

fix: fix filter scroll style

---

src/components/organisms/PaneManager/PaneManager.tsx
src/components/organisms/StartProjectPane/Guide.styled.tsx
src/components/organisms/StartProjectPane/RecentProjectsPage.styled.tsx
src/components/organisms/StartProjectPane/RecentProjectsPage.tsx
src/components/organisms/StartProjectPane/StartProjectPage.styled.tsx

- Show footer on Start Project page and Recent Projects page
- Refactor CSS styling

refactor: show footer on start page + recent projects

---

src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
src/components/organisms/PaneManager/PaneManager.tsx
src/components/organisms/PaneManager/PaneManagerRightMenu.tsx
src/utils/features.tsx

This PR adds a small utility for feature flags.
- It adds a `<FeatureFlag />` which dynamically renders based on typed flags.
- It adds a basic `useFeatureFlags` hook to abstract the feature flag implementation (i.e. the JSON file).

feat: add feature flags

---

electron/app/commands.ts
electron/app/ipc/ipcListeners.ts
package-lock.json
src/components/organisms/ErrorPage/ErrorPage.tsx
src/components/organisms/ErrorPage/ErrorStack.styled.tsx
src/components/organisms/ErrorPage/ErrorStack.tsx
src/components/organisms/PaneManager/PaneManager.tsx
src/index.tsx
src/utils/features.tsx

This PR:
- Hotfixes feature flags.
- Removes right pane as we have to see how this fits within the rework of both the start page and the split pane.
- Improves styling for very long error messages
- Fix "Back to Monokle" on error page by force reloading. Note: there is too much scattered global state for Monokle to reset properly by restoring Redux store to its initial state.

Fixes for release

---

src/utils/telemetry.ts

This PR hotfixes our build.
- It no longer imports `jsx` in the Electron build.

fix: hotfix build

---

electron/app/menu.ts

- Show the force reload shortcut instead of the reload in electron menu

refactor: show force reload shortcut instead of reload

---

src/components/molecules/ContextMenu/ContextMenu.tsx
src/components/organisms/NavigatorPane/WarningsAndErrorsDisplay.tsx
src/components/organisms/PageHeader/ClusterSelection.tsx
src/components/organisms/PageHeader/ProjectSelection.tsx

- Replace deprecated dropdown placement prop `bottomCenter` with `bottom`

fix: replace deprecated placement prop for antd dropdown

---

src/components/organisms/PageHeader/ClusterSelectionTable.styled.tsx
src/components/organisms/PageHeader/ProjectSelection.styled.tsx

- Remove the paddings from table body by setting the overflow-y to `auto`

fix: overflow-y auto for table on selectors

---

src/components/molecules/CheckedResourcesActionsMenu/CheckedResourcesActionsMenu.tsx
src/redux/thunks/removeResources.ts

- Update number of checked resources on resource delete
- Check multiple resources and delete only one resource

fix: update checked selection when deleting resources

---

src/redux/reducers/main.ts
src/redux/thunks/saveUnsavedResources.ts

- Highlight unsaved resource after appending to file ( if the file is already selected )
- Select file from file explorer and then append to the file an unsaved resource

fix: highlight unsaved resource after append

---

src/components/molecules/ResourceRefsIconPopover/RefsPopoverContent.tsx

- Scroll to link in Monaco editor if the resource is not selected
- Click on an outgoing link from a resource that is not selected

fix: scroll to link if resource is not selected

---

src/redux/reducers/main.ts

- Deselect image on preview / exiting preview
- Have an image selected and load the cluster

fix: deselect image on preview/exit

---

src/components/organisms/FileTreePane/styled.tsx
src/redux/selectors.ts

This PR I fix a selector that I overlooked while I fixed [fix multiple cluster resource sets](https://github.com/kubeshop/monokle/pull/1910/commits/9fbb6eb390ac318075dbeb7e734d08c09fd42200) and [fix cluster preview](https://github.com/kubeshop/monokle/pull/1910/commits/8095c85ba5f45ff4a7bd3fbf128656e07ed19ea4).
It's quite a visual bug so best to include it in release (In the navigator during preview you currently get the teal colored label instead the orange one) 
So what happened is this: createKubeClient in preview cluster used `createClient(configObject, contextString)` but when we use a configObject and not a configString then we had a bug that it ignored the provided context. Once I fixed that, I found a bug where we actually never passed contextString to begin with but instead the …

Fix is cluster mode

---

src/components/molecules/HotkeyLabel/HotkeyLabel.styled.tsx
src/index.css

- Tooltip hotkey overflow
- Hover over left menu options that have tooltips

fix: tooltip hotkey overflow

---

src/components/molecules/ModalConfirmWithNamespaceSelect/ModalConfirmWithNamespaceSelect.tsx
src/components/organisms/LocalResourceDiffModal/LocalResourceDiffModal.tsx
src/redux/services/compare/fetchResources.ts
src/redux/thunks/loadClusterDiff.ts
src/redux/thunks/previewCluster.ts
src/utils/kubeclient.ts

- Use kube config selector for getting the path and context used for creating the kube client
- Delete a resource from the cluster directly

fix: cluster resource delete

---

src/components/molecules/FilterPopover/FilterPopover.tsx

- Don't show popover when the filter button is disabled
- Hover over filter button when it is disabled

fix: don't show popover when button is disabled

---

src/components/organisms/NewResourceWizard/NewResourceWizard.tsx
src/models/k8sresource.ts
src/redux/services/compare/transferResource.ts
src/redux/services/resource.test.ts
src/redux/services/resource.ts
src/redux/services/unsavedResource.ts

- Add `isKindNamespaced` property on K8sResource
- Hide namespace input on the new resource wizard if the kind is not namespaced

feat: hide namespace for cluster scoped resources

---

src/App.tsx

- Only show release notes for the next big release, do not show it for patch releases
- Switch version from `1.8.0` to `1.8.1`
- Switch version from `1.7.5` to `1.8.1`

feat: show release notes only for the next big release

---

src/models/appstate.ts
src/redux/initialState.ts
src/redux/reducers/main.ts

This PR...
- Restores the previous selection history when previewing a helm chart or kustomize fails.
- Build up a selection history by moving between files or resources, make a change that will lead to a failure when launching a preview, then click preview. After the preview fails check that the selection history has been restored to its previous state.

fix: restore the previous selection history when preview fails

---

src/navsections/ImagesSectionBlueprint/ImagesQuickAction.styled.tsx
src/navsections/ImagesSectionBlueprint/ImagesQuickAction.tsx

- Disabled image `Replace` action when in preview mode

feat: disable replace in preview mode

---

src/utils/shell.ts

This PR...
- #2027
1. Create a project using template
2. Click on "Create a resource" in navigator
3. In Namespace click "read more" you can see "read more" by hovering on help symbol
4. Link direct to [Namespace](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/)

fix: Namespace help link goes to wrong kubernetes docs page

---

src/kindhandlers/EndpointSlice.handler.ts
src/kindhandlers/Endpoints.handler.ts
src/kindhandlers/index.ts

This PR adds support for EndpointSlice resources - see #2034 
Includes RefMappers for target objects and associated services

feat: added EndpointSlice handler

---

src/components/molecules/ResourceRefsIconPopover/RefsPopoverContent.tsx
src/components/molecules/ValidationErrorsPopover/ErrorsPopoverContent.tsx
src/navsections/ImagesSectionBlueprint/ImageOutgoingResourcesPopover.styled.tsx
src/navsections/ImagesSectionBlueprint/ImageOutgoingResourcesPopover.tsx
src/navsections/ImagesSectionBlueprint/ImagesSectionNameSuffix.styled.tsx
src/navsections/ImagesSectionBlueprint/ImagesSectionNameSuffix.tsx
src/utils/refs.ts

- Add popover with corresponding resources links for each image

feat: resources popover for images

---

src/kindhandlers/HorizontalPodAutoscaler.handler.ts
src/kindhandlers/LimitRange.handler.ts
src/kindhandlers/ResourceQuota.handler.ts
src/kindhandlers/StorageClass.handler.ts
src/kindhandlers/VolumeAttachment.handler.ts
src/kindhandlers/index.ts

This PR adds support for the following k8s objects
- HorizontalPodAutoscaler (#1588)
- LimitRange
- ResourceQuota
- StorageClass

feat: added more native resource kinds to navigator

---

src/components/molecules/NotificationMarkdown/TelemetryButtons.tsx
src/components/molecules/NotificationMarkdown/styled.tsx

This PR...
Added Margin to telemetry buttons as requested in #2055 
-
-
Run application after removing config.json in Monokle application data folder.

style: added margin to telemetry buttons content in notification box

---

src/components/molecules/FilePatternList/FilePatternList.tsx

This PR... related to #2053
- fixed styling when editing cluster selection namespace
-
-
Was:
Fixed:

fix: fixed displaying list of FilePatternListItem in cluster when editing context

---

src/components/organisms/StartProjectPane/StartProjectPage.styled.tsx
src/components/organisms/StartProjectPane/StartProjectPage.tsx

This PR...
-
- removed media queries and displayed title always in two lines
- fixed square symbol on windows
-
-

fix: removed media query and displaying title always in two lines after investigation with @julio

---

src/components/organisms/SearchPane/SearchPane.tsx

This PR...
- #2115
- You can find the `RECENT SEARCH` is disabled when no search was previously made.
- Once you did the search `RECENT SEARCH` will be enabled.
- You can see initially `RECENT SEARCH` is not visible.
- After search you can see the `RECENT SEARCH`

fix: recentSearch boolean check added to child component

---

src/components/organisms/SearchPane/styled.tsx

This PR...
- #2114 
- Hover on the Search items, you can only select the words and not the blank space area

fix: select hover in search fixed

---

src/components/molecules/NotificationMarkdown/NotificationMarkdown.tsx

- Apply markdown on the see more notification content

fix: enable markdown for see more notification content

---

electron/app/createWindow.ts
electron/app/ipc/ipcListeners.ts
package-lock.json
src/components/organisms/StartProjectPane/StartProjectPage.tsx
src/components/organisms/TerminalPane/TerminalPane.styled.tsx
src/components/organisms/TerminalPane/TerminalPane.tsx
src/constants/tooltips.tsx
src/models/appstate.ts
src/models/rootstate.ts
src/models/terminal.ts
src/redux/initialState.ts
src/redux/reducers/extension.ts
src/redux/reducers/main.ts
src/redux/reducers/terminal.ts
src/redux/store.ts

- Add action button to kill the terminal instead of just hiding it
- Fit on reopening terminal
- Start project page keys missing from a map warning

feat: kill terminal

---

src/App.tsx
src/components/molecules/Walkthrough/Walkthrough.tsx
src/components/molecules/Walkthrough/content/newReleaseFeatures.ts
src/components/molecules/Walkthrough/content/novice.ts
src/components/organisms/PageHeader/HelpMenu.tsx
src/models/walkthrough.ts
src/redux/reducers/ui.ts

- Rename `WalkThrough` to `Walkthrough`

refactor: rename WalkThrough to Walkthrough

---

docs/hotkeys.md
src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
src/constants/hotkeys.ts
src/constants/tooltips.tsx

- Add hotkey for terminal pane toggle - Ctrl/Cmd + ` ( screenshot 2 )
- Add tooltip for terminal menu option ( screenshot 1 )
- Update hotkey for setting toggle on docs

feat: toggle terminal pane hotkey

---

src/components/molecules/FormEditor/FormEditor.tsx

- Disable form editor in preview mode

fix: disable form editor in preview mode

---

src/components/organisms/BottomPaneManager/BottomPaneManager.styled.tsx
src/components/organisms/BottomPaneManager/BottomPaneManager.tsx
src/components/organisms/TerminalPane/TerminalPane.tsx
src/models/terminal.ts
src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenu.tsx
src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenuWrapper.tsx

- Show pod name and namespace in terminal when opening a shell into a pod

feat: terminal name for pod shell

---

src/components/molecules/ModalConfirmWithNamespaceSelect/ModalConfirmWithNamespaceSelect.tsx

- Have the create namespace option on deploying a resource modal

fix: bring back create namespace option

---

src/components/organisms/FileTreePane/TreeItem.tsx
src/constants/constants.ts

- Smaller font-size for tooltip text ( 12 px )
- Break chars instead of words
- 2 seconds delay before showing the tooltip, instead of 1 second

refactor: tree item tooltip overlay style

---

src/components/organisms/BottomPaneManager/BottomPaneManager.styled.tsx
src/components/organisms/BottomPaneManager/BottomPaneManager.tsx
src/components/organisms/TerminalPane/TerminalPane.tsx
src/index.css

- Have a popconfirm for killing a terminal instead of a modal
- Add horizontal scrolling when there are multiple terminals opened
-

feat: terminal tabs horizontal scrolling + popconfirm

---

src/components/molecules/ResourceFilter/ResourceFilter.tsx
src/navsections/K8sResourceSectionBlueprint/K8sResourceSectionBlueprint.ts
src/navsections/K8sResourceSectionBlueprint/ResourceKindSectionBlueprint.ts
src/redux/selectors.ts
src/utils/resources.ts

- Ignore `file/folder container in` filter when in preview mode

fix: ignore file/folder contained in filter when in preview mode

---

src/navsections/K8sResourceSectionBlueprint/ResourceKindInformation.styled.tsx
src/navsections/K8sResourceSectionBlueprint/ResourceKindInformation.tsx
src/navsections/K8sResourceSectionBlueprint/ResourceKindSectionBlueprint.ts
src/navsections/UnknownResourceSectionBlueprint/UnknownResourceSectionBlueprint.ts
src/styles/Colors.ts

- Refactor Age/Status info
- Different colors for `Closed`, `Running` and `Active` status
- Filled info icon

refactor: age/status info

---

src/components/organisms/NavigatorPane/WarningAndErrorsDisplay.styled.tsx
src/components/organisms/NavigatorPane/WarningsAndErrorsDisplay.tsx

- Add padding to warning/errors dropdown
- Use Antd Menu `items` prop instead of deprecated `children`

refactor: warnings/errors dropdown padding

---

src/components/organisms/ActionsPane/ActionsPaneHeader.tsx
src/components/organisms/ActionsPane/Restart/Restart.tsx
src/components/organisms/ActionsPane/Scale/Scale.tsx

- Show scale/restart buttons only in cluster mode

refactor: show scale/restart only in cluster mode

---

src/App.tsx
src/components/molecules/NotificationMarkdown/TelemetryButtons.tsx

-Close alert after clicking on button and open notifications drawer

fix: close alert after clicking on button and open notifications

---

src/navsections/HelmChartSectionBlueprint/HelmChartQuickAction.styled.tsx
src/navsections/HelmChartSectionBlueprint/HelmChartQuickAction.tsx
src/navsections/KustomizationSectionBlueprint/KustomizationQuickAction.tsx

- Bring back quick preview action when already previewing a helm/kustomization

feat: quick preview action when previewing helm/kustomization

---

src/redux/services/helm.ts

This PR fixes handling of invalid Chart.yaml files - but still needs improvements in regard to rendering performance of the Helm panel when loading the helm/helm repo - see #2260 
@devcatalin can you look into the performance - you can perhaps use this branch for improving?

fix: improved handling of invalid Chart.yaml

---

src/constants/terminal.ts
src/redux/services/terminalShells.ts

Signed-off-by: Dipankar Das <dipankardas0115@gmail.com>
This PR...
- Addition of ZSH shell for the 'other' OS
- Issue #2306

feat(terminal): added ZSH shell for Linux based OS

---

package-lock.json
src/navsections/K8sResourceSectionBlueprint/ResourceKindSectionNameCounter.tsx

- Extend kind section when clicking on warnings/errors count

fix: extend kind section when clicking on warnings/errors count

---

electron/app/git/git.ts
src/utils/git.ts

- Fixed Git Changelist which was returning the `modifiedContent` and `name` properties undefined when you're opening a subfolder of a Git repository as a project in Monokle.

fix: git changelist for nested folder projects

---

src/components/organisms/SearchPane/SearchPane.tsx

- Don't show number 0 when there are no recent searches in `SearchPane`
Without fix:
With fix:

fix: don't show 0 when there are no recent searches

---

electron/app/git/git.ts
electron/app/git/ipc.ts
src/components/organisms/GitPane/FileList.styled.tsx
src/components/organisms/GitPane/FileList.tsx
src/models/git.ts
src/redux/services/gitFolderMonitor.ts
src/redux/thunks/setRootFolder.ts
src/styles/Colors.ts
src/utils/git.ts

- Corresponding colors for added/deleted/modified files
- Absolute + relative paths for files
- Improved getting git changed files ( with `git.status` )
- Monitor when a file is staged/unstaged from outside Monokle when in a subfolder of a git repo as root path

feat: git changed files paths and colors

---

electron/app/git/git.ts
electron/app/git/ipc.ts
src/components/molecules/BranchSelect/BranchSelect.tsx

- Show warning modal when checking out to another branch is not possible

feat: warn user when checkout is not possible

---

src/components/organisms/PageHeader/ClusterSelection.styled.tsx

- 220px when device screen is bigger than 1270px
- 280px when device screen is bigger than 1440px

refactor: cluster selection size

---

src/components/organisms/GitPane/BottomActions.tsx

- Disable Sync button only when git repo is not found
- Push button ( from dropdown ) will remain disabled if no local commits are found ( ahead of the remote )

feat: enable sync button

---

src/components/molecules/Monaco/Monaco.tsx

- Dispose only models that are not attached to any editor

fix: dispose only models not attached to any editor

---

src/components/organisms/PageHeader/ProjectSelection.styled.tsx
src/components/organisms/PageHeader/ProjectSelection.tsx

- Ellipsis for project name when too long

fix: show ellipsis + hover full name for project name

---

src/components/organisms/CompareModal/ResourceSetSelector/ClusterContextSelect.tsx
src/components/organisms/CompareModal/ResourceSetSelector/GitSelect/GitBranchSelect.tsx
src/components/organisms/CompareModal/ResourceSetSelector/HelmSelect/HelmChartSelect.tsx
src/components/organisms/CompareModal/ResourceSetSelector/HelmSelect/HelmValuesOrConfigSelect.tsx
src/components/organisms/CompareModal/ResourceSetSelector/KustomizeSelect.tsx
src/components/organisms/CompareModal/ResourceSetSelector/ResourceSetTypeSelect.tsx

- Disable kustomize/helm preview options if there are no results found
- Default open of the dropdowns ( except for the git commits dropdown as we select by default the latest commit )

refactor: disable helm/kustomize in compare&sync

---

src/components/organisms/PaneManager/PaneManagerLeftMenu.styled.tsx
src/styles/Colors.ts

- Left menu badge background color

refactor: change left menu badge background color

---

.gitignore
electron/app/createWindow.ts
electron/app/utils.ts
src/components/organisms/PageHeader/ProjectSelection.tsx

- Remove warning if there are terminals open when switching a project or closing the Monokle window
-
-

fix: remove warning for terminals

---

src/hooks/fileTreeHooks/useFileSelect.tsx

- No longer being able to select a folder as a file

fix: being able to select folders as files

---

src/components/molecules/Monaco/Monaco.tsx

- Show editor for files that are empty

fix: show editor for empty files

---

src/redux/services/kustomize.ts
src/redux/services/resource.ts

Fixes:
- improved handling of external refs
- handling of path refs ending with path separator
- handling of resource refs to files without resources

fix: a bunch of kustomize fixes and refactorings backported from Cloud

---

src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx

- Duplicated walkthrough meant for images ( appearing next to git pane also )

fix: duplicated images walkthrough

---

src/components/organisms/FileTreePane/FileTreePane.tsx
src/components/organisms/SettingsManager/SettingsManager.tsx
src/models/appconfig.ts
src/redux/initialState.ts
src/redux/reducers/appConfig.ts
src/utils/electronStore.ts
src/utils/fileExplorer.ts

- Global settings for sorting file explorer ( folders first, files first or mixed )

feat: sorting files folders

---

src/components/molecules/NotificationMarkdown/NotificationMarkdown.tsx

This PR...
- `<p>` to `<pre>` for notification message to improve readibility 
- [Issue #2778](https://github.com/kubeshop/monokle/issues/2778) 
- Deploying multiple K8s resources as described in [issue](https://github.com/kubeshop/monokle/issues/2778)
- Before
- After

Changed paragraph to preformatted text

---

src/redux/services/kustomize.ts

fix: add support for external patch refs

---

electron/app/git/git.ts
electron/app/git/ipc.ts
src/redux/services/compare/fetchResources.ts

- Show content of resources from the commit hash not branch name

fix: git compare resource content

---

resources/releaseNotes/1.13/1.13.md

This PR fixes https://github.com/kubeshop/monokle/issues/2922 by updating the blog post link in the 1.13 release notes.
-
https://github.com/kubeshop/monokle/issues/2922
-
-
-

Fixed blog's broken link in 1.13 release notes.

---

src/components/organisms/SettingsManager/SettingsManager.tsx

- Set default project settings when there is no active project

fix: default project settings when no active project

---

public/Splashscreen.css
public/index.html
src/components/atoms/MonoPaneTitle/MonoPaneTitle.tsx
src/components/molecules/Logs/Logs.styled.ts
src/components/organisms/FileTreePane/styled.tsx
src/components/organisms/KeyboardShortcuts/BoardKeys/BoardKeys.styled.tsx
src/components/organisms/SearchPane/styled.tsx
src/index.css

- Change default font-family to `Inter`

refactor: change default font-family to Inter

---

package-lock.json
package.json
src/components/molecules/Monaco/Monaco.styled.tsx
src/components/organisms/ActionsPane/ActionsPane.styled.tsx
src/components/organisms/ActionsPane/ActionsPane.tsx
src/components/organisms/ActionsPane/ActionsPaneHeader.tsx
src/components/organisms_new/PaneManager/PaneManager.tsx
src/components/organisms_new/PaneManager/PaneManagerLeftMenu.tsx
src/components/organisms_new/PaneManager/activities.tsx
src/utils/hooks.ts

- Show the left menu ( settings and dashboard options ) when quick previewing a cluster
- Update stylings
- Height for actions pane

feat: enable validation

---

src/components/organisms/PageHeader/ClusterSelection.styled.tsx
src/components/organisms/PageHeader/ClusterSelection.tsx
src/constants/tooltips.tsx
src/models/appconfig.ts
src/redux/initialState.ts
src/redux/reducers/appConfig.ts
src/redux/reducers/main.ts
src/redux/services/clusterResourceWatcher.ts
src/redux/services/preview.ts
src/redux/thunks/previewCluster.ts
src/redux/thunks/previewKustomization.ts
src/redux/thunks/startClusterPreview.ts
src/utils/electronStore.ts

- When loading the cluster, fetch the resources with the namespace the same as the one currently selected

feat: fetch namespace cluster resources

---

src/components/organisms/GitCloneModal/GitCloneModal.tsx

- Create the provided location folder ( if it doesn't exist ) when trying to clone a repo

feat: create folder from location if it doesn't exist

---

src/components/organisms/CompareModal/CompareModalSelecting.tsx
src/components/organisms/GitCloneModal/GitCloneModal.tsx

- Remove the folder that is created when cloning a repo if the cloning fails

feat: remove repo name directory if cloning fails

---

src/redux/selectors.ts

The `currentConfigSelector` always returns a new object because of the `mergeConfig` function, so we should use the deep equal selector to check if it's outpus has actually changed, otherwise it will re-render components even if it doesn't change.
All other selectors that depend on the currentConfigSelector must also be deeply compared.

fix: config selectors re-rendering

---

src/components/molecules/FormEditor/FormWidgets/ApiGroupSelection.tsx
src/redux/reducers/appConfig.ts
src/redux/services/resource.ts
src/redux/store.ts
src/redux/validation/validation.worker.ts
src/redux/validation/validation.worker.types.ts
src/redux/validation/validator.ts

- adds a listener on `setOpenProject`
- loops through all the core kind handlers to get the schemas
- registers the schemas in the validator

fix: validation for k8s schema

---

electron/app/KubeConfigManager.ts
src/components/organisms/SettingsPane/Settings/Settings.tsx
src/shared/utils/kubeclient.ts

This PR throws a custom error on Cluster Connection error on the namespace access check and it doesn't throw notifications for every namespace. So hopefully it will not bother the users.
-
-
-
-

chore: remove bulk cluster connection notifications on access check

---

.github/workflows/monokle-build-nightly.yml

This PR adds a manual prerelease step as alternative to nightly builds on `main`.

chore: add manual prereleases

---

src/components/molecules/FormEditor/FormEditor.tsx
src/components/molecules/ResourceDiff/ResourceDiff.tsx
src/components/molecules/SaveResourcesToFileFolderModal/SaveResourcesToFileFolderModal.tsx
src/components/organisms/ClusterResourceDiffModal/ClusterResourceDiffModal.tsx
src/components/organisms/LocalResourceDiffModal/LocalResourceDiffModal.tsx
src/redux/services/__test__/yaml.test.ts
src/redux/services/manifest-utils.ts
src/redux/services/transientResource.ts
src/redux/thunks/applyMultipleResources.ts
src/redux/thunks/applyResource.ts
src/redux/thunks/renameResource.ts
src/redux/thunks/utils.ts
src/utils/crds.ts
src/utils/yaml.ts

This PR fixes #3393 by ensuring consistent yaml parsing/stringification and special handling for PodSpec/Volume related properties
-
-
-
-

fix: consistent YAML parsing/stringification and octal formatting

---

src/components/molecules/ResourceGraphTab/ResourceGraphTab.tsx
src/redux/reducers/main/mainSlice.ts

- Loading resources from previous namespaces when switching between them
- Connect to the cluster
- After 1-2 seconds, switch to another namespace
- Previous resources should not be loaded

fix: remove watchers when reloading resources

---

electron/app/services/cluster/daemons/kubeconfigWatcher.ts
electron/kubernetes/ProxyInstance.ts
src/components/organisms/SettingsPane/Settings/Settings.tsx
src/shared/models/config.ts

- Fixed the case where loading a kubeconfig still returns as valid from the k8s client node, even if the array of context/cluster 
- Load a random file ( containing only strings for example )
- See the warning icon appear in the settings

fix: kubeconfig isValid

---

src/redux/services/fileMonitor.ts

- Removing a file would show a git error modal
- Delete a file from file explorer
- File should be deleted and no git error shown

fix: removing file shows git error modal

---

src/components/organisms/NavigatorPane/KindRenderer/KindSuffix.tsx
src/components/organisms/NavigatorPane/NavigatorPane.tsx
src/components/organisms/NavigatorPane/ResourceRenderer/ResourceRenderer.styled.tsx
src/constants/tooltips.tsx

- Add button tooltip when disabled
- Disable add resource in cluster mode

fix: disable add resource in cluster mode + add tooltip

---

src/redux/reducers/main/mainSlice.ts
src/redux/validation/validation.listeners.tsx

This PR...
- Clears the selection on `deleteMultipleClusterResources` if any of the deleted resources was the current selection
- Handle `multiplePathsRemoved`, `updateMultipleClusterResources` and `deleteMultipleClusterResources` in the validation listener (Closes https://github.com/kubeshop/monokle/issues/3783)

fix: handling side effects from removing files or resources

---

src/redux/cluster/thunks/connect.ts
src/redux/thunks/cluster/loadClusterResources.ts

This PR...
- when changing context, set the namespace to default
-  check namespace existence before loading the resources 
-
-
-

fix: connect to default namespace when nonexistence namespace 

---

src/components/organisms/ExplorerPane/FilePane/FileSystemTree/FileSystemTree.tsx

fix: check values file if it is associated with a Helm Chart

---

src/components/organisms/ExplorerPane/KustomizePane/KustomizeList.tsx
src/components/organisms/ExplorerPane/KustomizePane/KustomizeRenderer/KustomizeRenderer.tsx
src/redux/selectors/kustomizeSelectors.ts

This PR fixes #3498 - I opened #3859 as a follow-up
-
-
-

fix: show name of overlay folder instead of filename in navigator

---

src/redux/services/resource.ts
src/redux/thunks/utils.ts

This PR fixes #3862 - we won't remove null values in local files since they might be there for a reason. Also removed the parsedDocCache as this was a remnant from when we did ref processing in Desktop - the cache wasn't used anymore and a potential memory-leak..
-
-
-
-

fix: remove parsedDoc cache and improve handling of timestamp in files

---

src/redux/validation/validation.thunks.ts

This PR makes unresolved optional links show up as warnings instead of errors - until we have #3840 resolved
-
-
-
-

fix: mark unresolved optional-links as warnings for now

---

src/components/organisms/ExplorerPane/FilePane/FilePane.tsx
src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/hooks.tsx
src/components/organisms/ExplorerPane/FilePane/useSetFolderFromMainThread.ts
src/components/organisms/ExplorerPane/KustomizePane/KustomizeRenderer/KustomizeContextMenu.tsx
src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
src/components/organisms/SettingsPane/Settings/Settings.tsx
src/redux/appConfig/appConfig.slice.ts
src/redux/reducers/main/mainSlice.ts
src/redux/thunks/setRootFolder.ts

- Keep transient resources when reloading file tree

fix: keep transient resources on reload

---

package-lock.json
package.json
src/components/molecules/ClosedPanePlaceholder/ClosedPanePlaceholder.tsx
src/components/molecules/ClosedPanePlaceholder/index.ts
src/components/molecules/index.ts
src/components/organisms/BottomPaneManager/BottomPaneManager.styled.tsx
src/components/organisms/PaneManager/PaneManager.tsx
src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
src/constants/constants.ts
src/shared/constants/constants.ts
src/shared/models/ui.ts

- Styling when the left pane is closed ( explorer )
- Styling when an option is active

refactor: pane manager

---

resources/schemas/kustomization.json
src/shared/constants/electronStore.ts

This PR updates to the latest kustomize 5.x schema and enables Helm features by default as some users are getting a related error message
-
-
-
-

fix: updated to latest Kustomize schema and enable helm by default

---

src/components/organisms/PaneManager/PaneManager.tsx

- Show `ClosedPanePlaceholder` only when the explorer option is active

fix: showing closed pane placeholder

---

src/components/organisms/ExplorerPane/KustomizePane/KustomizeRenderer/KustomizeRenderer.tsx

This PR fixes the rendering of an empty string when an overlay is in the root folder
-
-
-
-

fix: rendering of kustomization name when in root folder

---

src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/hooks.tsx

- Remove `New File/Folder` from file context menu

refactor: remove New File/Folder from file context menu

---

src/components/organisms/PaneManager/PaneManager.tsx
src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx

- Clicking on the same currently selected option would trigger the active status and the event tracking

fix: tracking event when clicking on the same option currently selected

---

craco.config.js

This PR...
- locally we don't need the Sentry plugin while building and this threw an error

chore: fix local builds

---

src/utils/crds.ts

This PR...
- added tr/catch cluse to handle EEXIST: file already exists. 
-  fixing a race condition while saving many crds at once 
-
-

fix: catch crd dir exists error

---

src/components/organisms/PaneManager/PaneManager.tsx
src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx

- Keep `leftMenuActive` status while changing left menu options

fix: keep leftMenuActive status when changing options

---

src/components/organisms/ExplorerPane/KustomizePane/KustomizeRenderer/KustomizeRenderer.tsx
src/components/organisms/ResourceSetSelector/KustomizeSelect.tsx
src/utils/kustomize.ts

- Kustomize name rendering in compare dropdown

fix: kustomize name in compare dropdown

---

package-lock.json
package.json
src/components/molecules/ResourceGraphTab/ResourceGraphTab.tsx

- Match cluster namespace with the graph namespace filter

feat: match cluster namespace with the graph filter namespace

---

src/components/organisms/CompareSyncPane/CompareSyncPane.tsx
src/components/organisms/CompareSyncPane/ComparisonList/ComparisonList.tsx
src/components/organisms/CompareSyncPane/InspectionActionBar/InspectionActionBar.styled.tsx
src/components/organisms/CompareSyncPane/TransferButton/TransferButton.tsx

- Show a confirm when trying to transfer a resource in the compare & sync
- Show back the extract buttons inside the inspection ( diff )

fix: add modal confirms when transferring in compare

---

src/components/organisms/ExplorerPane/HelmPane/HelmContextMenu.tsx
src/components/organisms/ExplorerPane/KustomizePane/KustomizeRenderer/KustomizeContextMenu.tsx
src/redux/reducers/ui.ts
src/shared/utils/file.ts
src/shared/utils/index.ts

- On selecting a file, expand the file tree accordingly so that the selected file is shown
- On select file, set the selected section to `files`

fix: on selecting a file, expand tree accordingly

---

src/components/organisms/ExplorerPane/PreviewConfigurationPane/PreviewConfigurationRenderer/PreviewConfigurationRenderer.styled.tsx
src/utils/helm.ts

- In some cases, the chart path ends with the corresponding OS separator. Removed it if found.
- Hovering styling of the helm configuration preview

fix: preview helm configuration

---

src/components/organisms/ActionsPane/ActionsPane.tsx

This PR...
- handle case when the graph tab is active then select a resource that has no graph 
-
-
-

fix: reset actions tab when changing file

---

src/components/organisms/ExplorerPane/PreviewConfigurationPane/PreviewConfigurationRenderer/PreviewConfigurationQuickAction.tsx
src/redux/thunks/previewConfiguration.ts

- Show `Exit` quick action when the preview configuration is being previewed
- If the preview configuration is selected and deleted, clear the selection
- If the preview configuration is being previewed and deleted, clear selection and stop the preview

fix: preview configuration multiple fixes

---

src/components/molecules/QuickActionCompare/QuickActionCompare.styled.tsx
src/components/molecules/QuickActionPreview/QuickActionPreview.styled.tsx
src/components/molecules/QuickActionPreview/QuickActionPreview.tsx
src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/TreeNode.styled.tsx
src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/TreeNodeFile.tsx
src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/hooks.tsx
src/components/organisms/ExplorerPane/HelmPane/HelmChartRenderer/HelmChartRenderer.tsx
src/components/organisms/ExplorerPane/HelmPane/HelmValueRenderer/HelmValueRenderer.styled.tsx
src/components/organisms/ExplorerPane/HelmPane/HelmValueRenderer/HelmValueRenderer.tsx
src/components/organisms/ExplorerPane/ImagesPane/ImageFilteredTag.tsx
src/components/organisms/ExplorerPane/KustomizePane/KustomizeRenderer/KustomizeRenderer.styled.tsx
src/components/organisms/ExplorerPane/KustomizePane/KustomizeRenderer/KustomizeRenderer.tsx
src/components/organisms/PageHeader/PreviewControl/PreviewLabel.tsx
src/redux/ipcRendererRedux.ts
src/redux/reducers/main/selectors.ts

- Show the context menu dots only on hover
- Change `Preview` label to `Dry-run`

refactor: is hovered renderers + change preview to dry-run

---

src/components/organisms/ExplorerPane/HelmPane/HelmChartRenderer/HelmChartRenderer.tsx
src/redux/services/fileEntry.ts
src/redux/services/helm.ts
src/shared/models/helm.ts

This PR associates parent charts with child charts - and displays corresponding naming in Helm Chart Sections
-
-
-
-

fix: support for identifying child/parent charts

---

src/components/organisms/NewResourceWizard/NewResourceWizard.tsx
src/redux/services/transientResource.ts
src/redux/thunks/saveResourceToFileFolder.ts
src/redux/thunks/saveTransientResources.ts
src/shared/models/resourceCreate.ts

- Do not create duplicate transient resource when saving a new resource to folder / append to a file

fix: create resource and save to folder / append to file duplicate

---

src/components/organisms/Dashboard/Overview/Overview.styled.tsx
src/components/organisms/Dashboard/Overview/Status.styled.tsx
src/components/organisms/Dashboard/Overview/Status.tsx

- Cluster dashboard warnings/errors count styling

fix: dashboard warnings/errors count

---

src/components/organisms/StartPage/StartPageHeader.styled.tsx
src/components/organisms/StartPage/StartPageHeader.tsx
src/shared/styles/borders.ts

- Add a `Back to project` button in the start page header when there is an active project

feat: active back to project button

---

src/components/organisms/NavigatorPane/EmptyResourceNavigator/EmptyResourceNavigator.tsx
src/components/organisms/NavigatorPane/EmptyResourceNavigator/NewResourceCard.tsx
src/hooks/menuItemsHooks/useNewResourceMenuItems.tsx
src/shared/models/resourceCreate.ts

- Order + labels of creating a new resource options
- Disable options of creating new resource from empty navigator in cluster mode

feat: order of create resource options + disable in cluster mode

---

src/components/organisms/TemplateExplorer/CreatedResources/SaveToFolderModal.tsx
src/hooks/useFolderTreeSelectData.ts

- By default show project root folder as value when saving transient resources
- Saving multiple resources with same name from template would override each other

fix: saving multiple resources with same name from template

---

src/components/organisms/ActionsPane/ActionsPaneHeader.tsx
src/redux/thunks/runPreviewConfiguration.ts

This PR...
- allow users to select a namespace where the helm dry-run config should be deployed

feat: select namespace for dry-run config deploy

---

docs/docs/cluster-issues.md
docs/docusaurus.config.js
docs/package-lock.json

This PR...
- There is a conflict mark present in `docs/docs/cluster-issues.md`
- There are inconsistent spaces at the end of several lines.
- Fixed the generated edit link in `docs/docusaurus.config.js`
- `docs/package-lock.json` wasn't updated, already updated with `npm i`
- Removed conflict mark 
- Removed inconsistent spaces
- Append `docs/` for edit links
- View `docs/docs/cluster-issues.md` at [https://docs.monokle.io/cluster-issues/](https://docs.monokle.io/cluster-issues/)
- View every pages and click the `edit this page`
- ![](https://github.com/kubeshop/monokle/assets/11081491/96423b72-acc5-439e-b745-43105f29a5a7) Located at: [https://docs.monokle.io/cluster-issues/](https://docs.monokle.io/cluster-issues/)
- ![](https://github.com/kubeshop/monokle/assets/11081491/ddf32885-cc5e-4c …

docs: remove conflict marker and fixed the incorrect edit link editor

---

src/components/organisms/ExplorerPane/DryRunsPane/DryRunsPane.tsx
src/redux/selectors/dryRunsSelectors.ts
src/redux/store.ts
src/redux/thunks/listeners/shouldStopKustomizeDryRunListener.ts
src/redux/thunks/updateFileEntry.ts

Improves handling of overlays during dry-runs

---

electron/app/services/cloud/authenticator.ts
electron/app/services/cloud/client-config.ts
electron/app/services/cloud/synchronizer.ts
package-lock.json
package.json

This PR adds client data to synchronizer instances. Part of https://github.com/kubeshop/monokle-saas/issues/1904.
Requires https://github.com/kubeshop/monokle-core/pull/593.
- As above.
- As above.
- E2E - either by looking into API logs (e.g. run locally) or with a tool such Charles or WireShark to see `User-Agent` send correctly.
- None.

Add client data to synchronizer instances

---

electron/app/services/cloud/policy.ts
electron/app/services/cloud/project.ts

This PR fixes invalid synchronizer calls.
Issue introduced in https://github.com/kubeshop/monokle/pull/4206 with deps update.
- As above.
- As above.
- `npm run build`
- None.

fix: fix synchronizer invalid calls

---

src/components/organisms/TemplateExplorer/TitleBarDescription/TitleBarDescription.tsx

This PR...
- Fix typo
- A typo in template's title bar
N/A
N/A

fix: typo in Template's Title bar
