src/components/organisms/GitPane/FileList.tsx, src/components/organisms/GitPane/GitPane.styled.tsx, src/components/organisms/GitPane/GitPane.tsx, src/components/organisms/PageHeader/PageHeader.tsx, src/components/organisms/PaneManager/PaneManagerLeftMenu.styled.tsx
- Changed files count badge refactor
- Remove possibility to select all
- Rename `Commit` to `Git`
- Monitor `.git` folder after initializing repo
=> fix: create local branch

src/components/organisms/GitPane/GitPane.tsx
=> feat: hide bottom actions if git repo is not found

electron/app/git/git.ts, package-lock.json, src/redux/services/gitFolderMonitor.ts
- Try/catch for fetching git repo
- Remove changed files if git repo is not found
=> fix: remove changed files if there is not git repo

electron/app/git/git.ts, src/components/organisms/GitPane/FileList.tsx, src/models/git.ts, src/redux/git/git.slice.ts, src/redux/reducers/main.ts, src/utils/git.ts
- Improve selecting changed file
- Fix changed file gitPath/path/showingPath
- Fix stage/unstage functionality
=> fix: changed files paths properties

src/utils/git.ts
=> fix: displayPath

src/components/molecules/NotificationMarkdown/TelemetryButtons.tsx, src/components/organisms/PageHeader/HelpMenu.tsx, tests/base.test.ts, tests/git.test.ts
=> test: telemetry/walk through

electron/app/git/git.ts, src/components/molecules/SectionRenderer/SectionRenderer.tsx, src/models/navigator.ts, src/navsections/HelmChartSectionBlueprint/HelmChartSectionBlueprint.ts, src/redux/reducers/main.ts, src/redux/services/fileEntry.ts, src/redux/services/fileMonitor.ts, src/redux/thunks/multiplePathsAdded.ts, src/redux/thunks/multiplePathsChanged.ts, src/redux/thunks/updateFileEntry.ts, src/redux/thunks/updateResource.ts, src/utils/git.ts, tests/git.test.ts
- `multiplePathsRemoved` sync redux action
- Git test
- Updating fileMap accordingly
- Remove unnecessary git requrests
=> fix: file map update

src/components/molecules/BranchSelect/BranchSelect.tsx, src/constants/constants.ts, src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenu.tsx, src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenuWrapper.tsx
- On git checkout, if there is an error, open terminal and run git checkout cmd
=> feat: on git checkout error show terminal cmd

docs/resource-crds.md, mkdocs.yml
=> docs: initial page for CRDs

src/components/organisms/GitPane/FileList.tsx, src/components/organisms/GitPane/GitPane.tsx, src/models/git.ts, src/utils/git.ts
- Show original content of a git changed file
=> fix: show original content of git changed file

src/components/organisms/GitOpsView/GitView.tsx
=> fix: disable git diff editor validation

src/models/integrations.ts
=> chore: add learn more url for CRDs

src/redux/reducers/main.ts
=> fix: reset filters when switching projects

package-lock.json, package.json
=> chore: update electron version to 19.1.1

src/redux/services/fileMonitor.ts, src/redux/thunks/setRootFolder.ts
=> fix: show removed file in git pane

src/components/organisms/GitOpsView/GitView.tsx
=> fix: make git diff editor read-only

src/components/organisms/GitPane/GitPane.styled.tsx, src/components/organisms/GitPane/GitPane.tsx
=> fix: show git pane header anytime

src/components/organisms/GitPane/BottomActions.tsx, src/components/organisms/GitPane/CommitModal.tsx, src/components/organisms/GitPane/GitPane.styled.tsx, src/components/organisms/GitPane/GitPane.tsx
=> feat: success modals after commit/push

electron/app/git/git.ts, src/components/organisms/GitPane/BottomActions.tsx, src/components/organisms/GitPane/GitPane.tsx
=> feat: disable publish & push

electron/app/git/git.ts, electron/app/git/ipc.ts, src/components/molecules/BranchSelect/BranchSelect.tsx, src/components/molecules/BranchSelect/CreateBranchInput.tsx, src/components/organisms/GitPane/BottomActions.styled.tsx, src/components/organisms/GitPane/BottomActions.tsx, src/components/organisms/GitPane/FileList.styled.tsx, src/components/organisms/PageHeader/PageHeader.tsx, src/constants/constants.ts, src/constants/tooltips.tsx, src/models/git.ts, src/redux/git/git.slice.ts, src/redux/services/fileMonitor.ts, src/redux/services/gitFolderMonitor.ts, src/redux/thunks/setRootFolder.ts, src/utils/git.ts, src/utils/terminal.ts
- Get commits ahead/behind
- Have a sync button for pulling/pushing changes
- Dropdown for fetch/pull/push actions
=> feat: git sync cta

src/components/molecules/FormEditor/FormEditor.tsx, src/components/organisms/ErrorPage/ErrorPage.styled.tsx
=> fix: add error boundary for form

src/kindhandlers/index.ts, src/utils/crds.ts
=> fix: save crds based on group & name

src/components/molecules/FormEditor/FormEditor.tsx, src/components/organisms/ErrorPage/ErrorPage.tsx
=> fix: conditional button back error boundary

package-lock.json, src/components/organisms/ActionsPane/ActionsPane.styled.tsx, src/components/organisms/ActionsPane/ActionsPane.tsx, src/components/organisms/PaneManager/PaneManagerSplitView.tsx
=> fix: monaco editor hide scroll

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 1.11.0

src/components/molecules/BranchSelect/BranchTable.tsx
=> fix: local branches by default

src/components/organisms/PaneManager/PaneManager.tsx
=> fix: double scroll

electron/app/git/git.ts, electron/app/git/ipc.ts, src/components/organisms/GitCloneModal/GitCloneModal.tsx
=> fix: handle clone errors

src/redux/reducers/appConfig.ts
=> fix: set left menu selection to file explorer when opening project

src/redux/services/fileEntry.ts
=> fix: get new content of the file when modifying resource

src/components/organisms/CompareModal/ComparisonList.styled.tsx
=> refactor: highlight row for comparing resources

.github/workflows/monokle-ui-tests.yml
=> disable UI tests on PRs

src/components/molecules/ContextMenu/ContextMenu.tsx, src/components/molecules/SectionRenderer/ItemRenderer/ItemRenderer.tsx, src/components/molecules/SectionRenderer/ItemRenderer/styled.tsx, src/components/organisms/FileTreePane/CreateNode.tsx, src/components/organisms/FileTreePane/TreeItem.tsx, src/components/organisms/FileTreePane/styled.tsx, src/components/organisms/FileTreePane/types.tsx, src/components/organisms/GitPane/FileList.tsx, src/hooks/fileTreeHooks/useFileSelect.tsx, src/navsections/HelmChartSectionBlueprint/HelmChartContextMenu.tsx, src/navsections/HelmChartSectionBlueprint/HelmChartContextMenuWrapper.tsx, src/navsections/HelmChartSectionBlueprint/HelmChartQuickAction.tsx, src/navsections/HelmChartSectionBlueprint/HelmChartSectionBlueprint.ts, src/navsections/KustomizationSectionBlueprint/KustomizationContextMenu.tsx, src/navsections/KustomizationSectionBlueprint/KustomizationContextMenuWrapper.tsx, src/navsections/KustomizationSectionBlueprint/KustomizationQuickAction.tsx, src/navsections/KustomizationSectionBlueprint/KustomizationSectionBlueprint.ts
- Filter out kustomizations/helms/files that are not contained in the filtered file/folder
=> fix: filtered kustomizations/helms/files

src/components/organisms/ValidationPane/CRDsSchemaValidation/CRDItem.styled.tsx, src/components/organisms/ValidationPane/CRDsSchemaValidation/CRDItem.tsx, src/components/organisms/ValidationPane/CRDsSchemaValidation/CRDsSchemaValidation.tsx
=> feat: modal for creating new resource from CRD

README.md
=> fix: remove unnecessary p closing tag

README.md
=> fix: use div

src/components/molecules/FormEditor/FormEditor.styled.tsx, src/components/organisms/ActionsPane/ActionsPane.tsx, src/components/organisms/FileTreePane/TreeItem.tsx, src/components/organisms/FileTreePane/types.tsx
=> fix: form editor scrollbar

src/components/molecules/Logs/Logs.styled.ts
=> fix: logs scrollbar

src/components/organisms/ActionsPane/ActionsPane.tsx, src/components/organisms/ActionsPane/ActionsPaneHeader.tsx, src/components/organisms/ActionsPane/Diff/Diff.tsx, src/components/organisms/ActionsPane/InstallDeploy/InstallDeploy.tsx, src/hooks/resourceHooks/index.ts, src/hooks/resourceHooks/useDiff.ts, src/hooks/resourceHooks/useInstallDeploy.ts, src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenu.tsx
- Make useDiff / useInstallDeploy hook
- Add Deploy/Diff in Resource Context Menu
- Disable deploy in cluster mode
=> feat: deploy diff actions

src/components/organisms/FileTreePane/FileTreePane.tsx
=> refactor: collapse all folders but root

src/components/organisms/FileTreePane/TreeItem.tsx, src/components/organisms/GitPane/FileList.tsx, src/utils/files.ts
- Possibility to discard changes ( restore deleted file / delete added file / restore modified file to original content )
=> feat: discard changes for unstaged files

src/redux/git/git.slice.ts, src/redux/thunks/setRootFolder.ts
This PR fixes https://github.com/kubeshop/monokle/issues/2556
-
-
-
-
=> refactor: async git tasks on setRootFolder

src/components/organisms/ActionsPane/ActionsPaneHeader.styled.tsx, src/components/organisms/ActionsPane/ActionsPaneHeader.tsx, src/components/organisms/ActionsPane/Diff/Diff.tsx, src/components/organisms/ActionsPane/InstallDeploy/InstallDeploy.tsx, src/components/organisms/ActionsPane/Restart/Restart.tsx, src/components/organisms/ActionsPane/Scale/Scale.tsx
- Refactor styling of the action buttons for editor pane
- Change icons for left/right arrows
=> refactor: actions pane buttons

src/components/organisms/FileTreePane/FileTreePane.tsx, src/hooks/fileTreeHooks/useHighlightNode.ts
- Improve expanding folders for file tree
=> refactor: improve set expanded folders

src/redux/git/git.slice.ts, src/redux/reducers/main.ts, src/redux/thunks/setRootFolder.ts
=> fix: set repo/changed files to initial

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 1.11.1

src/navsections/ImagesSectionBlueprint/ImageOutgoingResourcesPopover.tsx
=> fix: image outgoing resources refs

src/components/organisms/ValidationPane/CRDsSchemaValidation/CRDsSchemaValidation.styled.tsx, src/components/organisms/ValidationPane/CRDsSchemaValidation/CRDsSchemaValidation.tsx
=> feat: register CRDs from files

src/components/organisms/LazyDrawer/LazyDrawer.styled.tsx, src/components/organisms/LazyDrawer/LazyDrawer.tsx
=> feat: add close icon to drawers

src/components/organisms/ActionsPane/ActionsPane.tsx, src/kindhandlers/common/formLoader.ts
This PR...
- Removes metadata tab and adds into form tab
-
-
=> feat: Remove Metadata tab, bring back to Form tab

src/components/molecules/CommandPreview/CommandLabel.styled.tsx, src/components/molecules/CommandPreview/CommandLabel.tsx, src/components/molecules/CommandPreview/PreviewSavedCommand.tsx, src/components/molecules/CommandPreview/SaveCommand.tsx, src/components/organisms/CompareModal/ResourceSetSelector/CommandSelect/CommandSelect.tsx, src/components/organisms/CompareModal/ResourceSetSelector/CommandSelect/index.ts, src/components/organisms/CompareModal/ResourceSetSelector/ResourceSetSelector.tsx, src/components/organisms/CompareModal/ResourceSetSelector/ResourceSetTypeSelect.tsx, src/components/organisms/PageHeader/ClusterSelection.styled.tsx, src/models/appconfig.ts, src/navsections/ImagesSectionBlueprint/ImagesSectionNameDisplay.tsx, src/redux/compare/selectors.ts, src/redux/compare/state.ts, src/redux/compare/utils.ts, src/redux/services/compare/fetchResources.ts, src/redux/services/projectConfig.ts
This PR...
- logic for comparing command previews
- logic for deleting saved commands
- improved styling
- persisting of saved commands
=> feat: Compare Command Previews & Delete saved commands

src/components/organisms/ActionsPane/ActionsPaneHeader.styled.tsx, src/hooks/resourceHooks/useInstallDeploy.ts
=> fix: enable deploy in cluster mode

src/components/molecules/FormEditor/FormArrayFieldTemplate.tsx, src/components/molecules/FormEditor/FormEditor.tsx, src/components/molecules/FormEditor/FormObjectFieldTemplate.tsx
This PR...
- Makes the form buttons visible again
-
-
=> fix: bring form buttons back

src/components/organisms/CompareModal/ResourceSetSelector/GitSelect/GitCommitSelect.tsx, src/components/organisms/CompareModal/ResourceSetSelector/ResourceSetSelectColor.styled.tsx, src/utils/git.ts
=> feat: add git commit create date

src/components/molecules/CommandPreview/SaveCommand.tsx
=> chore: increase width of Saved Command modal

src/components/molecules/CheckedResourcesActionsMenu/CheckedResourcesActionMenu.styled.tsx, src/components/molecules/SectionRenderer/ItemRenderer/styled.tsx, src/components/molecules/SectionRenderer/styled.tsx, src/components/organisms/FileTreePane/styled.tsx, src/components/organisms/GitPane/FileList.tsx, src/components/organisms/SearchPane/styled.tsx, src/styles/Colors.ts
=> refactor: highlight/selection colors

electron/app/commands.ts, src/components/organisms/ValidationPane/CRDsSchemaValidation/CRDsSchemaValidation.tsx
=> fix: selecting files on macOS

src/components/atoms/StyledComponents/SecondaryButton.tsx, src/components/organisms/ActionsPane/ActionsPaneHeader.tsx, src/components/organisms/ActionsPane/Diff/Diff.tsx, src/components/organisms/ActionsPane/InstallDeploy/InstallDeploy.tsx, src/components/organisms/ActionsPane/Restart/Restart.tsx, src/components/organisms/ActionsPane/Scale/Scale.tsx, src/constants/constants.ts
- Styling for Editor pane actions
=> fix: styling for editor pane actions

electron/app/createWindow.ts, electron/app/ipc/ipcListeners.ts, electron/app/utils.ts, src/components/organisms/PageHeader/ProjectSelection.tsx, src/redux/reducers/appConfig.ts
- Kill all terminals when switching a project with confirmation
=> feat: kill terminals

src/redux/reducers/main.ts, src/redux/services/fileEntry.ts, src/redux/thunks/updateMultipleResources.ts
=> fix: check policies errors on add/update

src/components/organisms/ValidationPane/OpenPolicyAgent/ValidationOpenPolicyAgentTable.tsx
=> fix: validation pane scroll

src/App.tsx, src/feature-flags.json, src/utils/features.tsx
=> chore: add feature flag for TwoZero

src/redux/thunks/setRootFolder.ts
- Change `isGitFolder` to `isGitRepo`
=> fix: isGitRepo property

src/models/appstate.ts
=> chore: remove unused type

package-lock.json, package.json, shared/.gitignore, shared/package-lock.json, shared/package.json, shared/src/index.ts, shared/src/plugin.ts, shared/src/repository.ts, shared/tsconfig.json, shared/tsconfig.node.json, shared/vite-env.d.ts, shared/vite.config.ts
=> feat: created lib for shared logic between main & renderer

package-lock.json, package.json, shared/package-lock.json, shared/package.json
=> feat: hot reload for shared lib

shared/.gitignore
This PR...
- added the .gitignore file from the new shared folder in 2.0 branch so we can easily switch between main and 2.0
-
-
-
=> chore: add shared folder + gitignore on main

electron/app/git/git.ts, electron/app/git/ipc.ts, src/components/organisms/FileTreePane/TreeItem.tsx, src/models/git.ts
This PR...
Menu on file explorer
-
-
=> feat(menu): open on github

.github/workflows/add-issues-to-project.yaml
=> feat: add CREATE_ISSUE_TOKEN

electron/app/createWindow.ts
=> fix: dev tools

src/redux/services/resource.ts
=> fix: parsing yaml documents with comment before

src/redux/services/resource.ts
=> fix: parse multi-doc comment before

src/components/organisms/CompareModal/ComparisonList.styled.tsx, src/components/organisms/CompareModal/ComparisonList.tsx, src/components/organisms/CompareModal/ResourceList.styled.tsx, src/components/organisms/CompareModal/ResourceList.tsx, src/components/organisms/CompareModal/types.ts, src/redux/compare/selectors.ts, src/redux/services/compare/compareResources.ts
- The possibility to compare resources between different namespaces
=> feat: possiblity to compare namespaces

src/redux/services/compare/compareResources.ts
- Make the other operations work with the new comparison of all the namespaces
=> fix: compare operations

src/App.tsx, src/components/molecules/CommandPreview/CommandLabel.styled.tsx, src/components/molecules/CommandPreview/CommandLabel.tsx, src/components/molecules/CommandPreview/SaveCommand.tsx, src/components/molecules/CommandPreview/SaveEditModal.tsx, src/components/organisms/SaveEditCommandModal/SaveEditCommandModal.tsx, src/components/organisms/SaveEditCommandModal/index.ts, src/components/organisms/index.ts, src/models/ui.ts, src/redux/initialState.ts, src/redux/reducers/ui.ts
- Possibility to edit a saved command
- Show an error when trying to save a command with a label that is already used
- Show alert for updating/saving commands
=> feat: edit saved commands

src/redux/services/fileEntry.ts, src/redux/thunks/setRootFolder.ts
- Reading the content for folders
=> fix: reading content of folder

electron/app/commands.ts, src/components/organisms/SaveEditCommandModal/SaveEditCommandModal.tsx, src/redux/services/previewCommand.ts, src/utils/commands/execute.ts
=> refactor: set CWD of saved command to current project path

src/components/organisms/NewResourceWizard/NewResourceWizard.tsx, src/hooks/useFolderTreeSelectData.ts
=> feat: use folder tree select data hook

src/components/organisms/CompareModal/ResourceSetSelector/LocalSelect/LocalSelect.tsx, src/components/organisms/CompareModal/ResourceSetSelector/LocalSelect/index.ts, src/components/organisms/CompareModal/ResourceSetSelector/ResourceSetSelector.tsx, src/components/organisms/CompareModal/ResourceSetSelector/ResourceSetTypeSelect.tsx, src/components/organisms/NewResourceWizard/NewResourceWizard.tsx, src/redux/compare/state.ts, src/redux/compare/utils.ts, src/redux/services/compare/fetchResources.ts
- Possibility to compare between subfolders of the current project
=> feat: compare sub folders

src/components/organisms/FileTreePane/CreateNode.tsx, src/components/organisms/FileTreePane/TreeItem.tsx
=> fix: tooltip with absolute path only over name

.eslintrc.js, package.json
=> fix: eslint imports on shared

src/utils/fileExplorer.ts
=> fix: key warning

electron/app/git/git.ts, package-lock.json, src/components/atoms/TableSelect/TableSelect.tsx, src/components/organisms/GitPane/BottomActions.tsx, src/components/organisms/GitPane/GitPane.styled.tsx, src/components/organisms/GitPane/GitPane.tsx, src/components/organisms/GitPane/RemoteInput.tsx, src/models/git.ts, src/redux/git/git.slice.ts, src/redux/thunks/setRootFolder.ts, src/styles/Colors.ts
=> fix: git auth needed

src/components/organisms/CompareModal/CompareModal.styled.tsx, src/components/organisms/CompareModal/CompareModal.tsx
=> refactor: bring back resource selector at all times

src/components/organisms/CompareModal/ResourceList.tsx
=> feat: group resource list by kind and api version group

src/components/organisms/CompareModal/ResourceList.tsx
=> fix: resource list duplicate keys

src/navsections/HelmChartSectionBlueprint/HelmChartSectionBlueprint.ts, src/navsections/HelmChartSectionBlueprint/RootHelmChartsSectionBlueprint.ts, src/navsections/KustomizationSectionBlueprint/KustomizationSectionBlueprint.ts, src/navsections/KustomizePatchSectionBlueprint/KustomizePatchSectionBlueprint.ts, src/redux/selectors.ts, src/redux/thunks/applyMultipleResources.ts, src/redux/thunks/runPreviewConfiguration.ts
=> fix: fix kubeConfig mismatch

src/components/organisms/HotKeysHandler/HotKeysHandler.tsx, src/components/organisms/PageHeader/PageHeader.tsx
=> refactor: disconnect cluster on logo click

src/components/molecules/Walkthrough/content/newReleaseFeatures.ts, src/components/molecules/Walkthrough/content/novice.ts, src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx, src/models/walkthrough.ts
- Add corresponding tooltips for the next release
- Temporary hide the syntax tooltip
=> feat: release tooltips

electron/app/git/git.ts, electron/app/ipc/ipcListeners.ts, electron/app/utils.ts, src/components/molecules/FormEditor/FormEditor.tsx, src/components/molecules/ResourceRefsIconPopover/RefsPopoverContent.tsx, src/components/molecules/ValidationErrorsPopover/ErrorsPopoverContent.tsx, src/components/organisms/CreateProjectModal/CreateProjectModal.tsx, src/components/organisms/Dashboard/Tableview/InfoTab.tsx, src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx, src/components/organisms/QuickSearchActions/QuickSearchActions.tsx, src/components/organisms/TemplateModal/TemplateModal.tsx, src/components/organisms/ValidationPane/ValidationOverview/ValidationCard.tsx, src/redux/compare/slice.ts, src/redux/forms/slice.ts, src/redux/reducers/main.ts, src/redux/services/preview.ts, src/redux/services/previewCommand.ts, src/redux/thunks/applyFile.ts, src/redux/thunks/applyHelmChart.ts, src/redux/thunks/applyResource.ts, src/redux/thunks/previewCluster.ts, src/redux/thunks/previewHelmValuesFile.ts, src/redux/thunks/previewKustomization.ts, src/redux/thunks/runPreviewConfiguration.ts, src/redux/thunks/saveUnsavedResources.ts, src/redux/thunks/setRootFolder.ts, src/utils/shell.ts, src/utils/telemetry.ts
=> fix trackEvent method, rename events and add missing ones

src/components/organisms/StartProjectPane/StartProjectPage.styled.tsx
=> refactor: start project styling

src/components/organisms/Dashboard/Header/Header.tsx, src/components/organisms/Dashboard/Tableview/Drawer.tsx, src/components/organisms/Dashboard/Tableview/TableCells.tsx, src/components/organisms/DashboardPane/DashboardPane.tsx, src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx, src/components/organisms/StartProjectPane/RecentProjectsPage.tsx, src/components/organisms/StartProjectPane/StartProjectPage.tsx, src/redux/dashboard/slice.ts, src/utils/telemetry.ts
=> chore: add dashboard telemetry

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 1.13.0

src/components/molecules/NotificationMarkdown/styled.tsx
=> fix: notification markdown "pre"

src/components/organisms/PageHeader/CreateProject.tsx, src/components/organisms/PageHeader/PageHeader.tsx, src/utils/telemetry.ts
=> feat: add new tracking events

src/utils/files.ts
=> fix: create file

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 1.13.1

src/redux/services/clusterResourceWatcher.ts
=> fix: handle exit preview error

src/redux/reducers/appConfig.ts, src/redux/services/projectConfig.ts
=> fix: delete preview config custom option

src/constants/constants.ts
This PR...
- The list of K8s schemas supported
=> chore: adding support for K8s 1.26.0

src/components/organisms/SettingsManager/SettingsManager.tsx, src/redux/services/monitorKubeConfig.ts
=> chore: fix kubeconfig watcher

src/navsections/HelmChartSectionBlueprint/HelmChartContextMenu.tsx, src/navsections/HelmChartSectionBlueprint/HelmChartContextMenuWrapper.tsx
=> fix: rename helm value file

resources/schemas/1.26.0.json
=> fix: tests by adding 1.26 k8s schema

electron/app/ipc/ipcListeners.ts, electron/app/utils.ts, src/components/organisms/UpdateNotice/UpdateNotice.tsx, src/utils/electronStore.ts, src/utils/telemetry.ts
=> Refactor: app udates logic

src/components/organisms/SettingsManager/SettingsManager.tsx, src/components/organisms/SettingsManager/styled.tsx
=> chore: change text of cluster proxy setting

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 1.13.2

src/utils/shell.ts, src/utils/telemetry.ts
=> chore: track clicks of external doc links

package.json
=> chore: add requestedExecutionLevel for Windows build

src/components/molecules/Monaco/Monaco.tsx, src/components/organisms/FileTreePane/CreateNode.tsx, src/constants/constants.ts
=> feat: support additional files

src/redux/reducers/main.ts, src/redux/services/clusterResourceWatcher.ts
=> feat: add bulk operation for resource updates

src/components/organisms/Dashboard/Dashboard.tsx, src/components/organisms/Dashboard/Header/Header.tsx, src/components/organisms/Dashboard/Overview/Activity.tsx, src/components/organisms/Dashboard/Overview/InventoryInfo.tsx, src/components/organisms/Dashboard/Overview/Status.tsx, src/components/organisms/DashboardPane/DashboardPane.tsx, src/redux/dashboard/slice.ts, src/redux/dashboard/state.ts, src/redux/services/clusterResourceWatcher.ts, src/redux/services/preview.ts, src/redux/thunks/previewCluster.ts
=> feat: handle namespace for cluster dashboard

src/components/organisms/PageHeader/PageHeader.styled.tsx
=> fix: notifications badge

src/models/appconfig.ts, src/redux/reducers/appConfig.ts, src/redux/services/preview.ts, src/redux/thunks/startClusterPreview.ts
=> fix: switching namespace with proxy enabled

electron/app/initKubeconfig.ts, src/components/organisms/Dashboard/Header/Header.tsx, src/components/organisms/LocalResourceDiffModal/LocalResourceDiffModal.tsx, src/models/appconfig.ts, src/redux/services/monitorKubeConfig.ts, src/utils/kubeclient.ts
=> catch getKubeAccess errors

src/components/organisms/PaneManager/PaneManagerSplitView.tsx
This PR fixes https://github.com/kubeshop/monokle/issues/2994
-
-
-
-
=> fix: add loading skeleton for dashboard reloading

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 1.13.3

docs/cluster-issues.md, mkdocs.yml
=> docs: troubleshooting cluster connection

src/components/molecules/Logs/Logs.styled.ts, src/components/organisms/FileTreePane/styled.tsx, src/index.css
This PR...
- set the Inter font family as the default font 
-
-
-
=> fix: switch to Inter font family 

src/components/molecules/InputTags/InputTags.tsx, src/components/molecules/ResourceFilter/ResourceFilter.tsx, src/redux/thunks/previewCluster.ts
- Fetch cluster resources based on the filter kinds
Before applying kind filters
After applying a kind filter
=> feat: fetch cluster resources by kind filters

.github/workflows/monokle-publish-downloads.yml, .github/workflows/monokle-publish-updater.yml, .github/workflows/monokle-publish.yml, craco.config.js, package-lock.json, package.json, src/navsections/K8sResourceSectionBlueprint/K8sResourceSectionBlueprint.ts, src/navsections/K8sResourceSectionBlueprint/ResourceKindSectionBlueprint.ts, src/redux/reducers/appConfig.ts
=> quick performance fix + sentry webpack plugin

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 1.13.4

src/components/molecules/TemplateFormRenderer/TemplateFormRenderer.tsx, src/components/organisms/DashboardPane/DashboardPane.tsx, src/components/organisms_new/TemplateExplorer/TemplateForm/TemplateForm.tsx
- Possibility to go to previous step in template form
=> feat: template form back button

package.json
=> fix: windows uac prompt

src/components/organisms/NavigatorPane/NavigatorPane.tsx
=> refactor: update navigator title

src/components/organisms/PageHeader/K8sVersionSelection.tsx, src/components/organisms/PageHeader/PageHeader.tsx
=> refactor: default k8s version change

package-lock.json, package.json, src/components/organisms_new/LearnPage/LearnPage.tsx, src/components/organisms_new/LearnPage/WalkThroughModal.tsx, src/components/organisms_new/LearnPage/index.ts, src/components/organisms_new/StartPage/StartPage.tsx, src/components/organisms_new/index.ts, src/hooks/useStartPageOptions.tsx, src/redux/reducers/ui.ts, src/shared/constants/walkthrough.ts, src/shared/models/ui.ts
This PR...
-updated LearnPage component based on the latest `monokle-core` updates 
-
-
-
=> fix: update LearnPage component

src/hooks/useNamespaces.ts
=> fix use namespaces

src/shared/models/k8sResource.ts, src/shared/models/origin.ts, src/shared/models/preview.ts, src/shared/models/selection.ts
=> refactor type guards for resource / origin / selection / preview

src/redux/reducers/main/mainSlice.ts, src/redux/services/fileEntry.ts, src/redux/thunks/multiplePathsAdded.ts, src/redux/thunks/multiplePathsChanged.ts, src/redux/thunks/replaceImageTag.ts, src/redux/thunks/updateFileEntry.ts, src/redux/thunks/updateMultipleResources.ts, src/redux/validation/validation.listeners.tsx
=> fix: incremental validation triggers for file actions

src/utils/workerify.ts
=> feat: workerify utility

src/components/organisms_new/ExplorerPane/FilePane/FilePane.tsx, src/redux/reducers/main/selectionReducers.ts
=> fix: resource & file highlights

src/redux/validation/validation.services.ts, src/redux/validation/validation.thunks.ts, src/redux/validation/validation.worker.ts, src/redux/validation/validation.worker.types.ts, tsconfig.json
=> feat: run validation using web worker

src/components/molecules/ResourceRefsIconPopover/ResourceRefsIconPopover.tsx
=> chore: remove unsatisfied refs icon

package-lock.json, package.json, src/redux/validation/validation.listeners.tsx, src/redux/validation/validation.thunks.ts, src/redux/validation/validation.worker.ts, src/shared/models/validation.ts, src/utils/objects.ts
=> fix: validation for all resource storages

src/components/organisms/Dashboard/Tableview/ErrorCell.tsx, src/components/organisms/Dashboard/Tableview/TableCells.tsx
=> fix cluster dashboard error icon

src/components/organisms_new/PaneManager/activities.tsx
=> fix: reorder activities

package-lock.json, package.json, src/components/organisms_new/ExplorerPane/ExplorerPane.tsx, src/components/organisms_new/ValidationSettings/ValidationOpenPolicyAgent/ValidationLevelSelect.styled.tsx, src/components/organisms_new/ValidationSettings/ValidationOpenPolicyAgent/ValidationLevelSelect.tsx, src/components/organisms_new/ValidationSettings/ValidationOpenPolicyAgent/ValidationOpenPolicyAgent.tsx, src/components/organisms_new/ValidationSettings/ValidationOpenPolicyAgent/ValidationOpenPolicyAgentTable.styled.tsx, src/components/organisms_new/ValidationSettings/ValidationOpenPolicyAgent/ValidationOpenPolicyAgentTable.tsx, src/components/organisms_new/ValidationSettings/ValidationOpenPolicyAgent/useOpenPolicyAgentTable.tsx, src/constants/tooltips.tsx, src/redux/validation/validation.listeners.tsx, src/redux/validation/validation.selectors.ts, src/redux/validation/validation.slice.ts, src/shared/models/validation.ts
- Possibility to set an OPA rule as error/warning
- Make toggle error/plugin work again
- Accordion default collapse file explorer
=> feat: configure errors warnings

src/components/organisms_new/ValidationPane/ValidationPane.tsx, src/redux/validation/validation.slice.ts, src/redux/validation/validation.worker.ts
=> feat: validation overview loading

src/components/organisms_new/ExplorerPane/AccordionPanel/AccordionPanel.tsx
=> fix: accordion height

src/components/organisms/LocalResourceDiffModal/LocalResourceDiffModal.tsx
=> fix: disable namespaces for which the resource doesn't exist

src/redux/dashboard/slice.ts
=> fix: close table drawer when changing namespace

.github/workflows/monokle-build-nightly.yml, .github/workflows/monokle-publish-test.yml
=> fix: solve nightly build issue

src/components/atoms/StyledComponents/TitleBarWrapper.tsx, src/components/organisms/Dashboard/Overview/Status.styled.tsx
=> fix: dashboard status box

src/components/molecules/ResourceFilter/ResourceFilter.tsx, src/components/organisms/NavigatorPane/NavigatorPane.tsx, src/components/organisms/PageHeader/ClusterSelection.tsx, src/navsections/K8sResourceSectionBlueprint/K8sResourceSectionEmptyDisplay.tsx
=> fix: get started actions

src/redux/git/git.slice.ts
=> fix: loading when changing branches

src/components/organisms_new/ExplorerPane/FilePane/FilePane.tsx
=> fix: FilePane title bar buttons

src/components/organisms_new/PaneManager/activities.tsx
=> feat: validation problems count badge

electron/app/ipc/ipcListeners.ts, package-lock.json, package.json
=> fix: killing terminal session for windows

src/components/organisms/NavigatorPane/NavigatorPane.tsx
=> fix: resizing resource filters

src/components/organisms_new/PaneManager/PaneManagerLeftMenu.tsx
=> fix: background-color

src/components/molecules/Monaco/Monaco.tsx, src/components/molecules/Monaco/useDebouncedCodeSave.ts, src/redux/reducers/main/mainSlice.ts, src/redux/services/resource.ts, src/redux/thunks/updateMultipleResources.ts, src/redux/thunks/updateResource.ts
fixed debounce save from Monaco + updateResource and updateMultipleResources thunks
=> fix: saving resources

src/components/organisms/Dashboard/Dashboard.tsx, src/components/organisms/Dashboard/Overview/Overview.styled.tsx, src/components/organisms/Dashboard/Overview/Overview.tsx, src/components/organisms/Dashboard/Overview/Status.styled.tsx
=> chore: cluster dashboard updates

src/components/molecules/FormEditor/FormWidgets/NamespaceSelection.tsx
=> fix: unescape if statement

src/components/organisms/NavigatorPane/NavigatorPane.tsx
=> fix: increase the top height

src/components/molecules/BranchSelect/CreateBranchInput.tsx
=> fix: select branch after creation

src/components/molecules/Monaco/Monaco.tsx
=> fix: check undefined object

src/components/organisms_new/ProblemPane/ProblemPane.tsx
=> fix: scroll top when change the problem

src/components/organisms/Dashboard/Overview/Status.tsx, src/components/organisms/Dashboard/Tableview/TableCells.styled.tsx, src/components/organisms/DashboardPane/DashboardPane.tsx, src/shared/models/dashboard.ts
=> fix: change error badges

src/components/organisms/Dashboard/Tableview/ErrorCell.tsx, src/navsections/K8sResourceSectionBlueprint/ResourceKindPrefix.tsx, src/navsections/KustomizationSectionBlueprint/KustomizationPrefix.tsx
=> refactor: show errors first

src/components/molecules/FormEditor/FormEditor.tsx
=> fix: autosave direct when the form event get called

package-lock.json, package.json
=> fix: search validation by ruleId

src/components/organisms_new/StartPage/StartPageHeader.tsx
=> fix: disable search projects auto focus

src/components/organisms_new/ExplorerPane/FilePane/FilePane.tsx
=> feat: icon for creating folder on Files titlebar

src/components/organisms/Dashboard/Dashboard.tsx, src/components/organisms/Dashboard/Tableview/Tableview.tsx
=> fix: handle namespaces change gracefuly for cluster dashboard

package-lock.json, package.json, src/components/organisms_new/TemplateExplorer/TemplateExplorer.styled.tsx, src/components/organisms_new/TemplateExplorer/TemplateExplorer.tsx
=> fix: scrollbar for template explorer

electron/app/ipc/ipcListeners.ts, src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenu.tsx, src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenuWrapper.tsx
=> fix: open shell in pod

src/components/organisms/Dashboard/Tableview/TerminalTab.tsx
=> fix: shell height

src/components/organisms/Dashboard/Tableview/TerminalTab.tsx
=> fix: init only if terminal ref doesn't exist

CHANGELOG.md, package-lock.json
=> chore(release): 2.0.0

package-lock.json, src/components/molecules/NotificationMarkdown/TelemetryButtons.tsx
- Possibility to disable telemetry
=> fix: disable telemetry

src/components/organisms_new/ExplorerPane/ExplorerPane.tsx, src/components/organisms_new/PaneManager/PaneManagerLeftMenu.tsx, src/shared/models/telemetry.ts
- Add tracking of the left menu selection
- Add tracking of the explorer accordions panels selection
-
-
-
=> feat: add new telemetry events

src/components/molecules/SectionRenderer/ItemRenderer/ItemRenderer.tsx, src/components/molecules/SectionRenderer/ItemRenderer/styled.tsx, src/navsections/K8sResourceSectionBlueprint/ResourceKindPrefix.tsx
=> fix: navigation pane ellipsis

src/components/organisms/Dashboard/EmptyDashboard.styled.tsx, src/components/organisms/Dashboard/EmptyDashboard.tsx
=> refactor: change message

src/components/organisms_new/SettingsPane/PluginsManager/PluginManager.styled.tsx, src/components/organisms_new/SettingsPane/PluginsManager/PluginManager.tsx
=> refactor: install button on plugins manager

src/components/organisms/ActionsPane/ActionsPaneHeader.tsx, src/components/organisms/ActionsPane/Restart/Restart.tsx, src/components/organisms/ActionsPane/Scale/Scale.tsx
=> fix: styling of Scale/Restart buttons

src/navsections/K8sResourceSectionBlueprint/ResourceKindPrefix.tsx
=> fix: show/hide namespace tag based on filter

src/components/organisms_new/CreateProjectModal/CreateProjectModal.tsx
=> fix: path exists error when creating project

src/components/molecules/SectionRenderer/ItemRenderer/ItemRenderer.tsx
=> fix: clean item name sign

src/components/organisms_new/TemplateExplorer/TemplateExplorer.styled.tsx, src/components/organisms_new/TemplateExplorer/TemplateForm/TemplateForm.styled.tsx
=> fix: template explorer scrolling

src/components/organisms/NavigatorPane/NavigatorPane.tsx
=> fix: navigator search responsivness

src/components/organisms_new/ExplorerPane/FilePane/FileSystemTree/TreeNode/hooks.tsx
=> fix: creating file

src/redux/selectors/resourceMapSelectors.ts
=> fix: transient resources navigator

src/components/molecules/ModalConfirmWithNamespaceSelect/ModalConfirmWithNamespaceSelect.tsx
=> fix: deploy modal defaults

src/components/organisms_new/ExplorerPane/ExplorerPane.tsx, src/components/organisms_new/PaneManager/PaneManagerLeftMenu.tsx, src/shared/models/telemetry.ts
=> refactor: telemetry events

src/navsections/ImagesSectionBlueprint/ImagesSectionNameDisplay.styled.tsx, src/navsections/ImagesSectionBlueprint/ImagesSectionNameDisplay.tsx
=> refactor: use monokle-core search input

src/components/organisms/PageHeader/ClusterSelection.tsx, src/components/organisms_new/SettingsPane/Settings/Settings.tsx, src/components/organisms_new/SettingsPane/SettingsPane.tsx, src/redux/initialState.ts, src/shared/models/config.ts, src/shared/models/ui.ts
=> fix: cluster configure

src/components/molecules/BranchSelect/CreateBranchInput.tsx, src/components/organisms/GitPane/BottomActions.tsx, src/redux/git/git.slice.ts
=> fix: git publish branch

src/components/molecules/SectionRenderer/ItemRenderer/styled.tsx, src/components/organisms_new/SettingsPane/GlobalSettings/GlobalSettings.styled.tsx, src/components/organisms_new/SettingsPane/GlobalSettings/GlobalSettings.tsx, src/components/organisms_new/SettingsPane/PluginsManager/PluginManager.styled.tsx, src/components/organisms_new/SettingsPane/PluginsManager/PluginManager.tsx, src/components/organisms_new/SettingsPane/Settings/Settings.styled.tsx, src/components/organisms_new/SettingsPane/Settings/Settings.tsx, src/components/organisms_new/SettingsPane/SettingsPane.styled.tsx, src/components/organisms_new/SettingsPane/SettingsPane.tsx, src/components/organisms_new/StartPage/StartPage.styled.tsx
=> refactor: UI/UX

src/redux/thunks/cluster/startClusterConnection.ts
=> fix: change left menu selection only on connect

src/components/organisms_new/SettingsPane/CurrentProjectSettings/CurrentProjectSettings.tsx, src/components/organisms_new/SettingsPane/Settings/Settings.tsx, src/redux/appConfig/appConfig.listeners.ts, src/redux/reducers/ui.ts, src/redux/thunks/cluster/startClusterConnection.ts, src/shared/utils/selectors.ts
=> fix:  looping syncing localState with global state

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 2.0.1

src/App.tsx, src/components/organisms/UpdateNotice/UpdateNotice.styled.tsx, src/components/organisms/UpdateNotice/UpdateNotice.tsx
- Doesn't show popup of restart for patch releases
=> feat: silent patch releases

docs/docs/index.md
=> docs: Add 2.0 Release Notes Blog Post

.github/workflows/mkdocs.yml
=> chore: fix documentation

docs/docs/development.md
=> chore: change documentation

src/components/organisms/ValidationPane/ValidationPane.tsx, src/hooks/usePaneHeight.ts
=> fix: validation pane height

src/components/organisms/BottomPaneManager/BottomPaneManager.tsx, src/redux/appConfig/appConfig.slice.ts, src/redux/reducers/terminal.ts, src/redux/store.ts
=> fix: kill terminals when going to start page

src/components/organisms/TemplateExplorer/TemplateCollapseItem/TemplateCollapseItem.tsx, src/components/organisms/TemplateExplorer/TemplateExplorer.styled.tsx, src/components/organisms/TemplateExplorer/TemplateExplorer.tsx, src/redux/reducers/ui.ts
- Creating a project from a template when there is an active project
- Styling when no template is selected
=> fix: template create project

src/components/organisms/LearnPage/LearnPage.tsx, src/components/organisms/LearnPage/WalkThroughModal.tsx, src/components/organisms/SettingsPane/SettingsPane.tsx, src/components/organisms/StartPage/StartPage.tsx, src/components/organisms/StartPage/StartPageHeader.tsx, src/components/organisms/TemplateExplorer/TitleBarDescription/TitleBarDescription.tsx, src/redux/initialState.ts, src/redux/reducers/ui.ts, src/shared/models/ui.ts
=> fix: broken link

src/components/organisms/TemplateExplorer/CreatedResources/CreatedResources.styled.tsx, src/components/organisms/TemplateExplorer/CreatedResources/CreatedResources.tsx
=> refactor: Done button

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 2.0.2

.github/workflows/monokle-publish-downloads.yml, .github/workflows/monokle-publish-updater.yml, package-lock.json, package.json
=> fix: github actions

package-lock.json, package.json
=> fix: ValidationOverview resizable width

package-lock.json, package.json
=> chore: update

README.md
=> fix: readme icons

package-lock.json, package.json
=> chore: update styled-components

src/redux/validation/validation.thunks.ts
=> fix: show refs on first validation

src/components/organisms/SettingsPane/SettingsPane.styled.tsx, src/components/organisms/SettingsPane/SettingsPane.tsx
=> fix: settings

src/components/organisms/ExplorerPane/ExplorerPane.tsx, src/redux/initialState.ts, src/redux/reducers/ui.ts, src/shared/models/ui.ts
=> feat: redux selected explorer section

src/App.tsx, src/components/atoms/SelectItemImage/SelectItemImage.tsx, src/components/molecules/ResourceFilter/ResourceFilter.tsx, src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/hooks.tsx, src/components/organisms/FileCompareModal/FileCompareModal.styled.tsx, src/components/organisms/FileCompareModal/FileCompareModal.tsx, src/components/organisms/FileCompareModal/index.ts, src/components/organisms/NewResourceWizard/NewResourceWizard.tsx, src/components/organisms/ResourceSetSelector/GitSelect/GitFolderSelect.tsx, src/components/organisms/ResourceSetSelector/LocalSelect/LocalSelect.tsx, src/components/organisms/TemplateExplorer/CreatedResources/SaveToFolderModal.tsx, src/components/organisms/index.ts, src/hooks/useFileSelectOptions.tsx, src/hooks/useFolderTreeSelectData.ts, src/redux/initialState.ts, src/redux/reducers/ui.ts, src/shared/models/ui.ts
=> feat: compare single file

package-lock.json, package.json
=> chore: update monokle/components

src/components/organisms/ExplorerPane/AccordionPanel/AccordionPanel.tsx, src/components/organisms/ExplorerPane/ExplorerPane.tsx, src/components/organisms/ExplorerPane/FilePane/FilePane.tsx, src/components/organisms/ExplorerPane/HelmPane/HelmPane.tsx, src/components/organisms/ExplorerPane/KustomizePane/KustomizePane.tsx, src/components/organisms/PaneManager/activities.tsx
=> fix: disable section + hide git pane in cluster mode

src/components/organisms/SettingsPane/SettingsPane.tsx
=> fix: settings tabs

electron/app/initKubeconfig.ts, src/redux/appConfig/appConfig.listeners.ts, src/redux/appConfig/appConfig.selectors.ts
=> fix: watch global kubeconf and project kubeconf

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 2.0.3

craco.config.js, package-lock.json, package.json
=> chore: update to latest version of validation

craco.config.js, src/components/organisms/Dashboard/Dashboard.tsx, src/components/organisms/Dashboard/Tableview/Drawer.styled.tsx, src/components/organisms/Dashboard/Tableview/ErrorCell.tsx, src/components/organisms/Dashboard/Tableview/Tableview.tsx
=> fix: navigate to error in manifest tab

src/components/molecules/MonacoPlaceholder/MonacoPlaceholder.tsx, src/components/organisms/Dashboard/Overview/Status.styled.tsx, src/components/organisms/Dashboard/Overview/Status.tsx, src/components/organisms/PaneManager/activities.tsx, src/components/organisms/ValidationPane/ValidationPane.styled.tsx, src/components/organisms/ValidationPane/ValidationPane.tsx, src/constants/tooltips.tsx, src/redux/reducers/ui.ts, src/redux/store.ts
=> refactor: on errors/warnings click show validation pane

src/components/organisms/ValidationPane/ValidationPane.styled.tsx, src/components/organisms/ValidationPane/ValidationPane.tsx
=> feat: back to dashboard button

src/components/molecules/ProjectCard/ProjectCard.styled.tsx, src/components/molecules/ProjectCard/ProjectCard.tsx, src/redux/initialState.ts, src/redux/reducers/ui.ts, src/shared/constants/electronStore.ts, src/shared/models/ui.ts
=> feat: show alert when opening project if in cluster mode

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 2.0.4

.github/workflows/monokle-build-nightly.yml, .github/workflows/monokle-publish-downloads.yml, .github/workflows/monokle-publish-test.yml, .github/workflows/monokle-publish-updater.yml, .github/workflows/monokle-publish.yml
=> feat: add rpm binaries to releases

src/components/molecules/ImageDetails/ImageDetails.tsx, src/components/molecules/ImageDetails/ImageTags.tsx, src/components/molecules/SectionRenderer/SectionRenderer.tsx, src/components/molecules/TemplateFormRenderer/TemplateFormRenderer.tsx, src/components/organisms/PaneManager/PaneManager.tsx, src/components/organisms/ReleaseNotes/ReleaseNotes.tsx, src/components/organisms/SettingsPane/PluginsManager/PluginManager.tsx
=> fix: made all skeleton active

src/components/molecules/ResourceGraphTab/ResourceGraphTab.tsx, src/components/molecules/ResourceGraphTab/index.ts, src/components/molecules/index.ts, src/components/organisms/ActionsPane/ActionsPane.tsx
- Integrate resource graph from monkle-core
=> feat: resource graph

src/components/organisms/ResourceSetSelector/ClusterContextSelect.tsx, src/components/organisms/ResourceSetSelector/CommandSelect/CommandSelect.tsx, src/components/organisms/ResourceSetSelector/GitSelect/GitBranchSelect.tsx, src/components/organisms/ResourceSetSelector/HelmSelect/HelmChartSelect.tsx, src/components/organisms/ResourceSetSelector/KustomizeSelect.tsx
=> feat: default open/ auto focus dropdowns in compare

src/components/molecules/ResourceGraphTab/ResourceGraphTab.tsx, src/redux/parsing/parser.thunks.ts, src/redux/validation/validation.thunks.ts, src/utils/resources.ts
- Correct refs for resources on Windows
=> fix: windows kustomization refs

src/redux/parsing/parser.thunks.ts, src/utils/resources.ts
=> fix: refs file path

src/redux/thunks/previewKustomization.ts
=> fix: show alert when no resources are created on preview

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 2.0.5

src/components/organisms/PageHeader/ClusterSelection.tsx, src/components/organisms/SettingsPane/GlobalSettings/GlobalSettings.tsx, src/redux/appConfig/appConfig.slice.ts, src/redux/initialState.ts, src/shared/constants/electronStore.ts, src/shared/models/config.ts
=> fix: remove show cluster selector setting

src/components/molecules/ResourceRefsIconPopover/RefsPopoverContent.tsx
=> fix: select resource on ref link click

src/components/organisms/StartPage/StartPageHeader.tsx
=> fix: duplicated keys

src/components/molecules/Monaco/Monaco.tsx
=> fix: read only kustomize

src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/hooks.tsx
=> fix: is non resource file if the file is excluded

src/components/molecules/Monaco/editorHelpers.ts, src/redux/reducers/main/mainSlice.ts, src/redux/services/resource.ts
=> fix: persist resource refs after live cluster update

src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/hooks.tsx
=> fix: filter on this file

src/components/molecules/ResourceFilter/ResourceFilter.styled.tsx, src/components/molecules/ResourceFilter/ResourceFilter.tsx, src/components/molecules/SectionRenderer/ItemRenderer/ItemRenderer.tsx, src/components/molecules/SectionRenderer/ItemRenderer/styled.tsx, src/components/organisms/ExplorerPane/ExplorerPane.tsx, src/components/organisms/ExplorerPane/HelmPane/HelmPane.tsx, src/components/organisms/ExplorerPane/ImagesPane/ImagesPane.tsx, src/components/organisms/ExplorerPane/KustomizePane/KustomizePane.tsx, src/components/organisms/PaneManager/activities.tsx, src/components/organisms/SettingsPane/PluginsManager/PluginManager.styled.tsx, src/components/organisms/SettingsPane/PluginsManager/PluginManager.tsx, src/components/organisms/SettingsPane/Settings/Settings.tsx, src/constants/constants.ts, src/hooks/menuItemsHooks/useHelpMenuItems.tsx, src/navsections/HelmChartSectionBlueprint/HelmChartContextMenu.tsx, src/shared/models/explorer.ts
=> fix: bugs and improvements

electron/app/menu.ts, src/components/organisms/ActionsPane/ActionsPaneHeader.tsx, src/components/organisms/ExplorerPane/KustomizePane/KustomizePane.tsx, src/components/organisms/HotKeysHandler/HotKeysHandler.tsx, src/redux/thunks/selectFromHistory.ts, src/shared/utils/selectionHistory.ts
=> fix: select from history thunk + selection fix

src/components/organisms/StartPage/StartPage.styled.tsx, src/components/organisms/StartPage/StartPageHeader.styled.tsx, src/components/organisms/StartPage/StartPageHeader.tsx, src/hooks/useStartPageOptions.tsx
=> refactor: start page left menu

package-lock.json, package.json, src/components/molecules/ResourceFilter/ResourceFilter.styled.tsx, src/components/molecules/ResourceFilter/ResourceFilter.tsx, src/components/organisms/NavigatorPane/NavigatorDescription.styled.tsx, src/components/organisms/NavigatorPane/NavigatorDescription.tsx, src/components/organisms/ValidationPane/ValidationPane.tsx, src/redux/validation/validation.initialState.ts, src/redux/validation/validation.slice.ts, src/shared/models/validation.ts
=> feat: validation pane filters

electron/app/git/git.ts
=> fix: open on github remote url

src/components/molecules/Monaco/Monaco.tsx
=> fix: select line number for resource problem

electron/app/menu.ts, src/components/molecules/FormEditor/FormWidgets/ImageSelection.tsx, src/components/molecules/ImageDetails/ImageDetails.tsx, src/components/molecules/Monaco/Monaco.tsx, src/components/molecules/Monaco/useCodeIntel.ts, src/components/molecules/ResourceRefsIconPopover/RefsPopoverContent.tsx, src/components/molecules/ResourceRefsIconPopover/ResourceRefsIconPopover.tsx, src/components/organisms/ExplorerPane/ImagesPane/ImagesPane.tsx, src/components/organisms/ReplaceImageModal/ReplaceImageModal.tsx, src/navsections/ImagesSectionBlueprint/ImagesSectionBlueprint.ts, src/redux/initialState.ts, src/redux/reducers/main/imageListeners.ts, src/redux/reducers/main/imageReducers.ts, src/redux/reducers/main/mainSlice.ts, src/redux/reducers/main/selectionReducers.ts, src/redux/selectors.ts, src/redux/thunks/selectFromHistory.ts, src/shared/models/appState.ts, src/shared/utils/selectionHistory.ts
=> refactor: images map

src/components/molecules/Monaco/Monaco.tsx, src/redux/reducers/main/mainSlice.ts
=> fix: autosaving status

src/components/molecules/CheckedResourcesActionsMenu/CheckedResourcesActionsMenu.tsx, src/components/molecules/FormEditor/FormWidgets/PodSelectorSelection.tsx, src/components/molecules/ResourceDiff/ResourceDiff.tsx, src/components/molecules/ResourceGraphTab/ResourceGraphTab.tsx, src/components/organisms/ActionsPane/ActionsPane.tsx, src/components/organisms/ClusterResourceDiffModal/ClusterResourceDiffModal.tsx, src/components/organisms/Dashboard/Overview/Activity.tsx, src/components/organisms/Dashboard/Overview/InventoryInfo.tsx, src/components/organisms/Dashboard/Overview/Utilization.tsx, src/components/organisms/Dashboard/Tableview/Drawer.tsx, src/components/organisms/Dashboard/Tableview/InfoTab.tsx, src/components/organisms/HotKeysHandler/HotKeysHandler.tsx, src/components/organisms/LocalResourceDiffModal/LocalResourceDiffModal.tsx, src/components/organisms/NavigatorPane/ResourceRenderer/ResourceContextMenu.tsx, src/components/organisms/ReplaceImageModal/ReplaceImageModal.tsx, src/redux/selectors/resourceMapSelectors.ts, src/redux/thunks/applyResource.ts, src/redux/thunks/replaceImageTag.ts, src/redux/thunks/utils.ts
=> refactor: remove full resource map selectors

src/components/organisms/Dashboard/Tableview/Drawer.styled.tsx, src/components/organisms/Dashboard/Tableview/Drawer.tsx, src/components/organisms/LazyDrawer/LazyDrawer.styled.tsx, src/components/organisms/MessageBox/MessageBox.tsx, src/redux/reducers/main/mainSlice.ts, src/redux/services/clusterResourceWatcher.ts, src/redux/thunks/applyResource.ts
=> fix: update cluster resources errors

src/components/molecules/ChangeFiltersConfirmModal/ChangeFiltersConfirmModal.tsx, src/components/molecules/Monaco/Monaco.tsx, src/components/molecules/ProjectCard/ProjectCard.tsx, src/components/organisms/ActionsPane/ActionsPane.tsx, src/components/organisms/ActionsPane/ActionsPaneHeader.tsx, src/components/organisms/FileCompareModal/FileCompareModal.tsx, src/components/organisms/HotKeysHandler/HotKeysHandler.tsx, src/components/organisms/NewResourceWizard/NewResourceWizard.tsx, src/hooks/fileTreeHooks/useFilterByFileOrFolder.tsx, src/hooks/fileTreeHooks/useProcessing.tsx, src/utils/hooks.ts
=> refactor: ref selectors

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 2.0.6

src/components/organisms/ExplorerPane/FilePane/FilePane.tsx, src/components/organisms/ExplorerPane/HelmPane/HelmPane.tsx, src/components/organisms/ExplorerPane/KustomizePane/KustomizePane.tsx, src/components/organisms/ExplorerPane/PreviewConfigurationPane/PreviewConfigurationPane.tsx
=> fix: remove disabled console warning

src/redux/services/projectConfigMonitor.ts
=> fix: duplicate dispatch when open project

src/redux/validation/validation.selectors.ts
=> fix: replaced createSelector with createDeepEqualSelector

src/components/molecules/FormEditor/FormEditor.tsx, src/redux/selectors.ts
=> refactor: selectors

src/redux/appConfig/appConfig.selectors.ts, src/shared/utils/selectors.ts
=> fix: selectors dependencies

src/components/organisms/NavigatorPane/ResourceRenderer/ResourceRenderer.tsx
=> fix: show resource status only in cluster mode

src/components/organisms/ExplorerPane/HelmPane/HelmChartRenderer/HelmChartRenderer.styled.tsx
=> fix: no ellipsis for helm chart name

package-lock.json, package.json, src/index.tsx, src/utils/knownErrors.ts
=> chore: catch known errors

src/redux/thunks/updateResource.ts
=> fix: highlights after editing a kustomization

.eslintrc.js, electron/app/services/cluster/handlers/index.ts, electron/app/services/cluster/handlers/ping.ts, electron/app/services/cluster/ipc.ts, electron/app/utils/ipc.ts, src/redux/cluster/service/ping.ts, src/shared/ipc/cluster.ts, src/shared/ipc/core.ts, src/shared/ipc/index.ts, src/utils/ipc.ts
This PR adds a framework to deal with IPC in a robuust way.
=> feat: add ipc framework

src/components/molecules/ResourcePopover/ResourcePopover.styled.tsx, src/components/molecules/ResourcePopover/ResourcePopover.tsx, src/components/molecules/ResourcePopover/index.ts, src/components/organisms/NavigatorPane/ResourceRenderer/ResourceRenderer.tsx
=> feat: add resource popover

src/components/organisms/GitCloneModal/GitCloneModal.tsx, src/constants/constants.ts
- Change placeholder repo URL
- On tab prefill repo URL
- `Use Monokle Sample Repo` quick action
=> refactor: git clone modal

src/components/organisms/BottomPaneManager/BottomPaneManager.tsx, src/redux/reducers/terminal.ts, src/redux/store.ts
=> fix: listener for removing terminal

src/components/organisms/ExplorerPane/HelmPane/HelmChartRenderer/HelmChartCollapse.tsx, src/components/organisms/ExplorerPane/HelmPane/HelmChartRenderer/HelmChartRenderer.styled.tsx, src/components/organisms/ExplorerPane/HelmPane/HelmChartRenderer/HelmChartRenderer.tsx, src/components/organisms/ExplorerPane/HelmPane/HelmValueRenderer/HelmValueRenderer.styled.tsx, src/components/organisms/ExplorerPane/PreviewConfigurationPane/HelmChartRenderer/HelmChartCollapse.tsx, src/components/organisms/ExplorerPane/PreviewConfigurationPane/HelmChartRenderer/HelmChartRenderer.styled.tsx, src/components/organisms/ExplorerPane/PreviewConfigurationPane/HelmChartRenderer/HelmChartRenderer.tsx, src/components/organisms/ExplorerPane/PreviewConfigurationPane/PreviewConfigurationAdd.tsx, src/components/organisms/ExplorerPane/PreviewConfigurationPane/PreviewConfigurationList.tsx, src/components/organisms/ExplorerPane/PreviewConfigurationPane/PreviewConfigurationPane.tsx, src/components/organisms/ExplorerPane/PreviewConfigurationPane/PreviewConfigurationRenderer/PreviewConfigurationRenderer.styled.tsx, src/components/organisms/PreviewConfigurationEditor/PreviewConfigurationEditor.tsx, src/redux/appConfig/appConfig.slice.ts, src/redux/selectors/helmSelectors.ts, src/redux/services/projectConfig.ts, src/redux/services/projectConfigMonitor.ts, src/redux/thunks/previewConfiguration.ts, src/shared/utils/projectConfig.ts
=> fix: preview configurations

src/redux/reducers/main/mainSlice.ts, src/redux/reducers/main/selectionReducers.ts
=> fix: duplicate extra reducer

electron/app/ipc/ipcListeners.ts, src/shared/utils/telemetry.ts
=> fix: add appVersion to all telemetry events

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 2.0.7

src/components/molecules/Monaco/Monaco.tsx, src/components/organisms/GitCloneModal/GitCloneModal.tsx, src/components/organisms/GitPane/FileList.tsx, src/redux/parsing/parser.thunks.ts
- Remove `.git` from the project name on cloning
- Read-only mode when selecting a problem ( if there is no selection )
- Select files when a resource is selected
- Git staged/unstaged items check
=> fix: bugs/improvements

src/components/atoms/TabHeader/TabHeader.styled.tsx
=> fix: make tab heights consistent

src/components/organisms/NavigatorPane/NavigatorPane.tsx
=> fix: disabe recource create dropdown

src/components/molecules/ResourceFilter/ResourceFilter.styled.tsx
=> fix: remove scrollbar from filter when it is not opened

src/components/organisms/ValidationPane/ValidationPane.tsx
=> refactor: show by resource only in preview mode

src/components/organisms/GitCloneModal/GitCloneModal.tsx
=> fix: git clone

src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/hooks.tsx
=> fix: filter on folder

src/components/organisms/TemplateExplorer/TemplateForm/TemplateForm.tsx, src/shared/utils/index.ts, src/shared/utils/templateForm.ts
=> fix: format form data

src/components/molecules/Monaco/Monaco.tsx, src/components/molecules/Monaco/useDebouncedCodeSave.ts
=> fix: edit kustomize during previews

src/redux/reducers/main/previewReducers.ts, src/redux/services/preview.ts, src/redux/validation/validation.listeners.tsx
This PR skips unnecessary revalidation when attempting to preview 
-
- #3563 
-
-
=> fix: improve validation when entering previews

src/components/organisms/ExplorerPane/HelmPane/HelmList.tsx, src/components/organisms/ExplorerPane/ImagesPane/ImagesList.tsx, src/components/organisms/ExplorerPane/PreviewConfigurationPane/PreviewConfigurationList.tsx
=> fix: accordions loading when switching projects

package-lock.json
=> chore: recreate package-lock

src/components/organisms/Dashboard/Overview/InventoryInfo.tsx, src/constants/constants.ts
=> fix: fixed documentation links in cluster dashboard

src/components/organisms/ExplorerPane/FilePane/FileSystemTree/FileSystemTree.tsx, src/redux/selectors.ts, src/utils/fileExplorer.ts
=> fix: enhance toggle explore pane performance

src/components/molecules/ProjectsList/ProjectsList.tsx
=> fix: added possibility to order projects by name and lastOpened

src/components/organisms/ActionsPane/ActionsPane.tsx
=> fix: graph view visiblity

package-lock.json, package.json
=> fix: resize columns without lose its state

src/redux/appConfig/appConfig.slice.ts, src/redux/services/projectConfig.ts
- Do not write helm preview configs to project config when switching projects ( from previous to new )
=> fix: helm preview configurations

src/components/organisms/Dashboard/Tableview/Drawer.tsx, src/components/organisms/Dashboard/Tableview/Tableview.tsx, src/components/organisms/DashboardPane/DashboardPane.tsx
=> fix: bring events back & prevent autoclose of cluster drawer

src/components/organisms/ExplorerPane/FilePane/FileSystemTree/FileSystemTree.tsx, src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/TreeNodeFile.tsx, src/hooks/resourceHooks/useInstallDeploy.ts, src/redux/selectors.ts
=> fix: find helm resource by file path

src/redux/selectors/resourceMapSelectors.ts
=> fix: update selector dependencies

resources/schemas/1.26.3.json, src/shared/constants/k8s.ts
=> refactor: default 1.26.3 version

src/hooks/useTargetClusterNamespaces.ts
=> fix: reload cluster namespaces list on cluster connection

src/components/molecules/ResourceFilter/ResourceFilter.tsx
=> fix: hide namespace resource filter in cluster mode

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 2.0.8

package.json, patches/webpack-dev-server+4.13.2.patch
=> chore: hide ResizeObserver webpack errors

src/components/organisms/NavigatorPane/ResourceRenderer/ResourceInfoIcon.tsx, src/utils/yaml.ts
- Tooltip delay for mouse enter/leave on resource info
=> refactor: resource icon tooltip delay

src/components/organisms/Dashboard/Tableview/InfoTab.tsx
=> fix: crash when clicking on some resource from cluster list

src/components/organisms/DashboardPane/DashboardPane.tsx
=> fix: menu list

.github/README.md
=> chore: add readme

src/components/organisms/DashboardPane/DashboardFilteredMenu.tsx, src/components/organisms/DashboardPane/DashboardPane.tsx, src/components/organisms/DashboardPane/MenuItem.tsx
=> fix: overview rerendering

src/components/organisms/Dashboard/Overview/Status.tsx, src/components/organisms/DashboardPane/DashboardPane.tsx
=> refactor: improve dashboard

src/redux/thunks/removeResources.ts
This PR fixes the deletion of resources - #3791 
-
-
-
-
=> fix: fixed deletion of resources

package-lock.json, package.json, src/components/atoms/StyledComponents/TitleBarWrapper.tsx, src/components/atoms/TabHeader/TabHeader.styled.tsx, src/components/organisms/ActionsPane/ActionsPane.styled.tsx, src/components/organisms/ActionsPane/ActionsPaneHeader.tsx
=> fix: editor titlebar styling

src/components/atoms/Dots/Dots.styled.tsx, src/components/organisms/ExplorerPane/FilePane/FilePane.tsx, src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/TreeNodeFolder.tsx, src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/hooks.tsx, src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/index.tsx, src/components/organisms/NavigatorPane/NavigatorPane.tsx, src/index.css, src/redux/selectors.tsx, src/utils/git.ts
- Add root folder entry in file tree
- Smaller dots size
- TitleBar description vertically aligned
=> feat: root folder node

src/redux/reducers/ui.ts
- Show explorer pane after opening a project
=> refactor: on open project show explorer

package-lock.json, package.json, src/components/atoms/StyledComponents/TitleBarWrapper.tsx, src/components/molecules/FormEditor/FormEditor.styled.tsx, src/components/molecules/FormEditor/FormObjectFieldTemplate.tsx, src/components/molecules/ResourceFilter/ResourceFilter.styled.tsx, src/components/organisms/ActionsPane/ActionsPane.styled.tsx, src/components/organisms/ActionsPane/ActionsPane.tsx, src/components/organisms/CompareSyncPane/CompareSyncPane.styled.tsx, src/components/organisms/ExplorerPane/AccordionPanel/AccordionTitleBarContainer.tsx, src/components/organisms/ExplorerPane/ExplorerPane.tsx, src/components/organisms/ExplorerPane/FilePane/FilePane.tsx, src/components/organisms/ExplorerPane/FilePane/FileSystemTree/FileSystemTree.tsx, src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/TreeNodeFolder.tsx, src/components/organisms/ExplorerPane/HelmPane/HelmPane.tsx, src/components/organisms/ExplorerPane/ImagesPane/ImagesPane.tsx, src/components/organisms/ExplorerPane/KustomizePane/KustomizePane.tsx, src/components/organisms/ExplorerPane/PreviewConfigurationPane/PreviewConfigurationPane.tsx, src/components/organisms/GitPane/GitPane.tsx, src/components/organisms/NavigatorPane/NavigatorPane.tsx, src/components/organisms/PaneManager/PaneManager.tsx, src/components/organisms/ValidationPane/ValidationPane.styled.tsx, src/components/organisms/ValidationPane/ValidationPane.tsx
- New closable pane icon
- Title bar padding/margins
- Core title bar height
=> fix: title bar

src/components/molecules/ProjectCard/ProjectCard.tsx, src/components/molecules/ResourceFilter/ResourceFilter.tsx
=> fix: transferred resources when switching projects

src/redux/thunks/utils.ts
This PR improves timestamp handling for cluster resources - #3812 
-
-
-
-
=> fix: formatting or removal of timestamp properties retrieved from cluster

electron/app/services/cluster/handlers/setup.ts, electron/kubernetes/ProxyInstance.ts
=> refactor: add Windows specific messages when throwing errors

src/components/organisms/ExplorerPane/FilePane/FileSystemTree/FileSystemTree.tsx
=> fix: don't try expanding on root click ( file tree )

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 2.0.10

src/editor/listeners/editorSelection.listener.ts, src/editor/listeners/editorTextUpdate.listener.ts, src/redux/services/clusterResourceWatcher.ts, src/redux/thunks/utils.ts
This PR fixes timestamp parsing for resources that are updated from cluster - and some other minor glitches found while debugging...
-
-
-
-
=> fix: glitches related to cluster-resource updates and cluster-mode

src/redux/cluster/thunks/connect.ts, src/redux/thunks/cluster/loadClusterResources.ts
=> fix: skip checking all namespaces existence

src/shared/models/rootState.ts, src/shared/utils/selectors.ts
=> fix: update electron menu typescript

src/components/organisms/PageHeader/ClusterControl/Buttons.tsx, src/redux/cluster/thunks/connect.ts
=> fix: prioritize connecting to last namespace

src/components/organisms/DashboardPane/DashboardPane.tsx, src/kindhandlers/CustomResourceDefinition.handler.ts
This PR...
- instead of loading the crd definitions. loading crd resources 
-
-
-
=> fix: load custom resource items in dashboard

electron/app/menu.ts, src/components/molecules/ResourceFilter/ResourceFilter.tsx, src/components/molecules/ResourceRefsIconPopover/RefsPopoverContent.tsx, src/components/organisms/AboutModal/AboutModal.tsx, src/components/organisms/NavigatorPane/NavigatorPane.tsx, src/editor/editor.utils.ts, src/editor/enhancers/k8sResource/symbols.ts
This PR...
- Added current version number to the system app menu
- Change the text on the About modal
- Display of symbols markdown hovers (using tables now)
- Ref link navigation while Graph view is open
- Symbols with parents weren't showing up
- Double scroll of the resource filter
=> Small fixes and changes

src/components/organisms/ValidationPane/ValidationPane.tsx, src/redux/reducers/main/mainSlice.ts
- Connect button loading
- No reloading of validation problems when in cluster mode
=> fix: cluster validation

src/components/molecules/Logs/Logs.styled.ts, src/components/molecules/Logs/Logs.tsx, src/components/organisms/NavigatorPane/ResourceNavigator.tsx
- Show logs error if any instead of empty container
=> refactor: show logs error if any

src/components/molecules/ResourcePopover/ResourcePopover.tsx
=> refactor: tooltip_delay

src/redux/thunks/cluster/loadClusterResources.ts
=> fix: <all> namespace cluster resources

src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/hooks.tsx
=> fix: add menu divider

src/redux/appConfig/appConfig.slice.ts, src/redux/validation/validation.slice.ts
This PR...
- check folder existence before opening it 
-  
https://user-images.githubusercontent.com/20525304/235916757-897e346f-afaf-4480-a398-8e5034b4db55.mp4
-
-
=> fix: check folder existence before opening it 

src/redux/validation/validation.slice.ts
This PR...
-  reset validation count when switching projects
-
-
-
=> fix: reset validation count when switching projects

src/redux/validation/validation.slice.ts
=> fix: reset validation counts

electron/app/services/cluster/handlers/setup.ts, src/index.tsx
=> refactor: log unknown cluster error reason

src/redux/parsing/parser.thunks.ts, src/redux/parsing/parser.worker.ts, src/redux/parsing/parser.worker.types.ts, src/redux/validation/validation.thunks.ts
This PR fixes the first issue in #3859 
-
-
-
-
=> fix: pass files to refs parser

electron/app/menu.ts
- Create new Monokle window on click
=> fix: create monokle new window

src/components/organisms/SettingsPane/Settings/Settings.tsx, src/redux/initialState.ts, src/redux/services/projectConfig.ts, src/shared/models/config.ts
This PR...
- removed hideExcludedFilesInFileExplorer
- removed hideUnsupportedFilesInFileExplorer
-
-
-
=> fix: removed unused settings

electron/app/autoUpdater.ts, src/components/molecules/NewVersionNotice/NewVersionNotice.tsx
=> fix: new version notice

electron/app/services/cluster/utils/getDefaultKubeConfig.ts
=> refactor: get default kubeconfig

src/components/organisms/PaneManager/PaneManager.tsx
=> fix: closable explorer left pane only

src/redux/validation/validation.listeners.tsx
=> refactor: throttling incremental validation

package-lock.json, package.json, src/components/organisms/PaneManager/PaneManager.tsx
- Hiding bottom terminal would lose state
=> fix: resizable bottom terminal

src/redux/reducers/ui.ts
=> fix: reset collapsedResourceKinds on previews

electron/app/ipc/ipcListeners.ts, src/components/molecules/FormEditor/FormEditor.tsx, src/components/molecules/ProjectCard/ProjectCard.tsx, src/components/organisms/ActionsPane/ActionsPane.tsx, src/components/organisms/GitCloneModal/GitCloneModal.tsx, src/components/organisms/LearnPage/LearnPage.tsx, src/components/organisms/PageHeader/PageHeader.tsx, src/components/organisms/StartPage/StartPage.tsx, src/editor/enhancers/k8sResource/refs.ts, src/shared/models/telemetry.ts
This PR adds more telemetry to the starting panels
-
-
-
-
=> fix: added more telemetry to app start panels

electron/app/services/cluster/handlers/debugProxy.ts, electron/kubernetes/ProxyInstance.ts
=> fix: show cluster connection error description

src/components/organisms/SettingsPane/GlobalSettings/GlobalSettings.tsx, src/redux/appConfig/appConfig.slice.ts, src/redux/initialState.ts, src/shared/models/config.ts
=> fix: remove use kubectl proxy option

src/editor/CodeEditor/CodeEditor.tsx, src/editor/editor.instance.ts, src/editor/editor.slice.ts, src/shared/models/telemetry.ts
=> chore: add telemetry for code changes

src/components/organisms/DashboardPane/DashboardFilteredMenu.tsx
=> refactor: center scroll

src/components/organisms/ExplorerPane/HelmPane/HelmChartRenderer/HelmChartRenderer.styled.tsx, src/components/organisms/ExplorerPane/HelmPane/HelmChartRenderer/HelmChartRenderer.tsx, src/components/organisms/ExplorerPane/HelmPane/HelmValueRenderer/HelmValueRenderer.styled.tsx, src/components/organisms/ExplorerPane/HelmPane/HelmValueRenderer/HelmValueRenderer.tsx, src/components/organisms/ExplorerPane/KustomizePane/KustomizeRenderer/KustomizeRenderer.styled.tsx, src/components/organisms/ExplorerPane/KustomizePane/KustomizeRenderer/KustomizeRenderer.tsx, src/components/organisms/ExplorerPane/PreviewConfigurationPane/PreviewConfigurationRenderer/PreviewConfigurationRenderer.tsx
=> refactor: show "Preview" without hovering

CHANGELOG.md
=> chore(release): 2.1.0

src/components/organisms/Dashboard/Overview/Activity.tsx, src/components/organisms/Dashboard/Overview/Overview.tsx, src/components/organisms/Dashboard/Overview/Status.tsx, src/shared/models/telemetry.ts
This PR adds some more telemetry to the dashboard
-
-
-
-
=> fix: improve telemetry of cluster dashboard

src/index.css
=> refactor: separator border color

package.json
=> fix: don't ask for permission on windows installer

package.json
=> fix: bring back differentialPackage

src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/hooks.tsx, src/redux/services/fileEntry.ts
- Exclude subfiles too from an excluded file path
- Bring back the `Add/Remove from exclude` option for folders
=> fix: excluded files

src/components/atoms/FilePatternList/FilePatternList.tsx, src/components/organisms/SettingsPane/Settings/Settings.tsx, src/redux/services/fileEntry.ts, src/redux/services/helm.ts
=> fix: extract resources only for files not excluded

electron/app/ipc/ipcListeners.ts, package-lock.json, package.json, src/components/organisms/NavigatorPane/KindRenderer/ResourceCounter.tsx, src/redux/reducers/main/previewReducers.ts, src/redux/services/preview.ts, src/redux/services/selection.ts
- Update vm2 version
- Remove some warnings
=> chore: update vm2

src/components/organisms/SettingsPane/Settings/Settings.tsx
- Loading of the kubeconfig path browse button
=> fix: kubeconfig path browse loading

electron/app/commands.ts, electron/app/extensions/downloadExtension.ts, electron/app/extensions/downloadExtensionEntry.ts, electron/app/extensions/loadExtension.ts, electron/app/index.ts, electron/app/ipc/ipcListeners.ts, electron/app/openApplication.ts, electron/app/services/cluster/daemons/kubeconfigWatcher.ts, electron/app/services/cluster/handlers/setup.ts, electron/app/services/pluginService.ts, electron/app/services/templateService.ts, electron/app/utils.ts, electron/app/utils/ipc.ts, electron/kubernetes/ProxyInstance.ts, src/components/organisms/Dashboard/Tableview/Drawer.tsx, src/components/organisms/Dashboard/Tableview/ErrorCell.tsx, src/components/organisms/Dashboard/Tableview/InfoTab.tsx, src/components/organisms/Dashboard/Tableview/TableCells.tsx, src/components/organisms/Dashboard/Tableview/Tableview.tsx, src/components/organisms/PageHeader/ClusterControl/NamespaceSelect.tsx, src/redux/dashboard/slice.ts, src/redux/thunks/cluster/loadClusterResources.ts, src/shared/models/dashboard.ts, src/shared/models/telemetry.ts
=> fix: improve dashboard telemetry and main thread logging

README.md
=> refactor: add back dark mode logo

src/redux/validation/validation.listeners.tsx
- Validate resources when removing a resource
=> fix: validation when remove resource

src/redux/cluster/thunks/connect.ts, src/redux/parsing/parser.thunks.ts, src/redux/parsing/resourceParser.ts, src/redux/reducers/main/mainSlice.ts, src/redux/thunks/setRootFolder.ts, src/redux/validation/validation.listeners.tsx, src/redux/validation/validation.thunks.ts
- Switching projects in cluster mode doesn't transfer resources
=> fix: switching projects in cluster mode

src/components/organisms/Dashboard/Overview/InventoryInfo.tsx
- Show the k8s version when in cluster mode using `kubectl version`
=> fix: show k8s version in cluster mode

src/components/molecules/Logs/Logs.styled.ts, src/components/molecules/Logs/Logs.tsx, src/components/organisms/Dashboard/Tableview/TerminalTab.styled.tsx, src/shared/models/dashboard.ts
- Improve readability ( changed styling to a more terminal-like)
- Add search input for filtering logs
- Highlight of the searched value
=> refactor: logs

src/editor/CodeEditor/handleCodeChanges.ts
This PR...
-
- https://github.com/kubeshop/monokle/issues/3998
-
-
=> fix: saving code changes on helm values files

src/components/organisms/ActionsPane/ActionsPane.tsx
=> fix: avoid reset form tab

src/components/organisms/Dashboard/Tableview/Drawer.tsx, src/components/organisms/Dashboard/Tableview/GraphTab.tsx, src/shared/models/dashboard.ts
- Add graph view tab in cluster dashboard drawer
=> feat: add graph view in cluster dashboard

src/components/molecules/AIGenerationModal/AIGenerationModal.tsx, src/components/molecules/AIGenerationModal/ai.prompt.ts, src/redux/reducers/ui.ts, src/shared/models/telemetry.ts
This PR...
- added telemetry events for the new AI modal
-
-
-
=> chore: add telemetry for AI modal

src/components/molecules/AIGenerationModal/ai.prompt.ts
=> fix: eslint possible undefined warning

package-lock.json, src/components/molecules/ProjectCard/ProjectCard.tsx, src/components/molecules/ProjectsList/ProjectsList.tsx, src/components/organisms/StartPage/StartPage.tsx, src/hooks/useStartPageOptions.tsx, src/shared/models/ui.ts
- Merge Recent/All Projects into simple Projects
- Sort them by `last-opened` by default
=> refactor: merge all/recent projects into projects page

src/components/organisms/StartPage/StartPageHeader.tsx
=> refactor: start page search input placeholder

src/components/organisms/HelmRepoPane/HelmChartsView.tsx, src/components/organisms/HelmRepoPane/styled.tsx
=> fix: improve helm error

src/editor/enhancers/applyResourceEnhancers.ts, src/editor/enhancers/index.ts, src/editor/listeners/editorSelection.listener.ts, src/editor/listeners/editorTextUpdate.listener.ts, src/redux/selectors/helmGetters.ts
This PR...
- syncing changes to files from outside Monokle to the editor
- make a change on a file with another editor
=> fix: editor sync external changes

src/components/molecules/AIGenerationModal/AIGenerationModal.styled.tsx, src/components/molecules/AIGenerationModal/AIGenerationModal.tsx, src/components/molecules/FilterPopover/keyValueInput/KeyValueInput.style.ts, src/components/organisms/CompareSyncPane/ComparisonList/ComparisonList.styled.tsx, src/components/organisms/CompareSyncPane/ResourceList/ResourceList.styled.tsx, src/hooks/menuItemsHooks/useHelpMenuItems.tsx, src/shared/styles/colors.ts
=> fix: ai generate modal ui

src/redux/reducers/ui.ts
=> fix: show files from explorer when opening a new project

src/components/molecules/AIGenerationModal/AIGenerationModal.tsx, src/shared/models/telemetry.ts
=> chore: track unsuccessful AI generation

src/redux/thunks/setRootFolder.ts, src/shared/models/telemetry.ts
=> fix: add number of values files to open_project telemetry

src/components/molecules/Logs/Logs.tsx, src/shared/models/telemetry.ts
- Add telemetry for searching through the logs
=> feat: telemetry for logs search

src/components/organisms/PaneManager/PaneManager.tsx
This PR...
-
-
-
-
https://github.com/kubeshop/monokle/assets/20525304/8dccb3f1-9ed6-4910-8496-1b54df7c695e
=> fix: toggle dashboard left menu

src/components/organisms/GitPane/BottomActions.tsx
=> fix: git publish local branch and commit

src/editor/editor.instance.ts
=> chore: fix editor error/warning hover telemetry

src/components/organisms/HelmRepoPane/HelmChartDetails/HelmChartDetails.tsx, src/redux/thunks/InstallHelmRepoChart.ts, src/shared/utils/commands/helm.ts
=> fix: only load selected chart versions

package-lock.json
=> fix: sync semver libe  package-lock with package.json 

src/components/organisms/ExplorerPane/HelmPane/HelmContextMenu.tsx, src/components/organisms/ExplorerPane/HelmPane/HelmPane.tsx, src/components/organisms/ExplorerPane/HelmPane/HelmValueRenderer/HelmValueRenderer.styled.tsx, src/components/organisms/ExplorerPane/HelmPane/HelmValueRenderer/HelmValueRenderer.tsx, src/redux/selectors.tsx
=> fix: allow editing of values files at all times

src/redux/validation/validation.listeners.tsx, src/shared/models/telemetry.ts, src/utils/executionTime.ts
=> chore: improve validation telemetry

package-lock.json, package.json, src/components/organisms/ValidationPane/ValidationPane.tsx, src/utils/downloadJson.ts
=> chore: update @monokle/components

electron/app/ipc/ipcMainRedux.ts
This PR...
- 
- prevent dispatch to destroyed window 
-
-
=> fix: prevent dispatch to destroyed window

src/shared/utils/segment.ts
=> fix: segment error handler

electron/app/utils/git.ts
=> fix: read file safely

src/redux/validation/validation.listeners.tsx
=> fix: validate incremental telemetry

src/index.tsx
=> chore: console function for machine id

src/redux/appConfig/appConfig.slice.ts, src/shared/constants/sentry.ts
=> fix: skip noisy errors from sentry

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 2.3.1

.github/workflows/monokle-publish-test.yml
=> refactor: build test action

src/components/organisms/ActionsPane/ActionsPane.tsx, src/components/organisms/ActionsPane/ProjectOverview/ProjectOverview.tsx, src/components/organisms/ActionsPane/ProjectOverview/index.ts, src/components/organisms/ActionsPane/ProjectOverview/styled.tsx, src/redux/selectors.tsx, src/shared/models/telemetry.ts
=> fix: project summary overview

electron/app/services/cluster/ipc.ts, electron/app/services/cluster/utils/getDefaultKubeConfig.ts, src/redux/cluster/listeners/kubeconfig.ts, src/redux/cluster/selectors.ts, src/redux/cluster/service/kube-control.ts
=> fix: ENV kubeconfig with multiple files

src/redux/store.ts, src/utils/helm.ts, src/utils/ipc.ts
=> chore: improved production debugging

src/components/organisms/HelmRepoPane/HelmChartsView.tsx, src/redux/cluster/getters.ts, src/redux/cluster/listeners/clusterArgsChanged.ts, src/utils/cluster.ts
=> fix: helm kubeconfig argument

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 2.3.2

src/redux/compare/slice.ts, src/shared/models/telemetry.ts
=> chore: improve compare telemetry

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 2.3.3

src/redux/thunks/cluster/loadClusterHelmReleases.ts, src/redux/thunks/cluster/loadClusterResources.ts
=> fix errors related to <not-namespaced> option

src/components/organisms/PaneManager/activities.tsx, src/components/organisms/ResourceSetSelector/ResourceSetTypeSelect.tsx
=> feat: compare clusters in quick cluster mode

.github/workflows/monokle-build-nightly.yml, .github/workflows/monokle-publish-downloads.yml, .github/workflows/monokle-publish-test.yml, .github/workflows/monokle-publish-updater.yml, .github/workflows/monokle-publish.yml, CHANGELOG.md, notarization/afterSignHook.js, package.json
=> chore: release 2.4.0

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 2.4.1

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 2.4.2

package-lock.json, package.json, src/redux/validation/validation.loader.ts, src/redux/validation/validation.worker.ts, src/redux/validation/validator.ts
=> refactor: update validation package

electron/app/services/cluster/utils/getDefaultKubeConfig.ts, src/components/organisms/SettingsPane/GlobalSettings/GlobalSettings.tsx, src/redux/cluster/selectors.ts, src/shared/constants/electronStore.ts, src/shared/utils/commands/execute.ts
=> add setting for binary configuration & fix kubectl path splitting

package.json
=> fix: updated description and synopsis

src/components/organisms/Dashboard/TableView/TableView.tsx, src/components/organisms/SettingsPane/GlobalSettings/GlobalSettings.tsx, src/redux/validation/validation.listeners.tsx, src/shared/constants/electronStore.ts
=> Setting to disable cluster validation & added table pagination

src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/TreeNode.styled.tsx, src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/TreeNodeFile.tsx, src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/TreeNodeFolder.tsx, src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/hooks.tsx, src/constants/constants.ts, src/redux/selectors/dryRunsSelectors.ts, src/utils/files.ts
=> improve filtering visuals

src/shared/constants/electronStore.ts
=> fix: improved exclusion of default node_modules exclusion

CHANGELOG.md, package-lock.json, package.json
This PR is a part of 2.4.4 version release.
-
-
-
-
=> chore(release): 2.4.4

src/redux/appConfig/appConfig.listeners.ts
=> fix: missing crds folder runtime error
